BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBB BBBBBB

BBBBB BBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXX XXXX XXXXX XXXXXXXXX XXXXXXXXXX
        XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX
           XXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
           XXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBB
            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXX
        XXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBX
                   XXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                   XXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX
                XX XXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX
                XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXX
                   XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                XXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX

            XX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
                
            XXXX

            XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXX
                BBBBBBBBBB
                BBB BBBBB BB BBBB
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXFFFFFFFFFFFFXX
                        XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXX
                            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBX
                               XXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                               XXXXXXXXXXXXXX
                                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX

                            XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXXXXX
                               XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBXX
                                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                            XXXX

                        XXXXXX

                        XX XXXXXXXX
                           XXXXXXXXXXXXXXXXXX XXXX XXXXX XXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                                      XXXXX XXXXXXXXXXXXXXXXXXXX XXX X XXX XXXX XXXXX XXX X XXXX XXXXXXX XXX X XXXX XXXXXXXX XXX X XXXX XXXXXXXXXXXXXXXXXXXXXX XXX X XXX XXXXX XXXXXXXXXXXXXX XXX X XXX XXXXX XXXXXXX
                            XXXXXX
                        XXXX
                        XXXX XXXXXXXXXX XXXX XXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX

                            XXXX XXXXXXXXXXXXX
                                BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBB
                                    
                                BBBB
                                    FFFFFFFFFFFFFFFF FFF FFFFF FFFFFFF FFFFFFFFFFFFFFF FFFFFFFFFF FFFFFFFFFF
                                BBBBB
                            XXXXXX
                            XX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
                        XXXXXX
                    XXXXXX

                BBBBBB
            XXXXXXX
        XXXXXX

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX

BBBBBBBB

BBBBB BBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXX
        XXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXX
                XXXXXXX XXXXXXXX XXXXXXX XXX X
                    XXXXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXXXXX
                    XXXXXXXX
                        XXXX XBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                        XXXXX XXXXXXX
                        XXXXXXXX XXXXXXXXXXXXXXX XXXX
                        XXXXX X
                            XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XX
                        XXXXXXXXX XXXXXXX
                        XXXXXXXX XXXXXXXX XXXXXX X
                            XXXXXXXXXXXXXXXXXXXXXXXXXX
                        XX
                        XXXXXX XXXXXXXX XXXXXX X
                            XXXXXXXXX XXXXX XXXXXXXXXXX
                        X
                    XXX
                X
            XXX
        XXX
    XXXXXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBB