BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBB
    XXXXXXXX
        XXX XXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X
          XXXXXXXXXXXXXXXX XXXXXXXXX XX XXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX

        XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
            XX XXXXXX XX X XX XXXXX XX X XX XXXXX XX XX X
              XXXXXXXXXXXXXXX X XXXXXX
          X XXXX X
              XXXXXXXXXXXXXXX X XXXXX
          X
        X
    XXXXXXXXX
BBBBBBBB