# Generated by Django 3.2.15 on 2022-10-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0015_activitychannelgroup_activitychannelrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="card_class",
            field=models.CharField(
                blank=True,
                help_text="Additional classes that are added to the activity card for formatting",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_format",
            field=models.CharField(
                default="{category_abbreviation} {name} ({abbreviation})",
                help_text="Format for the short name to display the activity. Possible keys are: abbreviation, name, category_name and category_abbreviation",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="short_name_format",
            field=models.CharField(
                default="{category_abbreviation} {abbreviation}",
                help_text="Format for the short name to display the activity. Possible keys are: abbreviation, name, category_name and category_abbreviation",
                max_length=300,
            ),
        ),
    ]
