# (generated with --quick)

import torch
from torch import nn

def network_init(m) -> None: ...
def soft_update_params(net, target_net, tau) -> None: ...
def to_torch(xs, device) -> tuple: ...
def update_linear_schedule(optimizer, epoch, total_num_epochs, initial_lr) -> None: ...
