# Generated by Django 3.2.15 on 2022-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0016_auto_20221020_1516"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="activitymaterialrelation",
            constraint=models.UniqueConstraint(
                fields=("activity", "material"),
                name="unique_activity_relation_for_material",
            ),
        ),
    ]
