# Version file autogenerated by the build process
version = '0.11.0'
build = 1131
vcs_info = 'Git SHA1 aaeef90a committed on 2023-05-13'
package_name = 'ksconf'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.11.0"\nKSCONF_BUILD="1131"\nKSCONF_VCS_INFO="Git SHA1 aaeef90a committed on 2023-05-13"')
