
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-11T22:41:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6d0b38b4127c6fbca9a2e5ea9be91048d5799177",
 "version": "2.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
