# coding: utf-8

"""
    SYSNET CRZP connector API

    SYSNET CRŽP connector REST API (IPPC & CITES extension)  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RuianReference(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'isui_code': 'int',
        'name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'isui_code': 'isuiCode',
        'name': 'name'
    }

    def __init__(self, id=None, isui_code=None, name=None):  # noqa: E501
        """RuianReference - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._isui_code = None
        self._name = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if isui_code is not None:
            self.isui_code = isui_code
        if name is not None:
            self.name = name

    @property
    def id(self):
        """Gets the id of this RuianReference.  # noqa: E501


        :return: The id of this RuianReference.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this RuianReference.


        :param id: The id of this RuianReference.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def isui_code(self):
        """Gets the isui_code of this RuianReference.  # noqa: E501


        :return: The isui_code of this RuianReference.  # noqa: E501
        :rtype: int
        """
        return self._isui_code

    @isui_code.setter
    def isui_code(self, isui_code):
        """Sets the isui_code of this RuianReference.


        :param isui_code: The isui_code of this RuianReference.  # noqa: E501
        :type: int
        """

        self._isui_code = isui_code

    @property
    def name(self):
        """Gets the name of this RuianReference.  # noqa: E501


        :return: The name of this RuianReference.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RuianReference.


        :param name: The name of this RuianReference.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RuianReference, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RuianReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
