# Generated by Django 3.2.7 on 2022-03-24 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0009_remove_activity_mailing_list"),
        ("programme", "0016_alter_sessionmaterial_material_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                help_text="Please select the working or project group that this contribution fits the best.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="activities.activity",
                verbose_name="Working Group/Project Group",
            ),
        ),
    ]
