XXXXXXXXX XXXXX
BBBB BBBB BBBBBB
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX gettext(u'Survey')  X XXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    BBBBB BBBBBBBBBBBBBBBBB
XXXXXXX
XXXXXX
    BB BBBBBBBB
        BBB BBBBBBB BB BBBBBBBB
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBB
    BBBBB
    XXXX XXXXXXXXXXXXXXXX XXXXXXXXX
        BBBBB BBBBBBB BBBBBBBB
    XXXXXX

    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
    BBBBB BBBBBBBBBBBBBBBB
XXXXXXX
XXXXXXX