VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('13')
VERSION_HOUR = int('09')
VERSION_MINUTE = int('10')
MAJOR_VERSION = 0
MINOR_VERSION = 28
PATCH_VERSION = 202305130910
version_date = '2023/05/13 09:10'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
