"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class BeesAlert(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SWARMING_FIELD_NUMBER: builtins.int
    DEATH_FIELD_NUMBER: builtins.int
    @property
    def swarming(self) -> global___Swarming: ...
    @property
    def death(self) -> global___Death: ...
    def __init__(
        self,
        *,
        swarming: global___Swarming | None = ...,
        death: global___Death | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["death", b"death", "swarming", b"swarming", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["death", b"death", "swarming", b"swarming", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["type", b"type"]) -> typing_extensions.Literal["swarming", "death"] | None: ...

global___BeesAlert = BeesAlert

@typing_extensions.final
class Swarming(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROBABILITY_FIELD_NUMBER: builtins.int
    probability: builtins.float
    def __init__(
        self,
        *,
        probability: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["probability", b"probability"]) -> None: ...

global___Swarming = Swarming

@typing_extensions.final
class Death(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROBABILITY_FIELD_NUMBER: builtins.int
    probability: builtins.float
    def __init__(
        self,
        *,
        probability: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["probability", b"probability"]) -> None: ...

global___Death = Death
