# Generated by Django 4.1.6 on 2023-05-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fwadmin", "0004_remove_sessionrequest_action_reason_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sessionrequest",
            old_name="approved_by",
            new_name="managed_by",
        ),
        migrations.AlterField(
            model_name="sessionrequest",
            name="status",
            field=models.CharField(default="requested", editable=False, max_length=100),
        ),
    ]
