# Generated by Django 4.1.6 on 2023-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fwadmin", "0005_rename_approved_by_sessionrequest_managed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firewall",
            name="access_key",
        ),
        migrations.AddField(
            model_name="firewall",
            name="verify_cert",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="firewall",
            name="secret_key",
            field=models.CharField(max_length=200),
        ),
    ]
