# (generated with --quick)

import hsuanwu.env.utils
from typing import Any, Optional, Type

HsuanwuEnvWrapper: Type[hsuanwu.env.utils.HsuanwuEnvWrapper]

def make_atari_env(env_id: str = ..., num_envs: int = ..., device: str = ..., seed: int = ..., frame_stack: int = ..., distributed: bool = ...) -> Any: ...
def make_bullet_env(env_id: str = ..., num_envs: int = ..., device: str = ..., seed: int = ..., distributed: bool = ...) -> Any: ...
def make_dmc_env(env_id: str = ..., num_envs: int = ..., device: str = ..., resource_files: Optional[list] = ..., img_source: Optional[str] = ..., total_frames: Optional[int] = ..., seed: int = ..., visualize_reward: bool = ..., from_pixels: bool = ..., height: int = ..., width: int = ..., camera_id: int = ..., frame_stack: int = ..., frame_skip: int = ..., episode_length: int = ..., environment_kwargs: Optional[dict] = ...) -> Any: ...
def make_minigrid_env(env_id: str = ..., num_envs: int = ..., fully_observable: bool = ..., seed: int = ..., frame_stack: int = ..., device: str = ..., distributed: bool = ...) -> Any: ...
def make_multibinary_env(env_id: str = ..., num_envs: int = ..., device: str = ..., seed: int = ..., distributed: bool = ...) -> Any: ...
def make_procgen_env(env_id: str = ..., num_envs: int = ..., device: str = ..., seed: int = ..., gamma: float = ..., num_levels: int = ..., start_level: int = ..., distribution_mode: str = ...) -> Any: ...
