# Generated by Django 3.2.7 on 2022-03-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_submission_licenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="submission_for_activity",
            field=models.BooleanField(
                blank=True,
                help_text="Ask submitting people to select a working/project group in the community for the contribution. If you select <it>No</it>, people cannot select an activity at all. If you select <it>Yes</it>, people are forced to select an activity.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="submission_for_session",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Ask submitting people to select a session for the contribution. If you select <it>No</it>, people cannot select a session at all. If you select <it>Yes</it>, people are forced to select a session.",
                null=True,
            ),
        ),
    ]
