
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-17T15:28:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "de8817628e6fcc0447409dd387e5c4451a70920b",
 "version": "v4.10.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
