iconsDict = { 
# Emoji    Discord             ios
  '🔥' : [':fire:',                     'fire'],
  '❌' : [':x:',                        'cross mark'],
  '✅' : [':white_check_mark:',         'check mark symbol'],
  '🚩' : [':triangular_flag_on_post:',  'triangular flag on post'],
  '📄' : [':page_facing_up:',           'page facing up'],
  '⚠ ' : [':warning:',                  'warning'],
  '💙' : [':blue_heart:',               'blue heart'],
  '💜' : [':purple_heart:',             'purple heart'],
  '💕' : [':two_hearts:',               'two hearts'],
  '🍆' : [':eggplant:',                 'eggplant'],
  '🍑' : [':peach:',                    'peach'],
  '💦' : [':sweat_drops:',              'water droplets'],
  '✨' : [':sparkles:',                 'sparkles'],
  '🚧' : [':construction:',             'construction sign'],
  '❗' : [':exclamation:',              'red exclamation mark'],
  '❓' : [':question:',                 'red question mark'],
  '™️' : [':tm:',                        'trade mark sign'],
  '📁' : [':file_folder:',              'closed file folder'],
  '🎉' : [':tada:',                     'party popper'],
}
# '' : ['::', ''],