XXXX XXXXXXXXXXX XXXX XXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXX XXXXXXXXXX
        BB BBBBBBBBBBBB BB BBBBBBBBB
            XXXXXXXXXXXX
        BBBB BBBBBBBBBBBB BB BBBBBBBBB
            XXXXXXXXXXXX
        BBBB BBBBBBBBBBBB BB BBBBBB
            XXXXXXXXXX
        BBBB BBBBBBBBBBBB BB BBBBBBB
            XXXXXXXXXX
        BBBB
            XXXXXXXXXXX
        BBBBB
            XXXXXXXX XXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXX

            XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXX
                      XXXXXXXXX XXXXXXX X X XXXXXXX XXXX XXXXXXXXXXXXXXXXXXX X X XXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXX X X XXXXXXXX XXXXXXXX XXXXXXXXXXXXX XXXXXXX X X XXXXXXXXXXXXXXXXXXXX XX XXXXX XXXXXXX X X XXXXXXXXXXX
                      XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
        XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX
             XXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
                  XXXXX XXXX X XXXXX XXX X X XXXXX X X X X XXXX XXXXX
        XXXXXX

        XXXX XXXXXXXXXXX XXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXX
                
            XXXXX

            XX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
                
            XXXX
        XXXXXX
    XXXXXX
XXXXXX