XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX
        BB BBBBBBBBBBB BB BBBB
            XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXXXXXXXX
                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX
                BBBBB
                BB BBB BBBBBBBBB
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBX XXXXXXXXXXX XXXXX XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                            XXXXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXX X X XXXX X X X X XXX XXX XX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXXX XXXXX X XX XXXXXXX X XXXXX XXXXX XXXXX XXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX
                              XXXXXX
                    XXXX
                BBBBB
                BB BBBBBBBBBBBBBBBBBBBBBBB
                    XX XXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
                        XXXXXXXXXXXXXXXXXXXXXXXXXXXXBBB BBBBBBBBBBBBBBBBBBBB BBBBBBBBBXX
                        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                    XXXX
                BBBBB
            XXXXXX
        BBBBB
        XXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXXXXXXXX
            XXXX XXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXX

            XX XXXXXXXXXXX XXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXXX  XXXXXXX
                XXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX  XXXXXXX
            XXXX
        XXXXXXX
        XXX XXXXXXXXXXX XXXXXX

        BBB BBBBBB BB BBBBBBBBBBBBBBBBBBBBB
            XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXX XXXXXX
        BBBBBB

    XXXXXXXXXXXXX
XXXXXX