BBBB BBBB
XXXX XXXXXX XXXX XXXX XXX
XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXX
        XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXXX
                    XXXX XXXXXXX XXXX XXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXXXXXXXXXX XXXX XXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX gettext(u'Home') XXXXXXX
                    XXXX
                XXXXXX
                XXXX XXXXXXX XXXXXX XXXXX XXX
                XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Surveys') XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'About') XXXX
                XXXXXX
            XXXXXX
            XXXX XXXXXXXXX XXXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXX XX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                         XXXXXXXXXX X XX XXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXX XXX XXXX XXXXX
                    XXXXXX
                XXXX
            XXXXXX
            XXXX XXXXXX XXXX XXXXXX XXX
            XXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX
                XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXX XXX XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX X
                         XXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXXXXXXXXX
                         XXXXXXXXXXXXXXXX
                         XXXXXXXXXX X XX XXX
                         XXXXXXXXXXXXXXXXXXXXX
                    X
                        XXXXX XXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX
                    XXXXXX
                XXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
        XXX XXXXXXXXX
            XXX XXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'Surveys') XXXX
            XXXXX
            XXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX gettext(u'About') XXXX
            XXXXX
        XXXXX
    XXXXXX
    XXXXXXXX
        XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX
    XXXXXXXXX
XXXXXX