BBBB BBBB

XXXX
  XXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXX XXXXXX XXXXX XXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXX
  XXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXX
  XXXX
    XXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX
        XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXX
        XXX
          XXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Confirmation') 
        XXXXX
        XXXXXXXXX XXXXXXXXX
        XXXXXXX
          XXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX
          XXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX
            XXXXXXXXXX X XX XXX
            XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXX XXXXX
            XXXXX
              XXXXXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXXXXXXXXXX
              XXXXX XXXXX XXX XXXX XXX XX
          XXXXXX
        XXXXXXXXX
      XXXXXX

      XXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX gettext(u'Are you sure to delete %(html)s?') SSS SSS SSSS SS SSSSSS SSSSSSSSSXXXX
      XXXXXX

      XXXXXXXXX XXXXXXXXX
      XXXX
        XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX
          XXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Cancel') 
        XXXXXXXXX
        XX
          XXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX
          XXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
           gettext(u'Yes') 
        XXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
