BBBB BBBB
XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXX XXXXXXX XXXXXXX XXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX
            XXX
                    XXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            X
                XXXXXXX XX XXX XXXXXX XXXX XXXXXX
            XXXXX

            XX XXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXXXX
                XXXXXX XXXXX XXXXXX
            XXXX
        XXXXXX
    XXXXXX
XXXXXXXXXX