XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXX XXXX X X XX X X XXXXXXXXXXXXXXXXXXXX XXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XX X
            XXXXX XXXXXX X XXXXXXXXXXXXXXXX
            XXXXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXX X XXXXXXXXXXXXXXX X XXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXX XXXXXX XXX XXXX  XXXXXXXXXXXX XXX XXX XXXXX XX XXXXX XXXXXXXXXXX
        XXX
    X
XXXXXXXXX