from .components.main import Main
from .components.segment.attribute import Attribute
from .components.segment.attributes import Attributes
from .components.segment.selector import Selector
from .components.segment.save import Save
from .components.segment.segment import Segment
from .components.overview.overview import Overview
from .components.export.export import Export
from .components.tabs.tab import WidgetTab
