
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-15T17:20:43+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "60dfad96ac2be0ff537f3381656c9218fb2776e1",
 "version": "2022.12.15.post3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
