
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "288b0f6e04d649a74d9e0de888c6d89678abbc08",
 "version": "2.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
