VERSION_YEAR = 2023
VERSION_MONTH = int('05')
VERSION_DAY = int('15')
VERSION_HOUR = int('08')
VERSION_MINUTE = int('18')
MAJOR_VERSION = 0
MINOR_VERSION = 30
PATCH_VERSION = 202305150818
version_date = '2023/05/15 08:18'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
