# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/rillingcards',
                'doc_host': 'https://josephrilling.github.io',
                'git_url': 'https://github.com/josephrilling/rillingcards',
                'lib_path': 'rillingcards'},
  'syms': { 'rillingcards.card': { 'rillingcards.card.Card': ('card.html#card', 'rillingcards/card.py'),
                                   'rillingcards.card.Card.__init__': ('card.html#card.__init__', 'rillingcards/card.py'),
                                   'rillingcards.card.Card.__str__': ('card.html#card.__str__', 'rillingcards/card.py')},
            'rillingcards.deck': { 'rillingcards.deck.Deck': ('deck.html#deck', 'rillingcards/deck.py'),
                                   'rillingcards.deck.Deck.__init__': ('deck.html#deck.__init__', 'rillingcards/deck.py'),
                                   'rillingcards.deck.Deck.__str__': ('deck.html#deck.__str__', 'rillingcards/deck.py')}}}
