# Magyar nevek listái

vezeteknev = ['Kovács', 'Nagy', 'Kiss', 'Tóth', 'Varga', 'Farkas', 'Horváth', 'Szabó', 'Molnár', 'Balázs',
              'Lakatos', 'Takács', 'Papp', 'Katona', 'Szilágyi', 'Balogh', 'Gulyás', 'Szőke', 'Simon', 'Fehér',
              'Barta', 'Császár', 'Sándor', 'Fodor', 'Bakos', 'László', 'Kerekes', 'Fekete', 'Török', 'Pintér',
              'Juhász', 'Gáspár', 'Kis', 'Bognár', 'Hajdu', 'Kónya', 'Kozma', 'Borbély', 'Budai', 'Hegedűs',
              'Ács', 'Bálint', 'Rácz', 'Virág', 'Sipos', 'Kelemen', 'Gál', 'Szőllősi', 'Lengyel', 'Füredi',
              'Magyar', 'Fazekas', 'Antal', 'Bérczes', 'Temesvári', 'Oláh', 'Pál', 'Barna', 'Bajnai', 'Balog',
              'Kocsis', 'Halász', 'Kertész', 'Boros', 'Fekete', 'Bérczi', 'Vincze', 'Dudás', 'Mészáros',
              'Gombos', 'Árkosi', 'Pánczél', 'Karádi', 'Kulcsár', 'Ágoston', 'Pap', 'Pálinkás', 'Csák', 'Bódi',
              'Kerekes', 'Fischer', 'Győri', 'Magyar', 'Péter', 'Fenyő', 'Kocsis', 'Fazekas', 'Kis-Benedek',
              'Bán', 'Bánhidi', 'Kovácsik', 'Kincses', 'Iványi', 'Bertalan', 'Molnár', 'Papp', 'Benedek',
              'Huszár', 'Kis-Gál', 'Németh', 'Somogyi', 'Boda', 'Budai', 'Székely', 'Borsos', 'Czeglédi',
              'Árvai', 'Miklós', 'Füzesi', 'Pap', 'Kisfaludi', 'Pongrácz', 'Tóth', 'Budavári', 'Sajó',
              'Mészáros', 'Lévai', 'Kéri', 'Czakó', 'Csordás', 'Mészáros', 'Bodó', 'Kántor', 'Nagy-Balogh',
              'Szekeres', 'Takács', 'Jakab', 'Herczeg', 'Vajda', 'Gyuris', 'Kincs', 'Végh', 'Lukács', 'Erdélyi',
              'Simon', 'Bárdi', 'Szabó-Balog', 'Szubin']

keresztnev_n = ['Anna', 'Cecília', 'Erika', 'Hanna', 'Katalin', 'Mária', 'Nóra', 'Orsolya', 'Réka', 'Szilvia',
                'Tünde', 'Viktória', 'Dóra', 'Eszter', 'Flóra', 'Hajnalka', 'Izabella', 'Jázmin', 'Kamilla', 'Nikolett',
                'Panna', 'Rita', 'Sarolta', 'Zsófia', 'Ágota', 'Csilla', 'Lilla', 'Orsolya', 'Panna',
                'Szandra', 'Tamara', 'Ágnes', 'Júlia', 'Kincső', 'Babett', 'Barbara', 'Beáta', 'Bianka',
                'Blanka', 'Boglárka', 'Borbála', 'Boróka', 'Brigitta', 'Bernadett', 'Bettina', 'Berta', 'Betti',
                'Bianka', 'Cecília', 'Cintia', 'Csenge', 'Csilla', 'Detti', 'Diana', 'Dóra', 'Dalma', 'Daniella',
                'Debóra', 'Dolli', 'Dominika']

keresztnev_f = ['Ábel', 'Ádám', 'Ákos', 'Aladár', 'Albert', 'Albin', 'Alekszander', 'Alfréd', 'Ambrus', 'Andor',
                'András', 'Áron', 'Árpád', 'Attila', 'Aurél', 'Bálint', 'Barna', 'Barnabás', 'Béla', 'Benedek',
                'Benjámin', 'Bernát', 'Botond', 'Csongor', 'Dénes', 'Dániel', 'Dávid', 'Dezső', 'Dominik', 'Donát',
                'Edgár', 'Edmund', 'Ede', 'Eduárd', 'Endre', 'Erik', 'Ernő', 'Fábián', 'Farkas', 'Ferenc', 'Flórián',
                'Gábor', 'Géza', 'Gergely', 'Gusztáv', 'György', 'Győző', 'Hunor', 'Igor', 'Imre', 'István', 'János',
                'József', 'Kálmán', 'Károly', 'Kázmér', 'Kelemen', 'Kende', 'Kornél', 'Kristóf',
                'Lajos', 'László', 'Levente', 'Lóránt', 'Lóránd', 'Lukács', 'Márió', 'Márk', 'Márton', 'Mátyás',
                'Miklós', 'Milán', 'Mózes', 'Nándor', 'Nikolasz', 'Noé', 'Norbert', 'Olivér', 'Ödön', 'Oszkár',
                'Ottó', 'Pál', 'Patrik', 'Péter', 'Róbert', 'Rudolf', 'Sámuel', 'Sándor', 'Sebestyén', 'Soma',
                'Szabolcs', 'Szilárd', 'Szilveszter', 'Tamás', 'Tihamér', 'Tibor', 'Tivadar', 'Tódor', 'Tóbiás',
                'Vencel', 'Viktor', 'Vilmos', 'Vince', 'Zalán', 'Zétény', 'Zoltán', 'Zsigmond', 'Zsolt']

keresztnev_v =['Ábel', 'Ádám', 'Ákos', 'Aladár', 'Albert', 'Albin', 'Alekszander', 'Alfréd', 'Ambrus', 'Andor',
                'András', 'Áron', 'Árpád', 'Attila', 'Aurél', 'Bálint', 'Barna', 'Barnabás', 'Béla', 'Benedek',
                'Benjámin', 'Bernát', 'Botond', 'Csongor', 'Dénes', 'Dániel', 'Dávid', 'Dezső', 'Dominik', 'Donát',
                'Edgár', 'Edmund', 'Ede', 'Eduárd', 'Endre', 'Erik', 'Ernő', 'Fábián', 'Farkas', 'Ferenc', 'Flórián',
                'Gábor', 'Géza', 'Gergely', 'Gusztáv', 'György', 'Győző', 'Hunor', 'Igor', 'Imre', 'István', 'János',
                'József', 'Kálmán', 'Károly', 'Kázmér', 'Kelemen', 'Kende', 'Kornél', 'Kristóf',
                'Lajos', 'László', 'Levente', 'Lóránt', 'Lóránd', 'Lukács', 'Márió', 'Márk', 'Márton', 'Mátyás',
                'Miklós', 'Milán', 'Mózes', 'Nándor', 'Nikolasz', 'Noé', 'Norbert', 'Olivér', 'Ödön', 'Oszkár',
                'Ottó', 'Pál', 'Patrik', 'Péter', 'Róbert', 'Rudolf', 'Sámuel', 'Sándor', 'Sebestyén', 'Soma',
                'Szabolcs', 'Szilárd', 'Szilveszter', 'Tamás', 'Tihamér', 'Tibor', 'Tivadar', 'Tódor', 'Tóbiás',
                'Vencel', 'Viktor', 'Vilmos', 'Vince', 'Zalán', 'Zétény', 'Zoltán', 'Zsigmond', 'Zsolt',
               'Anna', 'Cecília', 'Erika', 'Hanna', 'Katalin', 'Mária', 'Nóra', 'Orsolya', 'Réka', 'Szilvia',
               'Tünde', 'Viktória', 'Dóra', 'Eszter', 'Flóra', 'Hajnalka', 'Izabella', 'Jázmin', 'Kamilla', 'Nikolett',
               'Panna', 'Rita', 'Sarolta', 'Zsófia', 'Ágota', 'Csilla', 'Lilla', 'Orsolya', 'Panna',
               'Szandra', 'Tamara', 'Ágnes', 'Júlia', 'Kincső', 'Babett', 'Barbara', 'Beáta', 'Bianka',
               'Blanka', 'Boglárka', 'Borbála', 'Boróka', 'Brigitta', 'Bernadett', 'Bettina', 'Berta', 'Betti',
               'Bianka', 'Cecília', 'Cintia', 'Csenge', 'Csilla', 'Detti', 'Diana', 'Dóra', 'Dalma', 'Daniella',
               'Debóra', 'Dolli', 'Dominika'
               ]

utca = ['Ady Endre utca', 'Akácfa utca', 'Alkotmány utca', 'Almássy tér', 'Andrássy út', 'Apáczai Csere János utca',
        'Aradi utca', 'Árpád fejedelem útja', 'Attila utca', 'Bajcsy-Zsilinszky út', 'Balassi Bálint utca',
        'Baross utca', 'Bartók Béla út', 'Batthyány tér', 'Bécsi utca', 'Belgrád rakpart', 'Bethlen Gábor tér',
        'Béke tér', 'Bem rakpart', 'Benczúr utca', 'Bérkocsis utca', 'Berzsenyi utca', 'Bihari utca', 'Bocskai utca',
        'Budaörsi út', 'Csarnok tér', 'Csévi utca', 'Csillaghegyi út', 'Csokonai utca', 'Csömöri utca', 'Dandár utca',
        'Darázs utca', 'Deák Ferenc utca', 'Dózsa György út', 'Egyetem tér', 'Erzsébet körút', 'Erzsébet tér',
        'Fadrusz utca', 'Fehérvári út', 'Kőrösi Csoma Sándor út', 'Ferenciek tere', 'Ferenc körút', 'Ferenc tér',
        'Feszty Árpád utca', 'Fő utca', 'Frankel Leó utca', 'Gát utca', 'Gönczy Pál utca', 'Gyömrői út',
        'Gyulai Pál utca', 'Hajós utca', 'Haller utca', 'Hársfa utca', 'Hattyú utca', 'Hegedűs Gyula utca',
        'Hegyalja út', 'Heltai Jenő utca', 'Hercegprímás utca', 'Hidegkúti út', 'Hűvösvölgyi út', 'Jókai utca',
        'József Attila utca', 'Kálmán Imre utca', 'Kálvin tér', 'Károly körút', 'Kassák Lajos utca',
        'Katona József utca', 'Káva utca', 'Kazinczy utca', 'Király utca',  'Klauzál tér', 'Klauzál utca',
        'Köztársaság tér', 'Kőbányai út', 'Közraktár utca', 'Klapka György út', 'Mártirok útja'
        'Krisztina körút', 'Kun utca', 'Váci út', 'Lajos utca', 'Lánchíd utca', 'Üllői út']

telepules = ['Aba', 'Abaliget', 'Abasár', 'Abaújalpár', 'Abaújkér', 'Abaújlak', 'Abaújszántó', 'Abaújszolnok',
             'Abaújvár', 'Abádszalók', 'Abda', 'Abod', 'Abony', 'Acsa', 'Acsalag', 'Acsád', 'Adács', 'Adásztevel',
             'Adony', 'Adorjánháza', 'Adorjás', 'Aggtelek', 'Agyagosszergény', 'Ajak', 'Ajka', 'Aka', 'Akasztó',
             'Alacska', 'Alap', 'Alattyán', 'Albertirsa', 'Alcsútdoboz', 'Aldebrő', 'Algyő', 'Alibánfa', 'Almamellék',
             'Almásfüzitő', 'Almásháza', 'Almáskamarás', 'Almáskeresztúr', 'Alsóberecki', 'Alsóbogát', 'Alsódobsza',
             'Alsógagy', 'Alsómocsolád', 'Alsónána', 'Alsónemesapáti', 'Alsónémedi', 'Alsónyék', 'Alsóörs', 'Alsópáhok',
             'Alsópetény', 'Alsórajk', 'Alsóregmec', 'Alsószenterzsébet', 'Alsószentiván', 'Alsószentmárton', 'Alsószölnök',
             'Alsószuha', 'Alsótelekes', 'Alsótold', 'Alsóújlak', 'Alsóvadász', 'Alsózsolca', 'Ambrózfalva', 'Anarcs',
             'Andocs', 'Andornaktálya', 'Andrásfa', 'Annavölgy', 'Apagy', 'Apaj', 'Aparhant', 'Apácatorna', 'Apátfalva',
             'Apátistvánfalva', 'Apátvarasd', 'Apc', 'Apostag', 'Aranyosapáti', 'Aranyosgadány', 'Arka', 'Arló',
             'Arnót', 'Aszaló', 'Aszód', 'Aszófő', 'Atkár', 'Attala', 'Ábrahámhegy', 'Ács', 'Ácsteszér', 'Ádánd', 'Ág',
             'Ágasegyháza', 'Ágfalva', 'Álmosd', 'Áporka', 'Ároktő', 'Árpádhalom', 'Árpás', 'Ártánd', 'Ásotthalom',
             'Ásványráró', 'Ászár', 'Áta', 'Átány', 'Babarc', 'Babarcszőlős', 'Babosdöbréte', 'Babócsa', 'Babót',
             'Badacsonytomaj', 'Badacsonytördemic', 'Bag', 'Bagamér', 'Baglad', 'Bagod', 'Baj', 'Baja', 'Bajánsenye',
             'Bajna', 'Bajót', 'Bak', 'Bakháza', 'Bakonszeg', 'Bakonya', 'Bakonybánk', 'Bakonybél', 'Bakonycsernye',
             'Bakonygyirót', 'Bakonyjákó', 'Bakonykoppány', 'Bakonykúti', 'Bakonynána', 'Bakonyoszlop', 'Bakonypéterd',
             'Bakonypölöske', 'Bakonyság', 'Bakonysárkány', 'Bakonyszentiván', 'Bakonyszentkirály', 'Bakonyszentlászló',
             'Bakonyszombathely', 'Bakonyszücs', 'Bakonytamási', 'Bakóca', 'Baks', 'Baksa', 'Baktakék',
             'Baktalórántháza', 'Baktüttös', 'Balajt', 'Balassagyarmat', 'Balaton', 'Balatonakali', 'Balatonalmádi',
             'Balatonberény', 'Balatonboglár', 'Balatoncsicsó', 'Balatonederics', 'Balatonendréd', 'Balatonfenyves',
             'Balatonföldvár', 'Balatonfőkajár', 'Balatonfüred', 'Balatonfűzfő', 'Balatongyörök', 'Balatonhenye',
             'Balatonkenese', 'Balatonkeresztúr', 'Balatonlelle', 'Balatonmagyaród', 'Balatonmáriafürdő',
             'Balatonőszöd', 'Balatonrendes', 'Balatonszabadi', 'Balatonszárszó', 'Balatonszemes',
             'Balatonszentgyörgy', 'Balatonszepezd', 'Balatonszőlős', 'Balatonudvari', 'Balatonújlak', 'Balatonvilágos',
             'Balástya', 'Balinka', 'Balkány', 'Ballószög', 'Balmazújváros', 'Balogunyom', 'Balotaszállás', 'Balsa',
             'Bana', 'Barabás', 'Baracs', 'Baracska', 'Baranyahidvég', 'Baranyajenő', 'Baranyaszentgyörgy', 'Barbacs',
             'Barcs', 'Barlahida', 'Barnag', 'Basal', 'Baskó', 'Baté', 'Battonya', 'Batyk', 'Bazsi', 'Bábolna',
             'Bábonymegyer', 'Bácsalmás', 'Bácsbokod', 'Bácsborsód', 'Bácsszentgyörgy', 'Bácsszőlős', 'Bágyogszovát',
             'Bálványos', 'Bánd', 'Bánfa', 'Bánhorváti', 'Bánk', 'Bánokszentgyörgy', 'Bánréve', 'Bár', 'Báránd',
             'Bárdudvarnok', 'Bárna', 'Bársonyos', 'Báta', 'Bátaapáti', 'Bátaszék', 'Bátmonostor', 'Bátonyterenye',
             'Bátor', 'Bátorliget', 'Bátya', 'Bázakerettye', 'Becsehely', 'Becske', 'Becskeháza', 'Becsvölgye', 'Bedegkér',
             'Bedő', 'Bejcgyertyános', 'Bekecs', 'Bekölce', 'Belecska', 'Beled', 'Beleg', 'Belezna', 'Beloiannisz',
             'Belsősárd', 'Belvárdgyula', 'Benk', 'Bercel', 'Beregdaróc', 'Beregsurány', 'Berekböszörmény', 'Berekfürdő',
             'Beremend', 'Berente', 'Beret', 'Berettyóújfalu', 'Berhida', 'Berkenye', 'Berkesd', 'Berkesz', 'Bernecebaráti',
             'Berzence', 'Berzék', 'Besence', 'Besenyőd', 'Besenyőtelek', 'Besenyszög', 'Besnyő', 'Beszterec',
             'Bezedek', 'Bezenye', 'Bezeréd', 'Bezi', 'Béb', 'Békás', 'Békés', 'Békéscsaba', 'Békéssámson',
             'Békésszentandrás', 'Bélapátfalva', 'Bélavár', 'Bélmegyer', 'Bénye', 'Bér', 'Bérbaltavár', 'Biatorbágy',
             'Bicsérd', 'Bicske', 'Bihardancsháza', 'Biharkeresztes', 'Biharnagybajom', 'Bihartorda', 'Biharugra',
             'Bikal', 'Bikács', 'Biri', 'Birján', 'Bisse', 'Boba', 'Bocfölde', 'Boconád', 'Bocska', 'Bocskaikert',
             'Boda', 'Bodajk', 'Bodmér', 'Bodolyabér', 'Bodonhely', 'Bodony', 'Bodorfa', 'Bodrog', 'Bodroghalom',
             'Bodrogkeresztúr', 'Bodrogkisfalud', 'Bodrogolaszi', 'Bogács', 'Bogád', 'Bogádmindszent', 'Bogdása',
             'Bogyiszló', 'Bogyoszló', 'Bojt', 'Bokod', 'Bokor', 'Boldog', 'Boldogasszonyfa', 'Boldogkőújfalu',
             'Boldogkőváralja', 'Boldva', 'Bolhás', 'Bolhó', 'Boncodfölde', 'Bonnya', 'Bonyhád', 'Bonyhádvarasd',
             'Bordány', 'Borgáta', 'Borjád', 'Borota', 'Borsfa', 'Borsodbóta', 'Borsodgeszt', 'Borsodivánka',
             'Borsodnádasd', 'Borsodszentgyörgy', 'Borsodszirák', 'Borsosberény', 'Borszörcsök', 'Borzavár', 'Bosta',
             'Botpalád', 'Botykapeterd', 'Bozsok', 'Bozzai', 'Bócsa', 'Bódvalenke', 'Bódvarákó', 'Bódvaszilas',
             'Bókaháza', 'Bóly', 'Bózsva', 'Böde', 'Bödeháza', 'Bögöt', 'Bögöte', 'Böhönye', 'Bököny', 'Bölcske',
             'Börcs', 'Börzönce', 'Bő', 'Bőcs', 'Bőny', 'Bősárkány', 'Bőszénfa', 'Bucsa', 'Bucsu', 'Bucsuszentlászló',
             'Bucsuta', 'Budajenő', 'Budakalász', 'Budakeszi', 'Budaörs', 'Budapest', 'Bugac', 'Bugacpusztaháza',
             'Bugyi', 'Buj', 'Buják', 'Buzsák', 'Bük', 'Bükkaranyos', 'Bükkábrány', 'Bükkmogyorósd', 'Bükkösd',
             'Bükkszenterzsébet', 'Bükkszentkereszt', 'Bükkszentmárton', 'Bükkszék', 'Bükkzsérc', 'Bürüs', 'Büssü',
             'Büttös', 'Cakóháza', 'Cák', 'Cece', 'Cegléd', 'Ceglédbercel', 'Celldömölk', 'Cered', 'Cégénydányád',
             'Chernelházadamonya', 'Cibakháza', 'Cigánd', 'Cikó', 'Cirák', 'Csabacsűd', 'Csabaszabadi', 'Csabdi',
             'Csabrendek', 'Csaholc', 'Csajág', 'Csanádalberti', 'Csanádapáca', 'Csanádpalota', 'Csanytelek', 'Csapi',
             'Csapod', 'Csarnóta', 'Csaroda', 'Csataszög', 'Csatár', 'Csatka', 'Csáfordjánosfa', 'Csákány',
             'Csákánydoroszló', 'Csákberény', 'Csákvár', 'Csánig', 'Csány', 'Csányoszró', 'Csárdaszállás', 'Császár',
             'Császártöltés', 'Császló', 'Csátalja', 'Csávoly', 'Csebény', 'Csegöld', 'Csehbánya', 'Csehi',
             'Csehimindszent', 'Csemő', 'Csempeszkopács', 'Csengele', 'Csenger', 'Csengersima', 'Csengerújfalu',
             'Csengőd', 'Csenyéte', 'Csepreg', 'Cserdi', 'Cserénfa', 'Cserépfalu', 'Cserépváralja', 'Cserháthaláp',
             'Cserhátsurány', 'Cserhátszentiván', 'Cserkeszőlő', 'Cserkút', 'Csernely', 'Cserszegtomaj', 'Csertalakos',
             'Csertő', 'Csesznek', 'Csesztreg', 'Csesztve', 'Csetény', 'Csécse', 'Csém', 'Csénye', 'Csép', 'Csépa',
             'Csér', 'Csévharaszt', 'Csibrák', 'Csikéria', 'Csikóstőttős', 'Csikvánd', 'Csincse', 'Csipkerek', 'Csitár',
             'Csobaj', 'Csobád', 'Csobánka', 'Csokonyavisonta', 'Csokvaomány', 'Csolnok', 'Csoma', 'Csomád',
             'Csombárd', 'Csongrád', 'Csonkahegyhát', 'Csonkamindszent', 'Csopak', 'Csorna', 'Csorvás', 'Csókakő',
             'Csólyospálos', 'Csór', 'Csót', 'Csöde', 'Csögle', 'Csökmő', 'Csököly', 'Csömend', 'Csömödér', 'Csömör',
             'Csönge', 'Csörnyeföld', 'Csörög', 'Csörötnek', 'Csősz', 'Csővár', 'Csurgó', 'Csurgónagymarton', 'Cún',
             'Dabas', 'Dabronc', 'Dabrony', 'Dad', 'Dalmand', 'Damak', 'Daraboshegy', 'Darány', 'Darnó', 'Darnózseli',
             'Daruszentmiklós', 'Darvas', 'Dág', 'Dáka', 'Dámóc', 'Dánszentmiklós', 'Dány', 'Dávod', 'Debercsény',
             'Debrecen', 'Debréte', 'Decs', 'Dejtár', 'Demecser', 'Demjén', 'Dencsháza', 'Derecske', 'Derekegyház',
             'Deszk', 'Detek', 'Detk', 'Devecser', 'Dédestapolcsány', 'Dég', 'Délegyháza', 'Dénesfa', 'Dévaványa',
             'Dinnyeberki', 'Diósberény', 'Diósd', 'Diósjenő', 'Dióskál', 'Diósviszló', 'Doba', 'Doboz', 'Dobri',
             'Dobronhegy', 'Domaháza', 'Domaszék', 'Dombegyház', 'Dombiratos', 'Dombóvár', 'Dombrád', 'Domony',
             'Domoszló', 'Dormánd', 'Dorog', 'Dorogháza', 'Dozmat', 'Dóc', 'Döbörhegy', 'Döbröce', 'Döbrököz',
             'Döbrönte', 'Döge', 'Dömös', 'Dömsöd', 'Dör', 'Dörgicse', 'Döröske', 'Dötk', 'Dövény', 'Drágszél',
             'Drávacsehi', 'Drávacsepely', 'Drávafok', 'Drávagárdony', 'Drávaiványi', 'Drávakeresztúr', 'Drávapalkonya',
             'Drávapiski', 'Drávaszabolcs', 'Drávaszerdahely', 'Drávasztára', 'Drávatamási', 'Drégelypalánk', 'Dubicsány',
             'Dudar', 'Duka', 'Dunaalmás', 'Dunabogdány', 'Dunaegyháza', 'Dunafalva', 'Dunaföldvár', 'Dunaharaszti',
             'Dunakeszi', 'Dunakiliti', 'Dunapataj', 'Dunaremete', 'Dunaszeg', 'Dunaszekcső', 'Dunaszentbenedek',
             'Dunaszentgyörgy', 'Dunaszentmiklós', 'Dunaszentpál', 'Dunasziget', 'Dunatetétlen', 'Dunaújváros',
             'Dunavarsány', 'Dunavecse', 'Dusnok', 'Dúzs', 'Ebergőc', 'Ebes', 'Ecseg', 'Ecsegfalva', 'Ecseny', 'Ecser',
             'Ecséd', 'Edde', 'Edelény', 'Edve', 'Eger', 'Egeralja', 'Egeraracsa', 'Egerág', 'Egerbakta', 'Egerbocs',
             'Egercsehi', 'Egerfarmos', 'Egerlövő', 'Egerszalók', 'Egerszólát', 'Egervár', 'Egervölgy', 'Egyed', 'Egyek',
             'Egyházasdengeleg', 'Egyházasfalu', 'Egyházasgerge', 'Egyházasharaszti', 'Egyházashetye', 'Egyházashollós',
             'Egyházaskesző', 'Egyházaskozár', 'Egyházasrádóc', 'Elek', 'Ellend', 'Előszállás', 'Emőd', 'Encs', 'Encsencs',
             'Endrefalva', 'Endrőc', 'Enese', 'Enying', 'Eperjes', 'Eperjeske', 'Eplény', 'Epöl', 'Ercsi', 'Erdőbénye',
             'Erdőhorváti', 'Erdőkertes', 'Erdőkövesd', 'Erdőkürt', 'Erdősmárok', 'Erdősmecske', 'Erdőtarcsa', 'Erdőtelek',
             'Erk', 'Erzsébet', 'Esztár', 'Eszteregnye', 'Esztergályhorváti', 'Esztergom', 'Ete', 'Etes', 'Etyek', 'Écs',
             'Égerszög', 'Érd', 'Érpatak', 'Érsekcsanád', 'Érsekhalma', 'Érsekvadkert', 'Értény', 'Fadd', 'Fajsz',
             'Fancsal', 'Farád', 'Farkasgyepű', 'Farkaslyuk', 'Farmos', 'Fazekasboda', 'Fábiánháza', 'Fábiánsebestyén',
             'Fácánkert', 'Fáj', 'Fedémes', 'Fegyvernek', 'Fehérgyarmat', 'Fehértó', 'Fehérvárcsurgó', 'Feked',
             'Feketeerdő', 'Felcsút', 'Feldebrő', 'Felgyő', 'Felpéc', 'Felsőberecki', 'Felsőcsatár', 'Felsődobsza',
             'Felsőegerszeg', 'Felsőgagy', 'Felsőjánosfa', 'Felsőkelecsény', 'Felsőlajos', 'Felsőmarác', 'Felsőmocsolád',
             'Felsőnána', 'Felsőnyárád', 'Felsőnyék', 'Felsőörs', 'Felsőpakony', 'Felsőpáhok', 'Felsőpetény',
             'Felsőrajk', 'Felsőregmec', 'Felsőszenterzsébet', 'Felsőszentiván', 'Felsőszentmárton', 'Felsőszölnök',
             'Felsőtárkány', 'Felsőtelekes', 'Felsőtold', 'Felsővadász', 'Felsőzsolca', 'Fenyőfő', 'Ferencszállás',
             'Fertőboz', 'Fertőd', 'Fertőendréd', 'Fertőhomok', 'Fertőrákos', 'Fertőszentmiklós', 'Fertőszéplak',
             'Fényeslitke', 'Fiad', 'Filkeháza', 'Fityeház', 'Foktő', 'Folyás', 'Fonó', 'Fony', 'Fonyód', 'Forráskút',
             'Forró', 'Fót', 'Földeák', 'Földes', 'Főnyed', 'Fulókércs', 'Furta', 'Füle', 'Fülesd', 'Fülöp', 'Fülöpháza',
             'Fülöpjakab', 'Fülöpszállás', 'Fülpösdaróc', 'Fürged', 'Füzesabony', 'Füzesgyarmat', 'Füzér',
             'Füzérkajata', 'Füzérkomlós', 'Füzérradvány', 'Füzvölgy', 'Gacsály', 'Gadács', 'Gadány', 'Gadna',
             'Gagyapáti', 'Gagybátor', 'Gagyvendégi', 'Galambok', 'Galgaguta', 'Galgagyörk', 'Galgahévíz', 'Galgamácsa',
             'Galvács', 'Gamás', 'Ganna', 'Gara', 'Garabonc', 'Garadna', 'Garáb', 'Garbolc', 'Garé', 'Gasztony',
             'Gáborján', 'Gáborjánháza', 'Gádoros', 'Gálosfa', 'Gánt', 'Gárdony', 'Gátér', 'Gávavencsellő', 'Gecse',
             'Gelej', 'Gelénes', 'Gellénháza', 'Gelse', 'Gelsesziget', 'Gemzse', 'Gencsapáti', 'Gerde', 'Gerendás',
             'Geresdlak', 'Gerényes', 'Gerjen', 'Gersekarát', 'Geszt', 'Gesztely', 'Geszteréd', 'Géberjén', 'Géderlak',
             'Gégény', 'Gérce', 'Gétye', 'Gic', 'Gige', 'Gilvánfa', 'Girincs', 'Golop', 'Gomba', 'Gombosszeg',
             'Gordisa', 'Gosztola', 'Gógánfa', 'Gór', 'Göd', 'Gödöllő', 'Gödre', 'Gölle', 'Gömörszőlős', 'Gönc',
             'Göncruszka', 'Gönyű', 'Görbeháza', 'Görcsöny', 'Görcsönydoboka', 'Görgeteg', 'Gősfa', 'Grábóc', 'Gulács',
             'Gutorfölde', 'Gyalóka', 'Gyanógeregye', 'Gyarmat', 'Gyál', 'Gyenesdiás', 'Gyepükaján', 'Gyermely',
             'Gyékényes', 'Gyomaendrőd', 'Gyód', 'Gyóró', 'Gyömöre', 'Gyömrő', 'Gyöngyfa', 'Gyöngyös', 'Gyöngyösfalu',
             'Gyöngyöshalász', 'Gyöngyösmellék', 'Gyöngyösoroszi', 'Gyöngyöspata', 'Gyöngyössolymos', 'Gyöngyöstarján',
             'Gyönk', 'Györe', 'Györgytarló', 'Györköny', 'Győr', 'Győrasszonyfa', 'Győrladamér', 'Győröcske',
             'Győrság', 'Győrsövényház', 'Győrszemere', 'Győrtelek', 'Győrújbarát', 'Győrújfalu', 'Győrvár',
             'Győrzámoly', 'Gyugy', 'Gyula', 'Gyulaháza', 'Gyulaj', 'Gyulakeszi', 'Gyúró', 'Gyügye', 'Gyüre',
             'Gyűrűs', 'Hagyárosbörönd', 'Hahót', 'Hajdúbagos', 'Hajdúböszörmény', 'Hajdúdorog', 'Hajdúhadház',
             'Hajdúnánás', 'Hajdúsámson', 'Hajdúszoboszló', 'Hajdúszovát', 'Hajmás', 'Hajmáskér', 'Hajós', 'Halastó',
             'Halászi', 'Halásztelek', 'Halimba', 'Halmaj', 'Halmajugra', 'Halogy', 'Hangács', 'Hangony', 'Hantos',
             'Harasztifalu', 'Harc', 'Harka', 'Harkakötöny', 'Harkány', 'Harsány', 'Harta', 'Hatvan', 'Hács',
             'Háromfa', 'Háromhuta', 'Hárskút', 'Hásságy', 'Hedrehely', 'Hegyesd', 'Hegyeshalom', 'Hegyfalu',
             'Hegyháthodász', 'Hegyhátmaróc', 'Hegyhátsál', 'Hegyhátszentjakab', 'Hegyhátszentmárton',
             'Hegyhátszentpéter', 'Hegykő', 'Hegymagas', 'Hegymeg', 'Hegyszentmárton', 'Hejce', 'Hejőbába',
             'Hejőkeresztúr', 'Hejőkürt', 'Hejőpapi', 'Hejőszalonta', 'Helesfa', 'Helvécia', 'Hencida', 'Hencse',
             'Herceghalom', 'Hercegkút', 'Hercegszántó', 'Herencsény', 'Herend', 'Heresznye', 'Heréd', 'Hermánszeg',
             'Hernád', 'Hernádbűd', 'Hernádcéce', 'Hernádkak', 'Hernádkércs', 'Hernádnémeti', 'Hernádpetri',
             'Hernádszentandrás', 'Hernádszurdok', 'Hernádvécse', 'Hernyék', 'Hetefejércse', 'Hetes', 'Hetvehely',
             'Hetyefő', 'Heves', 'Hevesaranyos', 'Hevesvezekény', 'Hédervár', 'Héhalom', 'Héreg', 'Hét', 'Hévíz',
             'Hévízgyörk', 'Hidas', 'Hidasnémeti', 'Hidegkút', 'Hidegség', 'Hidvégardó', 'Himesháza', 'Himod', 'Hirics',
             'Hobol', 'Hodász', 'Hollád', 'Hollóháza', 'Hollókő', 'Homokbödöge', 'Homokkomárom', 'Homokmégy',
             'Homokszentgyörgy', 'Homorúd', 'Homrogd', 'Hont', 'Horpács', 'Hort', 'Hortobágy', 'Horváthertelend',
             'Horvátlövő', 'Horvátzsidány', 'Hosszúhetény', 'Hosszúpályi', 'Hosszúpereszteg', 'Hosszúvíz',
             'Hosszúvölgy', 'Hosztót', 'Hottó', 'Hódmezővásárhely', 'Hövej', 'Hőgyész', 'Hugyag', 'Hunya',
             'Hunyadfalva', 'Husztót', 'Ibafa', 'Iborfia', 'Ibrány', 'Igal', 'Igar', 'Igrici', 'Iharos', 'Iharosberény',
             'Ikervár', 'Iklad', 'Iklanberény', 'Iklódbördőce', 'Ikrény', 'Iliny', 'Ilk', 'Illocska', 'Imola',
             'Imrehegy', 'Ináncs', 'Inárcs', 'Inke', 'Ipacsfa', 'Ipolydamásd', 'Ipolytarnóc', 'Ipolytölgyes',
             'Ipolyvece', 'Iregszemcse', 'Irota', 'Isaszeg', 'Ispánk', 'Istenmezeje', 'Istvándi', 'Iszkaszentgyörgy',
             'Iszkáz', 'Isztimér', 'Ivád', 'Iván', 'Ivánbattyán', 'Ivánc', 'Iváncsa', 'Ivándárda', 'Izmény', 'Izsák',
             'Izsófalva', 'Jakabszállás', 'Jágónak', 'Ják', 'Jákfa', 'Jákfalva', 'Jákó', 'Jánd', 'Jánkmajtis',
             'Jánoshalma', 'Jánosháza', 'Jánoshida', 'Jánossomorja', 'Járdánháza', 'Jármi', 'Jásd', 'Jászalsószentgyörgy',
             'Jászapáti', 'Jászágó', 'Jászárokszállás', 'Jászberény', 'Jászboldogháza', 'Jászdózsa',
             'Jászfelsőszentgyörgy', 'Jászfényszaru', 'Jászivány', 'Jászjákóhalma', 'Jászkarajenő', 'Jászkisér',
             'Jászladány', 'Jászszentandrás', 'Jászszentlászló', 'Jásztelek', 'Jenő', 'Jéke', 'Jobaháza',
             'Jobbágyi', 'Jósvafő', 'Juta', 'Kaba', 'Kacorlak', 'Kacsóta', 'Kadarkút', 'Kajárpéc', 'Kajászó',
             'Kajdacs', 'Kakasd', 'Kakucs', 'Kalaznó', 'Kallósd', 'Kalocsa', 'Kamond', 'Kamut', 'Kapolcs',
             'Kapoly', 'Kaposfő', 'Kaposgyarmat', 'Kaposhomok', 'Kaposkeresztúr', 'Kaposmérő', 'Kapospula',
             'Kaposszekcső', 'Kaposszerdahely', 'Kaposújlak', 'Kaposvár', 'Kapuvár', 'Karakó', 'Karakószörcsök',
             'Karancsalja', 'Karancsberény', 'Karancskeszi', 'Karancslapujtő', 'Karancsság', 'Karácsond', 'Karád',
             'Karcag', 'Karcsa', 'Kardos', 'Kardoskút', 'Karmacs', 'Karos', 'Kartal', 'Kaskantyú', 'Kastélyosdombó',
             'Kaszaper', 'Kaszó', 'Katafa', 'Katádfa', 'Katymár', 'Kazár', 'Kazincbarcika', 'Kazsok', 'Kács', 'Kákics',
             'Kál', 'Káld', 'Kálló', 'Kállósemjén', 'Kálmáncsa', 'Kálmánháza', 'Káloz', 'Kálócfa', 'Kám', 'Kánó',
             'Kántorjánosi', 'Kány', 'Kánya', 'Kányavár', 'Kápolna', 'Kápolnásnyék', 'Káptalanfa', 'Káptalantóti',
             'Kára', 'Kárász', 'Károlyháza', 'Kásád', 'Kátoly', 'Káva', 'Kávás', 'Kázsmárk', 'Kecel', 'Kecskemét',
             'Kecskéd', 'Kehidakustány', 'Kelebia', 'Kelemér', 'Kelevíz', 'Keléd', 'Kemecse', 'Kemence', 'Kemendollár',
             'Kemeneshőgyész', 'Kemeneskápolna', 'Kemenesmagasi', 'Kemenesmihályfa', 'Kemenespálfa', 'Kemenessömjén',
             'Kemenesszentmárton', 'Kemenesszentpéter', 'Kemestaródfa', 'Keménfa', 'Kemse', 'Kenderes', 'Kenéz',
             'Kenézlő', 'Kengyel', 'Kenyeri', 'Kercaszomor', 'Kercseliget', 'Kerecsend', 'Kerecseny', 'Kerekegyháza',
             'Kereki', 'Kerepes', 'Keresztéte', 'Kerékteleki', 'Kerkabarabás', 'Kerkafalva', 'Kerkakutas',
             'Kerkaszentkirály', 'Kerkateskánd', 'Kerkáskápolna', 'Kerta', 'Kertészsziget', 'Keszeg', 'Kesznyéten',
             'Keszőhidegkút', 'Keszthely', 'Kesztölc', 'Keszü', 'Kevermes', 'Kék', 'Kékcse', 'Kéked', 'Kékesd',
             'Kékkút', 'Kéleshalom', 'Kémes', 'Kérsemjén', 'Kétbodony', 'Kétegyháza', 'Kéthely', 'Kétpó', 'Kétsoprony',
             'Kétújfalu', 'Kétvölgy', 'Kéty', 'Kilimán', 'Kimle', 'Kincsesbánya', 'Királd', 'Királyegyháza',
             'Királyhegyes', 'Királyszentistván', 'Kisapáti', 'Kisapostag', 'Kisar', 'Kisasszond', 'Kisasszonyfa',
             'Kisbabot', 'Kisbajcs', 'Kisbajom', 'Kisbágyon', 'Kisbárapáti', 'Kisbárkány', 'Kisberény', 'Kisberzseny',
             'Kisbeszterce', 'Kisbér', 'Kisbodak', 'Kisbucsa', 'Kisbudmér', 'Kiscsehi', 'Kiscsécs', 'Kiscsősz',
             'Kisdér', 'Kisdobsza', 'Kisdombegyház', 'Kisdorog', 'Kisecset', 'Kisfalud', 'Kisfüzes', 'Kisgörbő',
             'Kisgyalán', 'Kisgyőr', 'Kishajmás', 'Kisharsány', 'Kishartyán', 'Kisherend', 'Kishódos', 'Kishuta',
             'Kisigmánd', 'Kisjakabfalva', 'Kiskassa', 'Kiskinizs', 'Kiskorpád', 'Kisköre', 'Kiskőrös',
             'Kiskunfélegyháza', 'Kiskunhalas', 'Kiskunlacháza', 'Kiskunmajsa', 'Kiskutas', 'Kisláng', 'Kisléta',
             'Kislippó', 'Kislőd', 'Kismarja', 'Kismaros', 'Kismányok', 'Kisnamény', 'Kisnána', 'Kisnémedi', 'Kisnyárád',
             'Kisoroszi', 'Kispalád', 'Kispáli', 'Kispirit', 'Kisrákos', 'Kisrécse', 'Kisrozvágy', 'Kissikátor', 'Kissomlyó',
             'Kisszállás', 'Kisszekeres', 'Kisszentmárton', 'Kisszékely', 'Kissziget', 'Kisszőlős', 'Kistamási',
             'Kistapolca', 'Kistarcsa', 'Kistelek', 'Kistokaj', 'Kistolmács', 'Kistormás', 'Kistótfalu', 'Kisunyom',
             'Kisújszállás', 'Kisvarsány', 'Kisvaszar', 'Kisvárda', 'Kisvásárhely', 'Kisvejke', 'Kiszombor',
             'Kiszsidány', 'Klárafalva', 'Kocs', 'Kocsér', 'Kocsola', 'Kocsord', 'Kokad', 'Kolontár', 'Komádi', 'Komárom',
             'Komjáti', 'Komló', 'Komlódtótfalu', 'Komlósd', 'Komlóska', 'Komoró', 'Kompolt', 'Kondorfa', 'Kondoros',
             'Kondó', 'Konyár', 'Koppányszántó', 'Korlát', 'Koroncó', 'Kosd', 'Kovácshida', 'Kovácsszénája',
             'Kovácsvágás', 'Kozárd', 'Kozármisleny', 'Kozmadombja', 'Kóka', 'Kóny', 'Kópháza', 'Kórós', 'Kóspallag',
             'Kótaj', 'Köblény', 'Köcsk', 'Kökény', 'Kölcse', 'Kölesd', 'Kölked', 'Kömlő', 'Kömlőd', 'Kömörő',
             'Kömpöc', 'Körmend', 'Környe', 'Köröm', 'Körösladány', 'Körösnagyharsány', 'Körösszakál', 'Körösszegapáti',
             'Köröstarcsa', 'Körösújfalu', 'Kötcse', 'Kötegyán', 'Kövegy', 'Köveskál', 'Kőkút', 'Kőröshegy',
             'Kőröstetétlen', 'Kőszárhegy', 'Kőszeg', 'Kőszegdoroszló', 'Kőszegpaty', 'Kőszegszerdahely', 'Kőtelek',
             'Kővágóörs', 'Kővágószőlős', 'Kővágótőttős', 'Krasznokvajda', 'Kulcs', 'Kunadacs', 'Kunágota', 'Kunbaja',
             'Kunbaracs', 'Kuncsorba', 'Kunfehértó', 'Kunhegyes', 'Kunmadaras', 'Kunpeszér', 'Kunszállás', 'Kunszentmárton',
             'Kunszentmiklós', 'Kunsziget', 'Kup', 'Kupa', 'Kurd', 'Kurityán', 'Kustánszeg', 'Kutas', 'Kutasó',
             'Kübekháza', 'Külsősárd', 'Külsővat', 'Küngös', 'Lad', 'Ladánybene', 'Lajoskomárom', 'Lajosmizse', 'Lak',
             'Lakhegy', 'Lakitelek', 'Lakócsa', 'Lapáncsa', 'Laskod', 'Lasztonya', 'Lábatlan', 'Lábod', 'Lácacséke',
             'Ládbesenyő', 'Lánycsók', 'Lápafő', 'Látrány', 'Lázi', 'Leányfalu', 'Leányvár', 'Legénd', 'Legyesbénye',
             'Lendvadedes', 'Lendvajakabfa', 'Lengyel', 'Lengyeltóti', 'Lenti', 'Lepsény', 'Lesencefalu', 'Lesenceistvánd',
             'Lesencetomaj', 'Letenye', 'Letkés', 'Levelek', 'Levél', 'Lébény', 'Léh', 'Lénárddaróc', 'Létavértes',
             'Libickozma', 'Lickóvadamos', 'Liget', 'Ligetfalva', 'Lipót', 'Lippó', 'Liptód', 'Lispeszentadorján',
             'Liszó', 'Litér', 'Litka', 'Litke', 'Lothárd', 'Lovas', 'Lovasberény', 'Lovászhetény', 'Lovászi',
             'Lovászpatona', 'Lócs', 'Lókút', 'Lónya', 'Lórév', 'Lövő', 'Lövőpetri', 'Lőkösháza', 'Lőrinci', 'Lucfalva',
             'Ludas', 'Ludányhalászi', 'Lukácsháza', 'Lulla', 'Lúzsok', 'Madaras', 'Madocsa', 'Maglóca', 'Maglód',
             'Magosliget', 'Magy', 'Magyaralmás', 'Magyaratád', 'Magyarbánhegyes', 'Magyarbóly', 'Magyarcsanád',
             'Magyardombegyház', 'Magyaregregy', 'Magyaregres', 'Magyarföld', 'Magyargencs', 'Magyargéc',
             'Magyarhertelend', 'Magyarhomorog', 'Magyarkeresztúr', 'Magyarkeszi', 'Magyarlak', 'Magyarlukafa',
             'Magyarmecske', 'Magyarnádalja', 'Magyarnándor', 'Magyarpolány', 'Magyarsarlós', 'Magyarszecsőd',
             'Magyarszentmiklós', 'Magyarszerdahely', 'Magyarszék', 'Magyarszombatfa', 'Magyartelek', 'Majosháza',
             'Majs', 'Makád', 'Makkoshotyka', 'Maklár', 'Makó', 'Malomsok', 'Maráza', 'Marcalgergelyi', 'Marcali',
             'Marcaltő', 'Markaz', 'Markotabödöge', 'Markóc', 'Maroslele', 'Maróc', 'Marócsa', 'Martfű', 'Martonfa',
             'Martonvásár', 'Martonyi', 'Matty', 'Mád', 'Mágocs', 'Mályi', 'Mályinka', 'Mánd', 'Mándok', 'Mánfa',
             'Mány', 'Márfa', 'Máriahalom', 'Máriakálnok', 'Máriakéménd', 'Márianosztra', 'Máriapócs', 'Márkháza',
             'Márkó', 'Márok', 'Márokföld', 'Márokpapi', 'Mártély', 'Mátészalka', 'Mátételke', 'Mátraballa', 'Mátraderecske',
             'Mátramindszent', 'Mátranovák', 'Mátraszele', 'Mátraszentimre', 'Mátraszőlős', 'Mátraterenye',
             'Mátraverebély', 'Mátyásdomb', 'Mátyus', 'Máza', 'Mecseknádasd', 'Mecsekpölöske', 'Mecsér',
             'Medgyesbodzás', 'Medgyesegyháza', 'Medina', 'Meggyeskovácsi', 'Megyaszó', 'Megyehid', 'Megyer',
             'Mekényes', 'Mencshely', 'Mende', 'Merenye', 'Mernye', 'Mersevát', 'Mesterháza', 'Mesteri',
             'Mesterszállás', 'Meszes', 'Meszlen', 'Mesztegnyő', 'Mezőberény', 'Mezőcsát', 'Mezőcsokonya',
             'Meződ', 'Mezőfalva', 'Mezőgyán', 'Mezőhegyes', 'Mezőhék', 'Mezőkeresztes', 'Mezőkomárom',
             'Mezőkovácsháza', 'Mezőkövesd', 'Mezőladány', 'Mezőlak', 'Mezőnagymihály', 'Mezőnyárád', 'Mezőörs',
             'Mezőpeterd', 'Mezősas', 'Mezőszemere', 'Mezőszentgyörgy', 'Mezőszilas', 'Mezőtárkány', 'Mezőtúr',
             'Mezőzombor', 'Méhkerék', 'Méhtelek', 'Mélykút', 'Méra', 'Mérges', 'Mérk', 'Miháld', 'Mihályfa',
             'Mihálygerge', 'Mihályháza', 'Mihályi', 'Mike', 'Mikebuda', 'Mikekarácsonyfa', 'Mikepércs', 'Miklósi',
             'Mikosszéplak', 'Mikófalva', 'Mikóháza', 'Milejszeg', 'Milota', 'Mindszent', 'Mindszentgodisa',
             'Mindszentkálla', 'Misefa', 'Miske', 'Miskolc', 'Miszla', 'Mocsa', 'Mogyoród', 'Mogyorósbánya',
             'Mogyoróska', 'Moha', 'Mohács', 'Mohora', 'Molnaszecsőd', 'Molnári', 'Molvány', 'Monaj', 'Monok',
             'Monor', 'Monostorapáti', 'Monostorpályi', 'Monoszló', 'Monyoród', 'Mosdós', 'Mosonmagyaróvár',
             'Mosonszentmiklós', 'Mosonszolnok', 'Mozsgó', 'Mónosbél', 'Mór', 'Mórahalom', 'Mórágy', 'Móricgát',
             'Mórichida', 'Mőcsény', 'Mucsfa', 'Mucsi', 'Muhi', 'Murakeresztúr', 'Murarátka', 'Muraszemenye', 'Murga',
             'Murony', 'Múcsony', 'Nadap', 'Nagyacsád', 'Nagyalásony', 'Nagyar', 'Nagyatád', 'Nagybajcs', 'Nagybajom',
             'Nagybakónak', 'Nagybaracska', 'Nagybarca', 'Nagybánhegyes', 'Nagybárkány', 'Nagyberény', 'Nagyberki',
             'Nagybörzsöny', 'Nagybudmér', 'Nagycenk', 'Nagycsány', 'Nagycsepely', 'Nagycserkesz', 'Nagycsécs',
             'Nagydém', 'Nagydobos', 'Nagydobsza', 'Nagydorog', 'Nagyecsed', 'Nagyesztergár', 'Nagyér', 'Nagyfüged',
             'Nagygeresd', 'Nagygörbő', 'Nagygyimót', 'Nagyhajmás', 'Nagyhalász', 'Nagyharsány', 'Nagyhegyes', 'Nagyhódos',
             'Nagyhuta', 'Nagyigmánd', 'Nagyiván', 'Nagykamarás', 'Nagykanizsa', 'Nagykapornak', 'Nagykarácsony', 'Nagykálló',
             'Nagykáta', 'Nagykereki', 'Nagykeresztúr', 'Nagykinizs', 'Nagykorpád', 'Nagykovácsi', 'Nagykozár', 'Nagykónyi',
             'Nagykökényes', 'Nagykölked', 'Nagykörű', 'Nagykőrös', 'Nagykutas', 'Nagylak', 'Nagylengyel', 'Nagylóc',
             'Nagylók', 'Nagylózs', 'Nagymaros', 'Nagymágocs', 'Nagymányok', 'Nagymizdó', 'Nagynyárád', 'Nagyoroszi',
             'Nagypall', 'Nagypáli', 'Nagypeterd', 'Nagypirit', 'Nagyrada', 'Nagyrábé', 'Nagyrákos', 'Nagyrécse',
             'Nagyréde', 'Nagyrév', 'Nagyrozvágy', 'Nagysáp', 'Nagysimonyi', 'Nagyszakácsi', 'Nagyszekeres',
             'Nagyszentjános', 'Nagyszékely', 'Nagyszénás', 'Nagyszokoly', 'Nagytarcsa', 'Nagytálya', 'Nagytevel',
             'Nagytilaj', 'Nagytótfalu', 'Nagytőke', 'Nagyút', 'Nagyvarsány', 'Nagyváty', 'Nagyvázsony', 'Nagyvejke',
             'Nagyveleg', 'Nagyvenyim', 'Nagyvisnyó', 'Nak', 'Napkor', 'Narda', 'Naszály', 'Nábrád', 'Nádasd', 'Nádasdladány',
             'Nádudvar', 'Nágocs', 'Nárai', 'Nekézseny', 'Nemesapáti', 'Nemesbikk', 'Nemesborzova', 'Nemesbőd', 'Nemesbük',
             'Nemescsó', 'Nemesdéd', 'Nemesgörzsöny', 'Nemesgulács', 'Nemeshany', 'Nemeshetés', 'Nemeske', 'Nemeskeresztúr',
             'Nemeskér', 'Nemeskisfalud', 'Nemeskocs', 'Nemeskolta', 'Nemesládony', 'Nemesmedves', 'Nemesnádudvar',
             'Nemesnép', 'Nemespátró', 'Nemesrádó', 'Nemesrempehollós', 'Nemessándorháza', 'Nemesszalók',
             'Nemesszentandrás', 'Nemesvámos', 'Nemesvid', 'Nemesvita', 'Nemti', 'Neszmély', 'Négyes', 'Németbánya',
             'Németfalu', 'Németkér', 'Nézsa', 'Nick', 'Nikla', 'Noszlop', 'Noszvaj', 'Nova', 'Novaj', 'Novajidrány',
             'Nógrád', 'Nógrádkövesd', 'Nógrádmarcal', 'Nógrádmegyer', 'Nógrádsáp', 'Nógrádsipek', 'Nógrádszakál', 'Nóráp',
             'Nőtincs', 'Nyalka', 'Nyárád', 'Nyáregyháza', 'Nyárlőrinc', 'Nyársapát', 'Nyergesújfalu', 'Nyékládháza',
             'Nyésta', 'Nyim', 'Nyirád', 'Nyíracsád', 'Nyíradony', 'Nyírábrány', 'Nyírbátor', 'Nyírbéltek',
             'Nyírbogát', 'Nyírbogdány', 'Nyírcsaholy', 'Nyírcsászári', 'Nyírderzs', 'Nyíregyháza', 'Nyírgelse',
             'Nyírgyulaj', 'Nyíri', 'Nyíribrony', 'Nyírjákó', 'Nyírkarász', 'Nyírkáta', 'Nyírkércs', 'Nyírlövő',
             'Nyírlugos', 'Nyírmada', 'Nyírmártonfalva', 'Nyírmeggyes', 'Nyírmihálydi', 'Nyírparasznya', 'Nyírpazony',
             'Nyírpilis', 'Nyírtass', 'Nyírtelek', 'Nyírtét', 'Nyírtura', 'Nyírvasvári', 'Nyomár', 'Nyőgér', 'Nyugotszenterzsébet',
             'Nyúl', 'Okány', 'Okorág', 'Okorvölgy', 'Olasz', 'Olaszfa', 'Olaszfalu', 'Olaszliszka', 'Olcsva',
             'Olcsvaapáti', 'Old', 'Oltárc', 'Onga', 'Orbányosfa', 'Orci', 'Ordacsehi', 'Ordas', 'Orfalu', 'Orfű',
             'Orgovány', 'Ormándlak', 'Ormosbánya', 'Orosháza', 'Oroszi', 'Oroszlány', 'Oroszló', 'Orosztony',
             'Ortaháza', 'Osli', 'Ostffyasszonyfa', 'Ostoros', 'Oszkó', 'Oszlár', 'Osztopán', 'Ozmánbük', 'Ozora',
             'Óbarok', 'Óbánya', 'Óbudavár', 'Ócsa', 'Ócsárd', 'Ófalu', 'Ófehértó', 'Óföldeák', 'Óhid', 'Ólmod',
             'Ónod', 'Ópályi', 'Ópusztaszer', 'Ózd', 'Ózdfalu', 'Öcs', 'Öcsöd', 'Ököritófülpös', 'Ölbő', 'Ömböly',
             'Öregcsertő', 'Öreglak', 'Örkény', 'Örményes', 'Örménykút', 'Örvényes', 'Öskü', 'Öttevény', 'Öttömös',
             'Ötvöskónyi', 'Őcsény', 'Őr', 'Őrbottyán', 'Őrhalom', 'Őrimagyarósd', 'Őriszentpéter', 'Őrtilos',
             'Ősagárd', 'Ősi', 'Pacsa', 'Padár', 'Pakod', 'Paks', 'Palé', 'Palkonya', 'Palotabozsok', 'Palotás',
             'Paloznak', 'Pamlény', 'Pamuk', 'Pankasz', 'Pannonhalma', 'Panyola', 'Pap', 'Papkeszi', 'Papos',
             'Parasznya', 'Parád', 'Parádsasvár', 'Paszab', 'Pat', 'Patak', 'Patalom', 'Patapoklosi', 'Patca',
             'Patosfa', 'Patvarc', 'Pácin', 'Pácsony', 'Páhi', 'Páka', 'Pákozd', 'Pálfa', 'Pálfiszeg', 'Pálháza',
             'Páli', 'Pálmajor', 'Pálmonostora', 'Pánd', 'Pányok', 'Pápa', 'Pápadereske', 'Pápakovácsi', 'Pápasalamon',
             'Pápateszér', 'Pápoc', 'Páprád', 'Pásztori', 'Pásztó', 'Pátka', 'Pátroha', 'Páty', 'Pátyod', 'Pázmánd',
             'Pázmándfalu', 'Pecöl', 'Pellérd', 'Penc', 'Penészlek', 'Penyige', 'Perbál', 'Pere', 'Perecse', 'Pereked',
             'Perenye', 'Peresznye', 'Pereszteg', 'Perkáta', 'Perkupa', 'Perőcsény', 'Peterd', 'Pethőhenye',
             'Petneháza', 'Petőfibánya', 'Petőfiszállás', 'Petőháza', 'Petőmihályfa', 'Petrikeresztúr', 'Petrivente',
             'Pettend', 'Pécel', 'Pécs', 'Pécsbagota', 'Pécsdevecser', 'Pécsely', 'Pécsudvard', 'Pécsvárad', 'Pély',
             'Pénzesgyőr', 'Pér', 'Péterhida', 'Péteri', 'Pétervására', 'Pétfürdő', 'Piliny', 'Pilis',
             'Pilisborosjenő', 'Piliscsaba', 'Piliscsév', 'Pilisjászfalu', 'Pilismarót', 'Pilisszántó',
             'Pilisszentiván', 'Pilisszentkereszt', 'Pilisszentlászló', 'Pilisvörösvár', 'Pincehely', 'Pinkamindszent',
             'Pinnye', 'Piricse', 'Pirtó', 'Piskó', 'Pitvaros', 'Pocsaj', 'Pogány', 'Pogányszentpéter', 'Polány',
             'Polgár', 'Polgárdi', 'Pomáz', 'Porcsalma', 'Pornóapáti', 'Poroszló', 'Porpác', 'Porrog',
             'Porrogszentkirály', 'Porrogszentpál', 'Porva', 'Potony', 'Potyond', 'Pócsa', 'Pócsmegyer', 'Pócspetri',
             'Pókaszepetk', 'Pórszombat', 'Pósfa', 'Pölöske', 'Pölöskefő', 'Pörböly', 'Pördefölde', 'Pötréte',
             'Prügy', 'Pula', 'Pusztaapáti', 'Pusztaberki', 'Pusztacsalád', 'Pusztacsó', 'Pusztadobos', 'Pusztaederics',
             'Pusztafalu', 'Pusztaföldvár', 'Pusztahencse', 'Pusztakovácsi', 'Pusztamagyaród', 'Pusztamérges',
             'Pusztamiske', 'Pusztamonostor', 'Pusztaottlaka', 'Pusztaradvány', 'Pusztaszabolcs', 'Pusztaszemes',
             'Pusztaszentlászló', 'Pusztaszer', 'Pusztavacs', 'Pusztavám', 'Pusztazámor', 'Putnok', 'Püski',
             'Püspökhatvan', 'Püspökladány', 'Püspökmolnári', 'Püspökszilágy', 'Radostyán', 'Ragály', 'Rajka',
             'Rakaca', 'Rakacaszend', 'Rakamaz', 'Ramocsa', 'Ramocsaháza', 'Raposka', 'Ravazd', 'Rábacsanak',
             'Rábacsécsény', 'Rábagyarmat', 'Rábahidvég', 'Rábakecöl', 'Rábapatona', 'Rábapaty', 'Rábapordány',
             'Rábasebes', 'Rábaszentandrás', 'Rábaszentmihály', 'Rábaszentmiklós', 'Rábatamási', 'Rábatöttös',
             'Rábcakapi', 'Rácalmás', 'Ráckeresztúr', 'Ráckeve', 'Rád', 'Rádfalva', 'Rádóckölked', 'Rákóczibánya',
             'Rákóczifalva', 'Rákócziújfalu', 'Ráksi', 'Rápolt', 'Rásonysápberencs', 'Rátka', 'Rátót', 'Recsk',
             'Regenye', 'Regéc', 'Regöly', 'Remeteszőlős', 'Resznek', 'Rezi', 'Réde', 'Rédics', 'Rém', 'Répáshuta',
             'Répcelak', 'Répceszemere', 'Répceszentgyörgy', 'Répcevis', 'Rétalap', 'Rétközberencs', 'Rétság',
             'Révfülöp', 'Révleányvár', 'Ricse', 'Rigács', 'Rigyác', 'Rimóc', 'Rinyabesenyő', 'Rinyakovácsi',
             'Rinyaszentkirály', 'Rinyaújlak', 'Rinyaújnép', 'Rohod', 'Románd', 'Romhány', 'Romonya', 'Rozsály',
             'Rózsafa', 'Rózsaszentmárton', 'Röjtökmuzsaj', 'Rönök', 'Röszke', 'Rudabánya', 'Rudolftelep', 'Rum',
             'Ruzsa', 'Sajóbábony', 'Sajóecseg', 'Sajógalgóc', 'Sajóhidvég', 'Sajóivánka', 'Sajókaza', 'Sajókápolna',
             'Sajókeresztúr', 'Sajólád', 'Sajólászlófalva', 'Sajómercse', 'Sajónémeti', 'Sajóörös', 'Sajópálfala',
             'Sajópetri', 'Sajópüspöki', 'Sajósenye', 'Sajószentpéter', 'Sajószöged', 'Sajóvámos', 'Sajóvelezd',
             'Sajtoskál', 'Salföld', 'Salgótarján', 'Salköveskút', 'Salomvár', 'Sand', 'Sarkad', 'Sarkadkeresztúr',
             'Sarród', 'Sarud', 'Ságújfalu', 'Ságvár', 'Sály', 'Sámod', 'Sámsonháza', 'Sándorfalva', 'Sántos', 'Sáp',
             'Sárazsadány', 'Sáránd', 'Sárbogárd', 'Sáregres', 'Sárfimizdó', 'Sárhida', 'Sárisáp', 'Sárkeresztes',
             'Sárkeresztúr', 'Sárkeszi', 'Sármellék', 'Sárok', 'Sárosd', 'Sárospatak', 'Sárpilis', 'Sárrétudvari',
             'Sárszentágota', 'Sárszentlőrinc', 'Sárszentmihály', 'Sárvár', 'Sásd', 'Sáska', 'Sáta', 'Sátoraljaújhely',
             'Sátorhely', 'Sávoly', 'Segesd', 'Sellye', 'Selyeb', 'Semjén', 'Semjénháza', 'Seregélyes', 'Serényfalva',
             'Sé', 'Sénye', 'Sényő', 'Sérsekszőlős', 'Sikátor', 'Siklós', 'Siklósbodony', 'Siklósnagyfalu', 'Sima',
             'Simaság', 'Simonfa', 'Simontornya', 'Sióagárd', 'Siófok', 'Siójut', 'Sirok', 'Sitke', 'Sobor', 'Sokorópátka',
             'Solt', 'Soltszentimre', 'Soltvadkert', 'Solymár', 'Som', 'Somberek', 'Somlójenő', 'Somlószőlős',
             'Somlóvásárhely', 'Somlóvecse', 'Somodor', 'Somogyacsa', 'Somogyapáti', 'Somogyaracs', 'Somogyaszaló',
             'Somogybabod', 'Somogybükkösd', 'Somogycsicsó', 'Somogydöröcske', 'Somogyegres', 'Somogyfajsz', 'Somogygeszti',
             'Somogyhatvan', 'Somogyhárságy', 'Somogyjád', 'Somogymeggyes', 'Somogysámson', 'Somogysárd', 'Somogysimonyi',
             'Somogyszentpál', 'Somogyszil', 'Somogyszob', 'Somogytúr', 'Somogyudvarhely', 'Somogyvámos', 'Somogyvár',
             'Somogyviszló', 'Somogyzsitfa', 'Sonkád', 'Soponya', 'Sopron', 'Sopronhorpács', 'Sopronkövesd',
             'Sopronnémeti', 'Sorkifalud', 'Sorkikápolna', 'Sormás', 'Sorokpolány', 'Sóly', 'Sóshartyán', 'Sóskút',
             'Sóstófalva', 'Sósvertike', 'Sótony', 'Söjtör', 'Söpte', 'Söréd', 'Sukoró', 'Sumony', 'Surd', 'Súr',
             'Sükösd', 'Sülysáp', 'Sümeg', 'Sümegcsehi', 'Sümegprága', 'Süttő', 'Szabadbattyán', 'Szabadegyháza',
             'Szabadhidvég', 'Szabadi', 'Szabadkígyós', 'Szabadszállás', 'Szabadszentkirály', 'Szabás', 'Szabolcs',
             'Szabolcsbáka', 'Szabolcsveresmart', 'Szada', 'Szajk', 'Szajla', 'Szajol', 'Szakadát', 'Szakácsi', 'Szakáld',
             'Szakály', 'Szakcs', 'Szakmár', 'Szaknyér', 'Szakoly', 'Szakony', 'Szakonyfalu', 'Szalafő', 'Szalapa',
             'Szalaszend', 'Szalatnak', 'Szalánta', 'Szalkszentmárton', 'Szalmatercs', 'Szalonna', 'Szamosangyalos',
             'Szamosbecs', 'Szamoskér', 'Szamossályi', 'Szamosszeg', 'Szamostatárfalva', 'Szamosújlak', 'Szanda',
             'Szank', 'Szany', 'Szaporca', 'Szarvas', 'Szarvasgede', 'Szarvaskend', 'Szarvaskő', 'Szatmárcseke',
             'Szatta', 'Szatymaz', 'Szava', 'Szágy', 'Szákszend', 'Szálka', 'Szántód', 'Szápár', 'Szár', 'Szárazd',
             'Szárász', 'Szárföld', 'Szárliget', 'Szászberek', 'Szászfa', 'Szászvár', 'Szátok', 'Százhalombatta',
             'Szebény', 'Szederkény', 'Szedres', 'Szeged', 'Szegerdő', 'Szeghalom', 'Szegi', 'Szegilong', 'Szegvár',
             'Szekszárd', 'Szeleste', 'Szelevény', 'Szellő', 'Szemely', 'Szemenye', 'Szemere', 'Szendehely', 'Szendrő',
             'Szendrőlád', 'Szenna', 'Szenta', 'Szentantalfa', 'Szentbalázs', 'Szentbékkálla', 'Szentborbás', 'Szentdénes',
             'Szentdomonkos', 'Szente', 'Szentegát', 'Szentendre', 'Szentes', 'Szentgál', 'Szentgáloskér',
             'Szentgotthárd', 'Szentgyörgyvár', 'Szentgyörgyvölgy', 'Szentimrefalva', 'Szentistván', 'Szentistvánbaksa',
             'Szentjakabfa', 'Szentkatalin', 'Szentkirály', 'Szentkirályszabadja', 'Szentkozmadombja', 'Szentlászló',
             'Szentliszló', 'Szentlőrinc', 'Szentlőrinckáta', 'Szentmargitfalva', 'Szentmártonkáta', 'Szentpéterfa',
             'Szentpéterfölde', 'Szentpéterszeg', 'Szentpéterúr', 'Szenyér', 'Szepetnek', 'Szerecseny', 'Szeremle',
             'Szerencs', 'Szerep', 'Szergény', 'Szécsénke', 'Szécsény', 'Szécsényfelfalu', 'Szécsisziget', 'Székely',
             'Székelyszabar', 'Székesfehérvár', 'Székkutas', 'Szigetbecse', 'Szigetcsép', 'Szigethalom', 'Szigetmonostor',
             'Szigetszentmárton', 'Szigetszentmiklós', 'Szigetújfalu', 'Szigetvár', 'Szigliget', 'Szihalom', 'Szijártóháza',
             'Szikszó', 'Szil', 'Szilaspogony', 'Szilágy', 'Szilsárkány', 'Szilvágy', 'Szilvás', 'Szilvásszentmárton',
             'Szilvásvárad', 'Szin', 'Szinpetri', 'Szirák', 'Szirmabesenyő', 'Szob', 'Szokolya', 'Szolnok', 'Szombathely',
             'Szomolya', 'Szomor', 'Szomód', 'Szorgalmatos', 'Szorosad', 'Szólád', 'Szögliget', 'Szörény', 'Szőc',
             'Szőce', 'Sződ', 'Sződliget', 'Szőke', 'Szőkedencs', 'Szőkéd', 'Szőlősardó', 'Szőlősgyörök', 'Szuha',
             'Szuhafő', 'Szuhakálló', 'Szuhogy', 'Szulimán', 'Szulok', 'Szurdokpüspöki', 'Szúcs', 'Szügy', 'Szűcsi',
             'Szűr', 'Tab', 'Tabajd', 'Tabdi', 'Tagyon', 'Tahitótfalu', 'Takácsi', 'Taksony', 'Taktabáj', 'Taktaharkány',
             'Taktakenéz', 'Taktaszada', 'Taliándörögd', 'Tamási', 'Tanakajd', 'Tapolca', 'Tapsony', 'Tar', 'Tarany',
             'Tarcal', 'Tard', 'Tardona', 'Tardos', 'Tarhos', 'Tarján', 'Tarjánpuszta', 'Tarnabod', 'Tarnalelesz',
             'Tarnaméra', 'Tarnaörs', 'Tarnaszentmária', 'Tarnaszentmiklós', 'Tarnazsadány', 'Tarpa', 'Tarrós', 'Tass',
             'Taszár', 'Tata', 'Tatabánya', 'Tataháza', 'Tatárszentgyörgy', 'Táborfalva', 'Tác', 'Tákos', 'Tállya', 'Táp',
             'Tápióbicske', 'Tápiógyörgye', 'Tápióság', 'Tápiószecső', 'Tápiószele', 'Tápiószentmárton', 'Tápiószőlős',
             'Táplánszentkereszt', 'Tápszentmiklós', 'Tárkány', 'Tárnok', 'Tárnokréti', 'Táska', 'Tát', 'Tázlár', 'Teklafalu',
             'Telekes', 'Telekgerendás', 'Teleki', 'Település név', 'Telki', 'Telkibánya', 'Tengelic', 'Tengeri', 'Tengőd',
             'Tenk', 'Terem', 'Tereske', 'Teresztenye', 'Terény', 'Terpes', 'Teskánd', 'Tetétlen', 'Tevel', 'Téglás', 'Tékes',
             'Tényő', 'Tépe', 'Tés', 'Tésa', 'Tésenfa', 'Téseny', 'Tét', 'Tibolddaróc', 'Tiborszállás', 'Tihany', 'Tikos',
             'Tilaj', 'Timár', 'Tinnye', 'Tiszaadony', 'Tiszaalpár', 'Tiszabábolna', 'Tiszabecs', 'Tiszabercel', 'Tiszabezdéd',
             'Tiszabő', 'Tiszabura', 'Tiszacsege', 'Tiszacsermely', 'Tiszacsécse', 'Tiszadada', 'Tiszaderzs', 'Tiszadob',
             'Tiszadorogma', 'Tiszaeszlár', 'Tiszaföldvár', 'Tiszafüred', 'Tiszagyenda', 'Tiszagyulaháza', 'Tiszaigar',
             'Tiszainoka', 'Tiszajenő', 'Tiszakanyár', 'Tiszakarád', 'Tiszakerecseny', 'Tiszakeszi', 'Tiszakécske',
             'Tiszakóród', 'Tiszakürt', 'Tiszaladány', 'Tiszalök', 'Tiszalúc', 'Tiszamogyorós', 'Tiszanagyfalu', 'Tiszanána',
             'Tiszaörs', 'Tiszapalkonya', 'Tiszapüspöki', 'Tiszarád', 'Tiszaroff', 'Tiszasas', 'Tiszasüly', 'Tiszaszalka',
             'Tiszaszentimre', 'Tiszaszentmárton', 'Tiszasziget', 'Tiszaszőlős', 'Tiszatardos', 'Tiszatarján', 'Tiszatelek',
             'Tiszatenyő', 'Tiszaug', 'Tiszaújváros', 'Tiszavalk', 'Tiszavasvári', 'Tiszavárkony', 'Tiszavid', 'Tisztaberek',
             'Tivadar', 'Tokaj', 'Tokod', 'Tokodaltáró', 'Tokorcs', 'Tolcsva', 'Told', 'Tolmács', 'Tolna', 'Tolnanémedi',
             'Tomajmonostora', 'Tomor', 'Tompa', 'Tompaládony', 'Tordas', 'Tormafölde', 'Tormás', 'Tormásliget',
             'Tornabarakony', 'Tornakápolna', 'Tornanádaska', 'Tornaszentandrás', 'Tornaszentjakab', 'Tornyiszentmiklós',
             'Tornyosnémeti', 'Tornyospálca', 'Torony', 'Torvaj', 'Tóalmás', 'Tófalu', 'Tófej', 'Tófű', 'Tószeg',
             'Tótkomlós', 'Tótszentgyörgy', 'Tótszentmárton', 'Tótszerdahely', 'Tótújfalu', 'Tótvázsony', 'Tök', 'Tököl',
             'Töltéstava', 'Tömörd', 'Tömörkény', 'Törökbálint', 'Törökkoppány', 'Törökszentmiklós', 'Törtel',
             'Töttös', 'Trizs', 'Tunyogmatolcs', 'Tura', 'Tuzsér', 'Túristvándi', 'Túrkeve', 'Túrony', 'Túrricse',
             'Türje', 'Tüskevár', 'Tyukod', 'Udvar', 'Udvari', 'Ugod', 'Ukk', 'Und', 'Uppony', 'Ura', 'Uraiújfalu',
             'Uszka', 'Uszód', 'Uzsa', 'Újbarok', 'Újcsanálos', 'Újdombrád', 'Újfehértó', 'Újhartyán', 'Újiráz', 'Újireg',
             'Újkenéz', 'Újkér', 'Újkígyós', 'Újlengyel', 'Újléta', 'Újlőrincfalva', 'Újpetre', 'Újrónafő', 'Újsolt',
             'Újszalonta', 'Újszász', 'Újszentiván', 'Újszentmargita', 'Újszilvás', 'Újtelek', 'Újtikos', 'Újudvar',
             'Újvárfalva', 'Úny', 'Úrhida', 'Úri', 'Úrkút', 'Üllés', 'Üllő', 'Üröm', 'Vadna', 'Vadosfa', 'Vaja', 'Vajdácska',
             'Vajszló', 'Vajta', 'Valkonya', 'Valkó', 'Vanyarc', 'Vanyola', 'Varászló', 'Varbó', 'Varbóc', 'Varga', 'Varsád',
             'Varsány', 'Vasad', 'Vasalja', 'Vasasszonyfa', 'Vasboldogasszony', 'Vasegerszeg', 'Vashosszúfalu', 'Vaskeresztes',
             'Vaskút', 'Vasmegyer', 'Vaspör', 'Vassurány', 'Vasszentmihály', 'Vasszécseny', 'Vasszilvágy', 'Vasvár',
             'Vaszar', 'Vatta', 'Vác', 'Vácduka', 'Vácegres', 'Váchartyán', 'Váckisújfalu', 'Vácrátót', 'Vácszentlászló',
             'Vág', 'Vágáshuta', 'Vál', 'Vállaj', 'Vállus', 'Vámosatya', 'Vámoscsalád', 'Vámosgyörk', 'Vámosmikola',
             'Vámosoroszi', 'Vámospércs', 'Vámosszabadi', 'Vámosújfalu', 'Váncsod', 'Várad', 'Váralja', 'Váraszó',
             'Várbalog', 'Várda', 'Várdomb', 'Várfölde', 'Várgesztes', 'Várkesző', 'Várong', 'Városföld', 'Városlőd',
             'Várpalota', 'Várvölgy', 'Vásárosbéc', 'Vásárosdombó', 'Vásárosfalu', 'Vásárosmiske', 'Vásárosnamény',
             'Vászoly', 'Vát', 'Vázsnok', 'Vecsés', 'Vejti', 'Vekerd', 'Velem', 'Velemér', 'Velence', 'Velény', 'Vereb',
             'Veresegyház', 'Verőce', 'Verpelét', 'Verseg', 'Versend', 'Veszkény', 'Veszprém', 'Veszprémfajsz', 'Veszprémgalsa',
             'Veszprémvarsány', 'Vezseny', 'Vécs', 'Végegyháza', 'Vékény', 'Véménd', 'Vének', 'Vép', 'Vértesacsa',
             'Vértesboglár', 'Vérteskethely', 'Vértessomló', 'Vértesszőlős', 'Vértestolna', 'Vése', 'Vésztő', 'Vid',
             'Vigántpetend', 'Villány', 'Villánykövesd', 'Vilmány', 'Vilonya', 'Vilyvitány', 'Vinár', 'Vindornyafok',
             'Vindornyalak', 'Vindornyaszőlős', 'Visegrád', 'Visnye', 'Visonta', 'Viss', 'Visz', 'Viszák', 'Viszló',
             'Visznek', 'Vitnyéd', 'Vizslás', 'Vizsoly', 'Vízvár', 'Vokány', 'Vonyarcvashegy', 'Vöckönd', 'Völcsej',
             'Vönöck', 'Vöröstó', 'Vörs', 'Zabar', 'Zagyvarékas', 'Zagyvaszántó', 'Zajk', 'Zajta', 'Zala', 'Zalaapáti',
             'Zalabaksa', 'Zalabér', 'Zalaboldogfa', 'Zalacsány', 'Zalacséb', 'Zalaegerszeg', 'Zalaerdőd', 'Zalagyömörő',
             'Zalahaláp', 'Zalaháshágy', 'Zalaigrice', 'Zalaistvánd', 'Zalakaros', 'Zalakomár', 'Zalaköveskút',
             'Zalalövő', 'Zalameggyes', 'Zalamerenye', 'Zalasárszeg', 'Zalaszabar', 'Zalaszántó', 'Zalaszegvár',
             'Zalaszentbalázs', 'Zalaszentgrót', 'Zalaszentgyörgy', 'Zalaszentiván', 'Zalaszentjakab', 'Zalaszentlászló',
             'Zalaszentlőrinc', 'Zalaszentmárton', 'Zalaszentmihály', 'Zalaszombatfa', 'Zalatárnok', 'Zalaújlak',
             'Zalavár', 'Zalavég', 'Zaláta', 'Zalkod', 'Zamárdi', 'Zaránk', 'Zádor', 'Zádorfalva', 'Záhony', 'Zákány',
             'Zákányfalu', 'Zákányszék', 'Zámoly', 'Zánka', 'Závod', 'Zebecke', 'Zebegény', 'Zemplénagárd',
             'Zengővárkony', 'Zichyújfalu', 'Zics', 'Ziliz', 'Zimány', 'Zirc', 'Zomba', 'Zók', 'Zsadány', 'Zsana',
             'Zsarolyán', 'Zsáka', 'Zsámbék', 'Zsámbok', 'Zsebeháza', 'Zselickisfalud', 'Zselickislak', 'Zselicszentpál',
             'Zsennye', 'Zsédeny', 'Zsira', 'Zsombó', 'Zsujta', 'Zsurk', 'Zubogy']


megye = ['Bács-Kiskun', 'Baranya', 'Békés', 'Borsod-Abaúj-Zemplén', 'Csongrád-Csanád', 'Fejér',
         'Győr-Moson-Sopron', 'Hajdú-Bihar', 'Heves', 'Jász-Nagykun-Szolnok', 'Komárom-Esztergom',
         'Nógrád', 'Pest', 'Somogy', 'Szabolcs-Szatmár-Bereg', 'Tolna', 'Vas', 'Veszprém', 'Zala']

folyo = ['Duna', 'Tisza', 'Dráva', 'Rába', 'Marcal', 'Szamos', 'Körös', 'Zagyva', 'Sajó', 'Ipoly',
         'Driszavica', 'Bodrog', 'Latorica', 'Zala', 'Hernád', 'Rábca', 'Lajta',
         'Kis-Duna', 'Fekete-Körös', 'Kis-Sajó', 'Torna', 'Kraszna', 'Mura', 'Séd', 'Kapos', 'Galga',
         'Cserna', 'Ivacs-patak', 'Bükkös-patak', 'Pilinka', 'Bodva', 'Hármas-Körös', 'Sajgó']

nap = ['hétfő', 'kedd', 'szerda', 'csütörtök', 'péntek', 'szombat', 'vasárnap']

honap = ['január', 'február', 'március', 'április', 'május', 'június', 'július',
         'augusztus', 'szeptember', 'október', 'november', 'december']

gyumolcs= ['alma', 'ananász',  'banán', 'barack', 'birs', 'cseresznye', 'datolya', 'dinnye', 'eper', 'füge',
            'gránátalma', 'kajszibarack', 'kivi', 'málna', 'meggy', 'narancs', 'őszibarack', 'ribizli',
            'sárgabarack', 'szeder', 'szilva', 'egres', 'vörösszőlő', 'szeder', 'körte', 'meggy', 'áfonya',
           'sárgadinnye', 'erdei szamóca', 'mangó']

zoldseg = ['articsóka', 'bab', 'borsó', 'brokkoli', 'burgonya', 'cékla', 'csicsóka', 'csiperkegomba', 'fokhagyma',
           'hagyma', 'karalábé', 'karfiol', 'káposzta', 'kelbimbó', 'kukorica', 'fejes sajáta', 'lilahagyma',
           'lilakáposzta', 'padlizsán', 'paprika', 'paszternák', 'retek', 'sárgarépa', 'spárga', 'spenót',
           'sütőtök', 'tök', 'uborka', 'zeller', 'sárgarépa', 'feketeretek','zeller', 'kínai kel', 'retek',
           'jégcsapretek', 'fokhagyma', 'újhagyma', 'szárzeller']

haszonallat = [ 'tehén', 'juh', 'kecske', 'disznó', 'tyúk', 'kacsa', 'liba', 'pulyka', 'strucc', 'ló', 'szamár', 'bivaly',
                 'jak', 'csirke', 'nyúl', 'szarvasmarha', 'szürkemarha', 'sertés', 'malac', 'gyöngytyúk', 'birka']

vad = ['medve', 'farkas', 'róka', 'borz', 'őz', 'szarvas','nyest', 'vaddisznó','muflon','vidra',
            'gímszarvas', 'molnárgörény','vadmacska']

hal = ['keszeg', 'ponty', 'csuka', 'harcsa', 'süllő', 'kárász', 'angolna', 'márna', 'fogasponty', 'sügér', 'amur',
         'menyhal', 'domolykó', 'keszeg', 'garda', 'paduc', 'compó', 'bodorka', 'nyúldomolykó']

madar = ['feketerigó', 'fülemüle', 'csalogány', 'kékvércse', 'széncinege', 'szajkó', 'szürkebegy', 'búbosbanka',
         'zöldike', 'sármány', 'fácán', 'kakukk', 'bölömbika', 'örvényi sas', 'szirti sas', 'parlagi sas',
         'réti keselyű', 'héja', 'pávaszemes fecske', 'gyurgyalag', 'gólya', 'kócsag', 'hattyú', 'vadkacsa', 'vadlúd',
         'szárcsa', 'rigó', 'szajkó']

bolygo =['Merkúr', 'Vénusz', 'Föld', 'Mars', 'Jupiter','Szaturnusz', 'Uránusz', 'Neptunusz']


leves = ["Gulyásleves", "Halászlé", "Hideg meggyleves", "Zöldborsóleves", "Jókai bableves", "Csontleves",
           "Marhahúsleves", "Zellerkrémleves", "Sárgaborsóleves", "Babgulyásleves", "Karalábéleves", "Zöldségleves",
           "Kukoricaleves", "Karfiolleves", "Hideg gyümölcsleves", "Korhelyleves", "Tyúkhúsleves",
           "Pirított tarhonyaleves", "Gombaleves", "Lencseleves", "Gulyáskrémleves", "Csülökleves", "Paradicsomleves",
           "Borleves", "Tárkonyos raguleves", "Zöldbableves", "Kapros-joghurtos leves", "Paradicsomleves betűtésztával",
           "Sajtos-tejfölös leves", "Burgonyaleves", "Csirkeleves", "Krumplileves",  "Tavaszi zöldségleves",
           "Karfiol krémleves", "Tojásleves", "Tárkonyos csirkeraguleves", "Káposztaleves", "Húsos zöldborsóleves",
           "Sárgadinnyeleves", "Tavaszi zöldségleves tarhonyával", "Hagymaleves",  "Húsleves gazdagon",
           "Gesztenyekrémleves", "Jérceleves", "Kolbászos bableves", "Uborkaleves", "Tejszínes karfiolleves",
           "Tarkabableves", "Hideg szilvaleves", "Fokhagymaleves", "Májgombócleves", "Brokkolileves",
           "Savanyú káposztaleves", "Erőleves", "Tejfölös gombaleves",  "Húsos káposztaleves", "Zöldspárga krémleves",
           "Sóska krémleves", "Burgonyapüréleves", "Laskaleves",  "Paradicsomleves húsgombóccal", "Csirkemájleves",
           "Ribizlileves", "Cukkinikrémleves", "Fokhagymás zöldbableves", "Zöldségleves tojással"]

foetel= ['Vadörkölt', 'Sült csirke',
         'Sertésszelet', 'Rántott hús', 'Paprikás csirke', 'Sült kolbász', 'Rántott sajt', 'Rántott karfiol',
         'Kacsacomb rántva', 'Kakaspörkölt',  'Sült hal',  'Gombapaprikás',
         'Marhapörkölt', 'Pacalpörkölt', 'Roston sült csirke',
         'Rántott gomba', 'Rántott karaj', 'Rántott csirkemell', 'Halpaprikás', 'Libamáj',
         'Sült sertés', 'Halpaprikás', 'Csülök Pékné módra', 'Borjúpörkölt ',
         'Párizsi csirkemell', 'Rántott karaj', 'Kacsapörkölt', 'Csirkepaprikás',  'Rántott csirkeszárny', 'Pacalpörkölt',
         'Rántott jércemell', 'Sertéspörkölt','Mátrai borzaska',
         'Grillezett csirkecomb', 'Lecsós csirke', 'Rántott gomba ', 'Rántott ponty', 'Lazacsteak', 'Roston sült hal',
         'Rántott camembert', 'Sült kacsacomb', 'Sült libacomb', 'Sült pulykamell', 'Sült tarja', 'Báránytokány',
         'Szűzérmék',  'Cordon bleu', 'Sült Kacsamáj',
         'Lecsós tarja', 'Stefánia vagdalt']

koret = ['Párolt rizs', 'Hagymás tört burgonya', 'Burgonyapüré', 'Párolt zöldségek', 'Hasábburgonya',
           'Grillezett zöldségek', 'Köleskása', 'Galuska', 'Zöldségköret', 'Kukoricás rizs', 'Sárgarépa püré',
            'Tarhonya',  'Burgonyakrokett', 'Kuszkusz', 'Brokkolipüré', 'Párolt sárgarépa',
           'Tarhonya',  'Zöldborsós rizs', 'Gombás rizs', 'Gersli',  'Sült édesburgonya hasáb',
           'Édesburgonya püré',  'Hercegnő burgonya', 'Csónak burgonya', 'Tepsis sült burgonya']

egytal = ['Rakott krumpli', 'Töltött káposzta', 'Lecsó','Töltött paprika','Lencsefőzelék sültkolbásszal','Hortobágyi húsos palacsinta',
          'Sztrapacska szalonna pörccel','Burgonyás tészta','Csirkés rizottó','Rakott kelkáposzta csőben sütve',
           'Rakott zöldbab', 'Disznótoros káposzta friss kenyérrel', 'Bácskai rizseshús', 'Brassói aprópecsenye','Tarhonyás hús',
          'Székelykáposzta kenyérrel','Paradicsomos töltött káposzta','Rakott cukkini', 'Pásztortarhonya','Húsos-szaftos tészta',
          'Lecsó Mezőcsáti módra', 'Sonkás-paradicsomos tészta', 'Sajtos-sonkás rakott tészta', 'Kolozsvári rakott káposzta',
          'Sonkás tészta csőben sütve','Túrós csusza','Kapros-túrós csusza', 'Székelykáposzta','Paprikás krumpli', 'Rakott padlizsán' ]

desszert = [
    'Almás pite', 'Aranygaluska','Bejgli','Bodri torta','Boszorkányszigeti torta','Budapest roló', 'Császármorzsa',
    'Csokoládé torta','Dobostorta','Diótorta', 'Esterházy torta','Fekete-erdő torta','Flódni','Gesztenyepüré torta',
    'János vitéz tortája', 'Joghurt torta', 'Kakaós-meggyes pite', 'Képviselőfánk', 'Két színű torta',
    'Kókuszos szelet', 'Krémes', 'Linzer', 'Mákos guba', 'Mákos kalács', 'Napóleon torta', 'Orosz krémtorta',
    'Francia krémes', 'Puncsgolyó','Rakott palacsinta','Rákóczi túrós','Rigó Jancsi', 'Somlói galuska',
    'Tiramisu','Répatorta']

bor = ['Tokaji Furmint', 'Villányi Franc', 'Eger Bikavér', 'Szekszárdi Bikavér', 'Balatonboglári Kékfrankos',
       'Badacsonyi Olaszrizling', 'Villányi Portugieser', 'Villányi Cabernet Franc', 'Egri Kékfrankos',
       'Villányi Merlot', 'Etyeki Chardonnay', 'Somlói Juhfark', 'Tokaji Aszú', 'Mátrai Irsai Olivér',
       'Villányi Cabernet Sauvignon', 'Balatonfüredi Szürkebarát', 'Soproni Kékfrankos', 'Szekszárdi Kadarka',
       'Szekszárdi Merlot', 'Balatonlellei Olaszrizling', 'Badacsonyi Kéknyelű', 'Villányi Syrah',
       'Somlói Furmint', 'Tokaji Szamorodni', 'Villányi Cuvée', 'Villányi Pinot Noir', 'Badacsonyi Kékfrankos',
       'Mátrai Pinot Noir', 'Tokaji Hárslevelű', 'Villányi Kékfrankos', 'Somlói Traminer',
       'Badacsonyi Muscat Ottonel', 'Villányi Kadarka', 'Mátrai Cabernet Sauvignon', 'Soproni Pinot Noir',
       'Balatonfüredi Olaszrizling', 'Badacsonyi Szürkebarát', 'Tokaji Szamorodni Édes', 'Egri Leányka',
       'Szekszárdi Cuvée', 'Villányi Kéknyelű', 'Egri Merlot', 'Somlói Olaszrizling',
       'Badacsonyi Rizlingszilváni', 'Villányi Portugieser Rosé', 'Balatonboglári Zenit',
       'Balatonlellei Riesling', 'Tokaji Szamorodni Száraz', 'Soproni Rosé']

udito = ['Narancslé', 'Almalé', 'Tonik', 'Ásványvíz', 'Gyümölcslé', 'Szőlőlé',
        'Bodza szörp', 'Cseresznyeszörp', 'Málnaszörp', 'Eper szörp',  'Zöld teás üdítő',
        'Narancs ízű ásványvíz','Coca Cola', 'Fanta', 'Sprite', 'Jeges tea', 'Gyömbér',
        'Bambi', 'Róna', 'Márka','Traubisoda','Olympos','Málna-gyöngye','Meggy-gyöngye',
        'Sió gyümölcs nektár','Limonádé']



kiraly = {'Árpád': (895, 907), 'Zoltán': (907, 947), 'Fajsz': (947, 955), 'Taksony': (955, 972), 'Géza': (972, 997),
    'I.István': (997, 1038),'I. Péter': (1038, 1041), 'Sámuel': (1041, 1044), 'Péter-2': (1044, 1045), 'I.András': (1041, 1060),
    'I. Béla': (1060, 1063), 'Salamon': (1063, 1074), 'I. Géza': (1074, 1077), 'I. László': (1077, 1095),
    'Kálmán': (1095, 1116),'II. István': (1116, 1131), 'II. Béla': (1131, 1141), 'II. Géza': (1141,1162),
    'III. István': (1162, 1172), 'III. Béla': (1172, 1196), 'Imre':(1196, 1204), 'III. László': (1204, 1205),
    'II. András': (1205, 1235),'IV. Béla': (1235, 1270), 'V. István': (1270, 1272), 'IV. László': (1272, 1290),
    'III. András': (1290, 1301), 'Vencel': (1301, 1305), 'Ottó': (1305, 1307), 'I. Károly': (1308, 1342),
    'I.Lajos': (1342, 1382), 'Mária': (1382, 1385), 'II. Károly': (1385, 1386), 'Mária-2':(1386, 1395),
    'Zsigmond' : (1387, 1437), 'Albert': (1437, 1439), 'V. László': (1440, 1457), 'I. Ulászló': (1440, 1444),
    'I. Mátyás': (1458, 1490), 'II. Ulászló': (1490, 1516), 'II. Lajos': (1516, 1526), 'I.János': (1526, 1540),
    'II. János' : (1540, 1571), 'I. Ferdinánd': (1526, 1564), 'Miksa': (1564, 1576), 'Rudolf': (1576, 1608),
    'II. Mátyás': (1608, 1619), 'II. Ferdinánd': (1618, 1637), 'III. Ferdinánd': (1637,1657), 'IV. Ferdinánd': (1647,1654),
    'I. Lipót' : (1657, 1705),  'I. József': (1705,1711), 'III. Károly': (1711,1740), 'Mária Terézia': (1740, 1780),
    'II. József':(1780, 1790), 'II. Lipót': (1790, 1792), 'I. Ferenc': (1790, 1835), 'V. Ferdinánd' : (1835,1848),
    'I. Ferenc József' : (1848,1916), 'IV. Károly':(1916,1918) }

megye_szekhely= {'Bács-Kiskun': 'Kecskemét','Baranya': 'Pécs', 'Békés': 'Békéscsaba','Borsod-Abaúj-Zemplén': 'Miskolc',
    'Csongrád-Csanád': 'Szeged','Fejér': 'Székesfehérvár', 'Győr-Moson-Sopron': 'Győr','Hajdú-Bihar': 'Debrecen',
    'Heves': 'Eger','Jász-Nagykun-Szolnok': 'Szolnok', 'Komárom-Esztergom': 'Tatabánya', 'Nógrád': 'Salgótarján',
    'Pest': 'Budapest', 'Somogy': 'Kaposvár', 'Szabolcs-Szatmár-Bereg': 'Nyíregyháza', 'Tolna': 'Szekszárd',
    'Vas': 'Szombathely', 'Veszprém': 'Veszprém', 'Zala': 'Zalaegerszeg' }

jaras= {
    'Bácsalmási járás': ['Bácsalmás', 'Bács-Kiskun'],'Bajai járás': ['Baja', 'Bács-Kiskun'],
    'Jánoshalmi járás': ['Jánoshalma', 'Bács-Kiskun'],'Kalocsai járás': ['Kalocsa', 'Bács -Kiskun'],
    'Kecskeméti járás': ['Kecskemét', 'Bács-Kiskun'], 'Kiskőrösi járás': ['Kiskőrös', 'Bács-Kiskun'],
    'Kiskunfélegyházi járás': ['Kiskunfélegyháza', 'Bács-Kiskun'], 'Kiskunhalasi járás': ['Kiskunhalas', 'Bács-Kiskun'],
    'Kunszentmiklósi járás': ['Kunszentmiklós', 'Bács-Kiskun'], 'Tiszakécskei járás': ['Tiszakécske', 'Bács-Kiskun'],
    'Kiskunmajsai járás' :['Kiskunmajsa', 'Bács-Kiskun'],
    'Bólyi járás': ['Bóly', 'Baranya'], 'Hegyháti járás': ['Sásd', 'Baranya'],
    'Komlói járás': ['Komló', 'Baranya'],'Mohácsi járás': ['Mohács', 'Baranya'],
    'Pécsi járás': ['Pécs', 'Baranya'], 'Pécsváradi járás': ['Pécsvárad', 'Baranya'],
    'Sellyei járás': ['Sellye', 'Baranya'], 'Szentlőrinci járás': ['Szentlőrinc', 'Baranya'],
    'Siklósi járás': ['Siklós', 'Baranya'], 'Szigetvári járás': ['Szigetvár', 'Baranya'],
    'Békési járás':['Békés', 'Békés'],'Gyulai járás': ['Gyula', 'Békés'],
    'Mezőkovácsházi járás': ['Mezőkovácsháza', 'Békés'],'Orosházi járás': ['Orosháza', 'Békés'],
    'Sarkadi járás': ['Sarkad', 'Békés'], 'Szeghalmi járás': ['Szeghalom', 'Békés'],
    'Békéscsabai járás':['Békéscsaba', 'Békés'], 'Gyomaendrődi járás':['Gyomaendrőd', 'Békés'],
    'Szarvasi járás':['Szarvas', 'Békés'],
    'Cigándi járás': ['Cigánd', 'Borsod-Abaúj-Zemplén'], 'Edelényi járás': ['Edelény', 'Borsod-Abaúj-Zemplén'],
    'Encsi járás': ['Encs', 'Borsod-Abaúj-Zemplén'], 'Gönci járás': ['Gönc', 'Borsod-Abaúj-Zemplén'],
    'Kazincbarcikai járás': ['Kazincbarcika', 'Borsod-Abaúj-Zemplén'], 'Mezőcsáti járás': ['Mezőcsát', 'Borsod-Abaúj-Zemplén'],
    'Mezőkövesdi járás': ['Mezőkövesd', 'Borsod-Abaúj-Zemplén'],  'Miskolci járás': ['Miskolc', 'Borsod-Abaúj-Zemplén'],
    'Ózdi járás': ['Ózd', 'Borsod-Abaúj-Zemplén'],  'Putnoki járás': ['Putnok', 'Borsod-Abaúj-Zemplén'],
    'Sárospataki járás': ['Sárospatak', 'Borsod-Abaúj-Zemplén'], 'Sátoraljaújhelyi járás': ['Sátoraljaújhely', 'Borsod-Abaúj-Zemplén'],
    'Szerencsi járás': ['Szerencs', 'Borsod-Abaúj-Zemplén'],  'Szikszói járás': ['Szikszó', 'Borsod-Abaúj-Zemplén'],
    'Tiszaújvárosi járás': ['Tiszaújváros', 'Borsod-Abaúj-Zemplén'],  'Tokaji járás': ['Tokaj', 'Borsod-Abaúj-Zemplén'],
    'Csongrádi járás': ['Csongrád', 'Csongrád-Csanád'],'Hódmezővásárhelyi járás': ['Hódmezővásárhely', 'Csongrád-Csanád'],
    'Kisteleki járás': ['Kistelek', 'Csongrád-Csanád'], 'Makói járás': ['Makó', 'Csongrád-Csanád'],
    'Mórahalmi járás': ['Mórahalom', 'Csongrád-Csanád'],'Szegedi járás': ['Szeged', 'Csongrád-Csanád'],
    'Szentesi járás': ['Szentes', 'Csongrád-Csanád'],
    'Bicskei járás': ['Bicske', 'Fejér'], 'Dunaújvárosi járás': ['Dunaújváros', 'Fejér'],
    'Enyingi járás': ['Enying', 'Fejér'],'Gárdonyi járás': ['Gárdony', 'Fejér'],
    'Martonvásári járás': ['Martonvásár', 'Fejér'],'Móri járás': ['Mór', 'Fejér'],
    'Sárbogárdi járás': ['Sárbogárd', 'Fejér'], 'Székesfehérvári járás': ['Székesfehérvár', 'Fejér'],
    'Csornai járás': ['Csorna', 'Győr-Moson-Sopron'], 'Győri járás': ['Győr', 'Győr-Moson-Sopron'],
    'Kapuvári járás': ['Kapuvár', 'Győr-Moson-Sopron'], 'Mosonmagyaróvári járás': ['Mosonmagyaróvár', 'Győr-Moson-Sopron'],
    'Pannonhalmi járás': ['Pannonhalma', 'Győr-Moson-Sopron'], 'Soproni járás': ['Sopron', 'Győr-Moson-Sopron'],
    'Téti járás': ['Tét', 'Győr-Moson-Sopron'],
    'Balmazújvárosi járás': ['Balmazújváros', 'Hajdú-Bihar'],'Berettyóújfalui járás': ['Berettyóújfalu', 'Hajdú-Bihar'],
    'Debreceni járás': ['Debrecen', 'Hajdú-Bihar'],'Derecskei járás': ['Derecske', 'Hajdú-Bihar'],
    'Hajdúböszörményi járás': ['Hajdúböszörmény', 'Hajdú-Bihar'],'Hajdúhadházi járás': ['Hajdúhadház', 'Hajdú-Bihar'],
    'Hajdúnánási járás': ['Hajdúnánás', 'Hajdú-Bihar'],'Hajdúszoboszlói járás': ['Hajdúszoboszló', 'Hajdú-Bihar'],
    'Nyíradonyi járás': ['Nyíradony', 'Hajdú-Bihar'],'Püspökladányi járás': ['Püspökladány', 'Hajdú-Bihar'],
    'Bélapátfalvai járás': ['Bélapátfalva', 'Heves'], 'Egri járás': ['Eger', 'Heves'],
    'Füzesabonyi járás': ['Füzesabony', 'Heves'], 'Gyöngyösi járás': ['Gyöngyös', 'Heves'],
    'Hatvani járás': ['Hatvan', 'Heves'],'Hevesi járás': ['Heves', 'Heves'],
    'Pétervásárai járás': ['Pétervására', 'Heves'],
    'Jászapáti járás': ['Jászapáti', 'Jász-Nagykun-Szolnok'],'Jászberényi járás': ['Jászberény', 'Jász-Nagykun-Szolnok'],
    'Karcagi járás': ['Karcag', 'Jász-Nagykun-Szolnok'],'Kunhegyesi járás': ['Kunhegyes', 'Jász-Nagykun-Szolnok'],
    'Kunszentmártoni járás': ['Kunszentmárton', 'Jász-Nagykun-Szolnok'],
    'Mezőtúri járás': ['Mezőtúr', 'Jász-Nagykun-Szolnok'],
    'Szolnoki járás': ['Szolnok', 'Jász-Nagykun-Szolnok'],
    'Tiszafüredi járás': ['Tiszafüred', 'Jász-Nagykun-Szolnok'],
    'Törökszentmiklósi járás': ['Törökszentmiklós', 'Jász-Nagykun-Szolnok'],
    'Esztergomi járás': ['Esztergom', 'Komárom-Esztergom'],'Kisbéri járás': ['Kisbér', 'Komárom-Esztergom'],
    'Komáromi járás': ['Komárom', 'Komárom-Esztergom'], 'Oroszlányi járás': ['Oroszlány', 'Komárom-Esztergom'],
    'Tatabányai járás': ['Tatabánya', 'Komárom-Esztergom'],'Tatai járás': ['Tata', 'Komárom-Esztergom'],
    'Balassagyarmati járás': ['Balassagyarmat', 'Nógrád'], 'Bátonyterenyei járás': ['Bátonyterenye', 'Nógrád'],
    'Pásztói járás': ['Pásztó', 'Nógrád'], 'Rétsági járás': ['Rétság', 'Nógrád'],
    'Salgótarjáni járás': ['Salgótarján', 'Nógrád'], 'Szécsényi járás': ['Szécsény', 'Nógrád'],
    'Aszódi járás': ['Aszód', 'Pest'],'Budakeszi járás': ['Budakeszi', 'Pest'],
    'Ceglédi járás': ['Cegléd', 'Pest'],'Dabasi járás': ['Dabas', 'Pest'],
    'Dunakeszi járás': ['Dunakeszi', 'Pest'],'Érdi járás': ['Érd', 'Pest'],
    'Gödöllői járás': ['Gödöllő', 'Pest'], 'Gyáli járás': ['Gyál', 'Pest'],
    'Monori járás': ['Monor', 'Pest'],'Nagykátai járás': ['Nagykáta', 'Pest'],
    'Nagykőrösi járás': ['Nagykőrös', 'Pest'],'Pilisvörösvári járás': ['Pilisvörösvár', 'Pest'],
    'Ráckevei járás': ['Ráckeve', 'Pest'], 'Szentendrei járás': ['Szentendre', 'Pest'],
    'Szigetszentmiklósi járás': ['Szigetszentmiklós', 'Pest'],'Szobi járás': ['Szob', 'Pest'],
    'Váci járás': ['Vác', 'Pest'],'Vecsési járás': ['Vecsés', 'Pest'],
    'Barcsi járás': ['Barcs', 'Somogy'],  'Csurgói járás': ['Csurgó', 'Somogy'],
    'Fonyódi járás': ['Fonyód', 'Somogy'], 'Kaposvári járás': ['Kaposvár', 'Somogy'],
    'Marcali járás': ['Marcali', 'Somogy'], 'Nagyatádi járás': ['Nagyatád', 'Somogy'],
    'Siófoki járás': ['Siófok', 'Somogy'], 'Tabi járás': ['Tab', 'Somogy'],
    'Baktalórántházai járás': ['Baktalórántháza', 'Szabolcs-Szatmár-Bereg'],'Csengeri járás': ['Csenger', 'Szabolcs-Szatmár-Bereg'],
    'Fehérgyarmati járás': ['Fehérgyarmat', 'Szabolcs-Szatmár-Bereg'], 'Ibrányi járás': ['Ibrány', 'Szabolcs-Szatmár-Bereg'],
    'Kemecsei járás': ['Kemecse', 'Szabolcs-Szatmár-Bereg'],'Kisvárdai járás': ['Kisvárda', 'Szabolcs-Szatmár-Bereg'],
    'Mátészalkai járás': ['Mátészalka', 'Szabolcs-Szatmár-Bereg'], 'Nagykállói járás': ['Nagykálló', 'Szabolcs-Szatmár-Bereg'],
    'Nyírbátori járás': ['Nyírbátor', 'Szabolcs-Szatmár-Bereg'], 'Nyíregyházi járás': ['Nyíregyháza', 'Szabolcs-Szatmár-Bereg'],
    'Tiszavasvári járás': ['Tiszavasvári', 'Szabolcs-Szatmár-Bereg'],'Vásárosnaményi járás': ['Vásárosnamény', 'Szabolcs-Szatmár-Bereg'],
    'Záhonyi járás': ['Záhony', 'Szabolcs-Szatmár-Bereg'],
    'Bonyhádi járás': ['Bonyhád', 'Tolna'], 'Dombóvári járás': ['Dombóvár', 'Tolna'],
    'Paksi járás': ['Paks', 'Tolna'], 'Szekszárdi járás': ['Szekszárd', 'Tolna'],
    'Tamási járás': ['Tamási', 'Tolna'], 'Tolnai járás': ['Tolna', 'Tolna'],
    'Celldömölki járás': ['Celldömölk', 'Vas'],'Körmendi járás': ['Körmend', 'Vas'], 'Kőszegi járás': ['Kőszeg', 'Vas'],
    'Sárvári járás': ['Sárvár', 'Vas'],'Szentgotthárdi járás': ['Szentgotthárd', 'Vas'],
    'Szombathelyi járás': ['Szombathely', 'Vas'],   'Vasvári járás': ['Vasvár', 'Vas'],
    'Ajkai járás': ['Ajka', 'Veszprém'], 'Balatonalmádi járás': ['Balatonalmádi', 'Veszprém'],
    'Balatonfüredi járás': ['Balatonfüred', 'Veszprém'], 'Devecseri járás': ['Devecser', 'Veszprém'],
    'Pápai járás': ['Pápa', 'Veszprém'], 'Sümegi járás': ['Sümeg', 'Veszprém'],'Tapolcai járás': ['Tapolca', 'Veszprém'],
    'Várpalotai járás': ['Várpalota', 'Veszprém'], 'Veszprémi járás': ['Veszprém', 'Veszprém'], 'Zirci járás': ['Zirc', 'Veszprém'],
    'Keszthelyi járás': ['Keszthely', 'Zala'],'Lenti járás': ['Lenti', 'Zala'],'Letenyei járás': ['Letenye', 'Zala'],
    'Nagykanizsai járás': ['Nagykanizsa', 'Zala'],'Zalaegerszegi járás': ['Zalaegerszeg', 'Zala'],
    'Zalaszentgróti járás': ['Zalaszentgrót', 'Zala'] }

villamos = {
            "BKK1": {"viszonylat":1, "indulas": "Kelenföld vasútállomás", "erkezes": "Bécsi út/Vörösvári út","menetido": 50,"varos": "Budapest" },
            "BKK2":{"viszonylat": 2, "indulas": "Jászai Mari tér", "erkezes" : "Közvágóhíd", "menetido" : 22 ,"varos": "Budapest" },
            "BKK3":{"viszonylat": 3, "indulas": "Mexikói út metróállomás", "erkezes" : "Gubacsi út/ Határ út", "menetido" : 47,"varos": "Budapest" },
            "BKK4":{ "viszonylat": 4,"indulas": "Széll Kálmán tér metróállomás", "erkezes" : "Újbuda központ metróállomás", "menetido": 30,"varos": "Budapest" },
            "BKK6":{ "viszonylat": 6,"indulas": "Széll Kálmán tér metróállomás", "erkezes" : "Móricz Zsigmond körtér metróállomás", "menetido" : 30 ,"varos": "Budapest"},
            "BKK12":{"viszonylat": 12, "indulas": "Angyalföld kocsiszín", "erkezes" : "Rákospalota Kossuth utca", "menetido" : 14,"varos": "Budapest"},
            "BKK14":{"viszonylat": 14,"indulas": "Lehel tér metróállomás", "erkezes" : "Káposztásmegye, Megyeri út", "menetido" : 33 ,"varos": "Budapest"},
            "BKK17":{"viszonylat": 17,"indulas": "Savoya park", "erkezes" : "Bécsi út/ Vörösvári út", "menetido" : 52,"varos": "Budapest" },
            "BKK19":{"viszonylat": 19, "indulas": "Kelenföld vasútállomás", "erkezes" : "Bécsi út / Vörösvári út", "menetido" : 40,"varos": "Budapest"},
            "BKK23":{"viszonylat": 23, "indulas": "Jászai Mari tér", "erkezes" : "Keleti pályaudvar metróállomás", "menetido": 35,"varos": "Budapest"},
            "BKK24":{"viszonylat": 24,"indulas": "Keleti pályudvar metróállomás", "erkezes" : "Közvágóhíd HÉV állomás", "menetido": 18,"varos": "Budapest"},
            "BKK28":{"viszonylat": 28, "indulas": "Blaha Lujza tér metróállomás", "erkezes" : "Izraelita temető", "menetido": 38,"varos": "Budapest"},
            "BKK37":{"viszonylat": 37,"indulas": "Blaha Lujza tér metróállomás", "erkezes" : "Új köztemető (Kozma utca)", "menetido": 31,"varos": "Budapest"},
            "BKK41":{"viszonylat": 41, "indulas": "Kamaraerdei ifjúsági park", "erkezes" : "Bécsi út / Vörösvári út", "menetido": 62,"varos": "Budapest"},
            "BKK42":{"viszonylat": 42, "indulas": "Határ út metróállomás", "erkezes" : "Kispest Tulipán utca", "menetido": 8,"varos": "Budapest"},
            "BKK47":{"viszonylat": 47, "indulas": "Deák Ferenc tér metróállomás", "erkezes" : "Városház tér", "menetido": 31,"varos": "Budapest"},
            "BKK48":{"viszonylat": 48, "indulas": "Savoya park", "erkezes" : "Deák Ferenc tér metróállomás", "menetido": 28,"varos": "Budapest"},
            "BKK49":{"viszonylat": 49, "indulas": "Kelenföld vasútállomás", "erkezes" : "Deák Ferenc tér metróállomás", "menetido": 20,"varos": "Budapest"},
            "BKK50":{ "viszonylat": 50,"indulas": "Határ út", "erkezes" : "Pestszentlőrinc ,Béke tér", "menetido": 25,"varos": "Budapest"},
            "BKK51":{ "viszonylat": 51,"indulas": "Nagysándor József utca", "erkezes" : "Ferenc körút/Mester utca", "menetido": 28,"varos": "Budapest"},
            "BKK52":{ "viszonylat": 52,"indulas": "Határ út metróállomás", "erkezes" : "Pesterzsébet, Pacsirtatelep", "menetido": 25,"varos": "Budapest"},
            "BKK56":{"viszonylat": 56, "indulas": "Hűvösvölgy", "erkezes" : "Városház tér", "menetido": 56,"varos": "Budapest"},
            "BKK59":{"viszonylat": 59,"indulas": "Márton Áron tér", "erkezes" : "Szent János kórház", "menetido": 19,"varos": "Budapest"},
            "BKK60":{"viszonylat": 60,"indulas": "Városmajor", "erkezes" : "Széchenyi-hegy, Gyermekvasút", "menetido": 14,"varos": "Budapest"},
            "BKK61": {"viszonylat": 61, "indulas": "Móricz Zsigmond körtér", "erkezes" : "Hűvösvölgy", "menetido": 35,"varos": "Budapest"},
            "BKK62":{"viszonylat": 62, "indulas": "Blaha Lujza tér metróállomás", "erkezes" : "Rákospalota, MÁV-telep", "menetido": 47,"varos": "Budapest"},
            "BKK69":{"viszonylat": 69, "indulas": "Újpalota, Erdőkerülő utca", "erkezes" : "Mexikói út metróállomás", "menetido": 56,"varos": "Budapest"},
            "DKV1": {"viszonylat": 1, "indulas": "Nagyállomás", "erkezes": "Nagyállomás", "menetido": 38, "varos": "Debrecen"},
            "DKV2": {"viszonylat": 2, "indulas": "Nagyállomás", "erkezes": "Nagyállomás", "menetido": 44, "varos": "Debrecen"},
            "MVK1": {"viszonylat": 1, "indulas": "Tiszai pályaudvar", "erkezes": "Felső-Majláth", "menetido": 33,"varos": "Miskolc"},
            "MVK2": {"viszonylat": 2, "indulas": "Tiszai pályaudvar", "erkezes": "Újgyőri főtér", "menetido": 26,"varos": "Miskolc"},
            "SZKT1": {"viszonylat": 1, "indulas": "Szeged plaza", "erkezes": "Szeged vasútállomás", "menetido": 33, "varos": "Szeged"},
            "SZKT2": {"viszonylat": 2, "indulas": "Európa liget", "erkezes": "Szeged vasútállomás", "menetido": 33, "varos": "Szeged"},
}

orszag= {
    "Albánia": "Tirana","Andorra": "Andorra város", "Ausztria": "Bécs", "Belgium": "Brüsszel",
    "Bosznia és Hercegovina": "Szarajevó",  "Bulgária": "Szófia",  "Ciprus": "Nicosia",
    "Csehország": "Prága",  "Dánia": "Koppenhága", "Észtország": "Tallinn", "Finnország": "Helsinki",
    "Franciaország": "Párizs", "Görögország": "Athén", "Horvátország": "Zágráb", "Izland": "Reykjavík",
    "Írország": "Dublin", "Koszovó": "Pristina", "Lengyelország": "Varsó", "Lettország": "Riga",
    "Liechtenstein": "Vaduz",  "Litvánia": "Vilnius",  "Luxemburg": "Luxemburg",
    "Magyarország": "Budapest",  "Málta": "Valletta",  "Moldova": "Kisinyov",  "Monaco": "Monaco",
    "Montenegró": "Podgorica", "Németország": "Berlin", "Norvégia": "Oslo", "Olaszország": "Róma",
    "Portugália": "Lisszabon", "Románia": "Bukarest", "San Marino": "San Marino",
    "Spanyolország": "Madrid", "Svájc": "Bern",  "Svédország": "Stockholm",  "Szlovákia": "Pozsony",
    "Szlovénia": "Ljubljana", "Törökország": "Ankara", "Ukrajna": "Kijev", "Vatikán": "Vatikánváros"
}

def szotarbol_veletlen_kulcs(szotar, n):
    """
        szotar (dict): A szótár, amelyből véletlenszerűen választunk kulcsokat.
        n (int): A választandó kulcsok száma.
    """
    kulcsok = list(szotar.keys())
    veletlen_kulcsok = []
    for i in range(n):
        kulcs_index = hash(str(i)) % len(kulcsok)
        veletlen_kulcs = kulcsok[kulcs_index]
        veletlen_kulcsok.append(veletlen_kulcs)
    return veletlen_kulcsok

def tordel(lst, n=None):  # lst = kiírandó lista, n = hany kerüljön  egy sorba
    if n is None:
        n = 10
    for i in range(0, len(lst), n):
        row = lst[i:i+n]
        print(", ".join(map(str, row)), end=", ")
        print()

def ftordel(lst, n=None, indent=None):
    if n is None:
        n = 10
    if indent is None:
        indent = ''
    tordelt_sorok = []
    for i in range(0, len(lst), n):
        row = lst[i:i+n]
        tordelt_sorok.append(f"{indent}{', '.join(map(str, row))}")
    return "\n".join(tordelt_sorok)

ABECEDARAK = 'aábcdeéfghiíjklmnoóöőpqrstuúüűvwxyz'
def abc(lista):
    return sorted(lista, key=lambda s: [ABECEDARAK.find(c) for c in s.lower()])

def fel_kerekit(szam):
    if szam % 1 == 0:
        return int(szam)
    else:
        return int(szam) + 1

def le_kerekit(szam):
    return int(szam // 1)
