# coding: utf-8

"""
    Netilion API Documentation

    Welcome to the Netilion API Documentation, which provides interactive access and documentation to our REST API.  This section contains new endpoints which are still under development. You're welcome to test them but please note that they still can change anytime!   # noqa: E501

    OpenAPI spec version: 01.00.00
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CertificateRenewalResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'certificate': 'str'
    }

    attribute_map = {
        'status': 'status',
        'certificate': 'certificate'
    }

    def __init__(self, status=None, certificate=None):  # noqa: E501
        """CertificateRenewalResponse - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._certificate = None
        self.discriminator = None
        self.status = status
        if certificate is not None:
            self.certificate = certificate

    @property
    def status(self):
        """Gets the status of this CertificateRenewalResponse.  # noqa: E501

        The status of the certificate renewal process. \"renewal\" is requesting a new csr (base64 encoded, containing the serial number as CN=MySerialNumber) from the connected asset. \"replace\" indicates that a new certificate is present in the response to be picked up.  # noqa: E501

        :return: The status of this CertificateRenewalResponse.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CertificateRenewalResponse.

        The status of the certificate renewal process. \"renewal\" is requesting a new csr (base64 encoded, containing the serial number as CN=MySerialNumber) from the connected asset. \"replace\" indicates that a new certificate is present in the response to be picked up.  # noqa: E501

        :param status: The status of this CertificateRenewalResponse.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def certificate(self):
        """Gets the certificate of this CertificateRenewalResponse.  # noqa: E501

        A base64-encoded PEM certificate that was created for the connected asset, returned only with status \"replace\".  # noqa: E501

        :return: The certificate of this CertificateRenewalResponse.  # noqa: E501
        :rtype: str
        """
        return self._certificate

    @certificate.setter
    def certificate(self, certificate):
        """Sets the certificate of this CertificateRenewalResponse.

        A base64-encoded PEM certificate that was created for the connected asset, returned only with status \"replace\".  # noqa: E501

        :param certificate: The certificate of this CertificateRenewalResponse.  # noqa: E501
        :type: str
        """

        self._certificate = certificate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CertificateRenewalResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CertificateRenewalResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
