
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-16T10:52:51+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "b56b81654029b2143529ffc0640d6159b8be90fa",
 "version": "2.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
