facesDict = { 
# Emoji    Discord             ios
  '🙂' : [':slight_smile:',   'slightly smiling face'],
  '🙃' : [':upside_down:',    'upside down face'],
  '😊' : [':blush:',          'smiling face with smiling eyes'],
  '😆' : [':laughing:',       'grinning squinting face'],
  '😉' : [':wink:',           'winking face'],
  '😏' : [':smirk:',          'smirking face'],
  '😅' : [':sweat_smile:',    'grinning face with sweat'],
  '🥺' : [':pleading_face:',  'pleading face'],
  '😇' : [':innocent:',       'smiling face with halo'],
  '😐' : [':neutral_face:',   'neutral face'],
  '😑' : [':expressionless:', 'expressionless face'],
  '🥳' : [':partying face:',  'party face'],
  '😴' : [':sleeping:',       'sleeping face'],
  '🥵' : [':hot_face:',       'hot face'],
  '🤯' : ['exploding_head',   'exploding head'],
  '🤓' : [':nerd:',           'smiling face with glasses'],
  '😭' : [':sob:',            'loudly crying face'],
  '🫠 ': ['n/a',              'melting face'],
  '🤣' : [':rofl:',           'rolling on the floor laughing face'],
  '😤' : [':triumph:',        'face with steam from nose'],
  '😈' : [':smiling_imp:',    'smiling face with horns'],
  '👀' : [':eyes:',           'eyes'],
}
# '' : ['::', ''],