
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-15T18:49:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b1eae28c1ee83837878bb4ec37f49af3ca2a309",
 "version": "0.0.8.dev20230516"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
