from typing import Text, Any, Union
from pygim.typing import PathLike

def write_bytes(filename: PathLike, data: bytes, *, make_dirs: bool = ..., suffix: Text = ...) -> None: ...
def pickle_and_compress(
    obj: Any, filename: PathLike = ..., *, make_dirs: bool = ..., suffix: Text = ...
) -> bytes: ...
def decompress_and_unpickle(obj: Union[bytes, PathLike]) -> Any: ...
