from typing import Iterator, Text, Any, Optional, Iterable
from pygim.typing import PathLike

def measure_coverage(*, include: Optional[PathLike] = ..., show_missing: bool = ...) -> Iterator[None]: ...
def run_tests(
    test_file: PathLike, module_name: Text, pytest_args: Iterable[Any] = ..., *, coverage: bool = ...
) -> None: ...
