# Generated by Django 3.2.7 on 2022-03-28 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploaded_material", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="user",
            field=models.ForeignKey(
                help_text="The user who uploaded the material.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
