# Generated by Django 3.2.15 on 2022-11-09 11:47

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploaded_material", "0010_auto_20220923_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="upload_material",
            field=private_storage.fields.PrivateFileField(
                blank=True,
                help_text="You can upload a file instead of inserting an external URL.",
                max_length=1000,
                null=True,
                storage=private_storage.storage.files.PrivateFileSystemStorage(),
                upload_to="media/",
            ),
        ),
    ]
