BB BBBBBBBBBBBBBBBBB
    XXXXXXBB BBBBBBBBBBBBBBB XXXXXXBBBBB XXXXXXXXXXX XXXXXXXXXXXX XXXXXXX XXXXXX
BBBBB
        XXXXXX XXXXXXX XXXXXXXBB BBBBBBBBBBBB BB BBBB XXXXXXXXBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXXXXXXXXX XXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
BB BBBBBBBBBBBBBBBBB 
    XXXXXXXX
BBBBB
