BBBB BBBBBB BBBBBBBBBBBBBBB

XXXXXX XXXXXXX XXXXXXXBB BBBBBBBBBBBB BB BBBB XXXXXXXXBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
BB BBBBBBBBBBBB BB BBBB
    FFFFFFFFFFFFFFFFFFFFFFFFFFF
BBBB
    FFFFFFFFFFFFFFFFFFFFFFFFFFF
BBBBB

XXXXXXXX
    XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXXXXXX X
        XXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXX
        XXX XX

        XXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXX X XX XX X
                X X XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXX X
                    XXX XXX X XX XX XXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXX
                X XXXX X
                    XXX XXX X X XXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
                X
                XXXXX XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
        XXX

    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX