# Generated by Django 3.2.7 on 2022-05-13 19:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="secret_uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                help_text="A field that is used to create unique webpush tokens.",
            ),
        ),
    ]
