# Generated by Django 4.0.2 on 2023-05-14 15:07

from ..orm import fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moarcframework', '0004_attachment_mimetype_alter_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=fields.IntegerField(default=0, verbose_name='Tamaño del archivo'),
        ),
    ]
