# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.1.dev24+gda03843.d20230511'
__version_tuple__ = version_tuple = (0, 2, 1, 'dev24', 'gda03843.d20230511')
