# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ho_protocols/live/system.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eho_protocols/live/system.proto\x12\x0eho.live.system\"\xd7\x01\n\x0eSystemLiveItem\x12/\n\ncore_stats\x18\x01 \x01(\x0b\x32\x19.ho.live.system.CoreStatsH\x00\x12+\n\x08\x63ore_pwr\x18\x02 \x01(\x0b\x32\x17.ho.live.system.CorePwrH\x00\x12\x32\n\x0c\x63ore_ip_addr\x18\x03 \x01(\x0b\x32\x1a.ho.live.system.CoreIPAddrH\x00\x12+\n\x08\x63ore_rht\x18\x04 \x01(\x0b\x32\x17.ho.live.system.CoreRhtH\x00\x42\x06\n\x04type\"\xc1\x01\n\tCoreStats\x12\x12\n\ndisk_total\x18\x01 \x01(\x03\x12\x11\n\tdisk_used\x18\x02 \x01(\x03\x12\x11\n\tdisk_free\x18\x03 \x01(\x03\x12\x0f\n\x07load_1m\x18\x04 \x01(\x02\x12\x0f\n\x07load_5m\x18\x05 \x01(\x02\x12\x10\n\x08load_15m\x18\x06 \x01(\x02\x12\x11\n\tmem_total\x18\x07 \x01(\x03\x12\x10\n\x08mem_used\x18\x08 \x01(\x03\x12\x11\n\tmem_avail\x18\t \x01(\x03\x12\x0e\n\x06uptime\x18\n \x01(\x02\"X\n\x07\x43orePwr\x12\t\n\x01v\x18\x01 \x01(\x02\x12\x0f\n\x07v_shunt\x18\x02 \x01(\x02\x12\r\n\x05power\x18\x03 \x01(\x02\x12\x0f\n\x07\x63urrent\x18\x04 \x01(\x02\x12\x11\n\tcurr_avg3\x18\x05 \x01(\x02\"c\n\nCoreIPAddr\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.ho.live.system.CoreIPAddr.Item\x1a%\n\x04Item\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\"1\n\x07\x43oreRht\x12\x11\n\trel_humid\x18\x01 \x01(\x02\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x42\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ho_protocols.live.system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _globals['_SYSTEMLIVEITEM']._serialized_start=51
  _globals['_SYSTEMLIVEITEM']._serialized_end=266
  _globals['_CORESTATS']._serialized_start=269
  _globals['_CORESTATS']._serialized_end=462
  _globals['_COREPWR']._serialized_start=464
  _globals['_COREPWR']._serialized_end=552
  _globals['_COREIPADDR']._serialized_start=554
  _globals['_COREIPADDR']._serialized_end=653
  _globals['_COREIPADDR_ITEM']._serialized_start=616
  _globals['_COREIPADDR_ITEM']._serialized_end=653
  _globals['_CORERHT']._serialized_start=655
  _globals['_CORERHT']._serialized_end=704
# @@protoc_insertion_point(module_scope)
