# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ControlOut.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43ontrolOut.proto\x12\x11\x63om.loorr.message\"R\n\nControlOut\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\x12\x11\n\teventType\x18\x02 \x01(\t\x12\x11\n\terrorCode\x18\x03 \x01(\r\x12\x10\n\x08\x65rrorMsg\x18\x04 \x01(\tB\x13\x42\x0f\x43ontrolOutProtoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ControlOut_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\017ControlOutProtoP\001'
  _CONTROLOUT._serialized_start=39
  _CONTROLOUT._serialized_end=121
# @@protoc_insertion_point(module_scope)
