# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/polvosetups',
                'doc_host': 'https://lgvaz.github.io',
                'git_url': 'https://github.com/lgvaz/polvosetups',
                'lib_path': 'polvosetups'},
  'syms': { 'polvosetups.core': { 'polvosetups.core.SetupTools': ('core.html#setuptools', 'polvosetups/core.py'),
                                  'polvosetups.core.SetupTools.__init__': ('core.html#setuptools.__init__', 'polvosetups/core.py'),
                                  'polvosetups.core.bash': ('core.html#bash', 'polvosetups/core.py'),
                                  'polvosetups.core.controlnet': ('core.html#controlnet', 'polvosetups/core.py'),
                                  'polvosetups.core.deepfloydif': ('core.html#deepfloydif', 'polvosetups/core.py'),
                                  'polvosetups.core.git_clone': ('core.html#git_clone', 'polvosetups/core.py'),
                                  'polvosetups.core.jupyter': ('core.html#jupyter', 'polvosetups/core.py'),
                                  'polvosetups.core.main': ('core.html#main', 'polvosetups/core.py'),
                                  'polvosetups.core.miniconda': ('core.html#miniconda', 'polvosetups/core.py'),
                                  'polvosetups.core.mkdir': ('core.html#mkdir', 'polvosetups/core.py'),
                                  'polvosetups.core.polvo_suite': ('core.html#polvo_suite', 'polvosetups/core.py'),
                                  'polvosetups.core.test': ('core.html#test', 'polvosetups/core.py')}}}
