from setuptools import setup

setup(name="cluseek",
    version="1.0",
    description="A GUI application for the discovery and analysis of gene clusters.",
    url="",
    author="Hreb",
    author_email="hrebiceo@gmail.com",
    license="MIT",
    packages=["cluseek"],
    install_requires=[
    "altgraph==0.17.2",
    "biopython==1.79",
    "cycler==0.11.0",
    "et-xmlfile==1.1.0",
    "fonttools==4.37.1",
    "future==0.18.2",
    "kiwisolver==1.4.4",
    "matplotlib==3.5.3",
    "numpy==1.23.3",
    "openpyxl==3.0.10",
    "packaging==21.3",
    "pefile==2022.5.30",
    "Pillow==9.2.0",
    "pip-licenses==4.0.1",
    "prettytable==3.5.0",
    "pyinstaller==5.4.1",
    "pyinstaller-hooks-contrib==2022.10",
    "pyparsing==3.0.9",
    "PySide2==5.15.2.1",
    "python-dateutil==2.8.2",
    "pywin32-ctypes==0.2.0",
    "scipy==1.9.1",
    "shiboken2==5.15.2.1",
    "six==1.16.0",
    "wcwidth==0.2.5"],
    entry_points = {
        "console_scripts": ["cluseek=cluseek.__main__:main"]
    },
    zip_safe=False,
    include_package_data=True)