"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import ho_protocols.alert.bees_pb2
import ho_protocols.alert.system_pb2
import ho_protocols.common_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class AlertMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    SYSTEM_FIELD_NUMBER: builtins.int
    BEES_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> ho_protocols.common_pb2.Header: ...
    @property
    def system(self) -> ho_protocols.alert.system_pb2.SystemAlert: ...
    @property
    def bees(self) -> ho_protocols.alert.bees_pb2.BeesAlert: ...
    def __init__(
        self,
        *,
        header: ho_protocols.common_pb2.Header | None = ...,
        system: ho_protocols.alert.system_pb2.SystemAlert | None = ...,
        bees: ho_protocols.alert.bees_pb2.BeesAlert | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["bees", b"bees", "header", b"header", "payload", b"payload", "system", b"system"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bees", b"bees", "header", b"header", "payload", b"payload", "system", b"system"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["payload", b"payload"]) -> typing_extensions.Literal["system", "bees"] | None: ...

global___AlertMessage = AlertMessage
