
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-17T11:18:57-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "26ce5cf0d34b65514223967ffc0628d0b5031d05",
 "version": "2.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
