
BIBSTER_PUBLICATIONS_QUERY_FORM_CLASSNAME = ""
BIBSTER_PUBLICATION_LAYOUT_BLOCK_CLASSNAME = ""
BIBSTER_PUBLICATION_LIST_BLOCK_CLASSNAME = ""
BIBSTER_PUBLICATION_LIST_CONTENT_WRAPPER_CLASSNAME = ""
BIBSTER_PUBLICATION_CONTAINER_CLASSNAME = "pubref-container"
BIBSTER_PUBLICATION_TAGS_CLASSNAME = "pubref-tags"
BIBSTER_PUBLICATION_TAG_CLASSNAME = "pubref-tag"
BIBSTER_PUBLICATION_SUMMARY_CLASSNAME = "pubref-summary"
