
JOURNAL_ARTICLE_LABEL = "Journal Article"
PREPRINT_ARTICLE_LABEL = "Preprint Article"
BOOK_CHAPTER_LABEL = "Book Chapter"
BOOK_LABEL = "Book"
PROCEEDINGS_ARTICLE_LABEL = "Proceedings Article"
PUBLISHED_STANDARD_LABEL = "Published Standard"
PATENT_LABEL = "Patent"
REPORT_LABEL = "Report"
MAP_LABEL = "Map"
WEBSITE_LABEL = "Website"


JOURNAL_ARTICLE_REFERENCE = "journal_article"
PREPRINT_ARTICLE_REFERENCE = "preprint_article"
BOOK_CHAPTER_REFERENCE = "book_chapter"
BOOK_REFERENCE = "book"
PROCEEDINGS_ARTICLE_REFERENCE = "proceedings_article"
PUBLISHED_STANDARD_REFERENCE = "published_standard"
PATENT_REFERENCE = "patent"
REPORT_REFERENCE = "report"
MAP_REFERENCE = "map"
WEBSITE_REFERENCE = "website"


AUTHOR_ROLE = 'author'
EDITOR_ROLE = 'editor'
INVENTOR_ROLE = 'inventor'

ROLES = (AUTHOR_ROLE, EDITOR_ROLE, INVENTOR_ROLE)
ROLE_CHOICES = ((AUTHOR_ROLE, "Author"), (EDITOR_ROLE, "Editor"), (INVENTOR_ROLE, "Inventor"))
AUTHOR_OR_EDITOR_ROLE_CHOICES = (

    (AUTHOR_ROLE, "Author"),
    (EDITOR_ROLE, "Editor"),
)

AUTHOR_ROLE_CHOICES = (

    (AUTHOR_ROLE, "Author"),
)

EDITOR_ROLE_CHOICES = (

    (EDITOR_ROLE, "Editor"),
)

INVENTOR_ROLE_CHOICES = (

    (INVENTOR_ROLE, "Inventor"),
)



UNKNOWN_PUBLICATION_STATUS = "unknown_publication_status"
SUBMITTED_PUBLICATION_STATUS = "submitted_publication_status"
TO_BE_PUBLISHED_PUBLICATION_STATUS = "to_be_published_publication_status"


UNKNOWN_PUBLICATION_STATUS_LABEL = "Unknown"
SUBMITTED_PUBLICATION_STATUS_LABEL = "Submitted"
TO_BE_PUBLISHED_PUBLICATION_STATUS_LABEL = "To be published"

PUBLICATION_STATUS_CHOICES = (
    (UNKNOWN_PUBLICATION_STATUS, UNKNOWN_PUBLICATION_STATUS_LABEL),
    (SUBMITTED_PUBLICATION_STATUS, SUBMITTED_PUBLICATION_STATUS_LABEL),
    (TO_BE_PUBLISHED_PUBLICATION_STATUS, TO_BE_PUBLISHED_PUBLICATION_STATUS_LABEL)
)


HARVARD_STYLE = "harvard"
HARVARD_LABEL_STYLE = "harvard_label"

DEFAULT_STYLE = HARVARD_STYLE
DEFAULT_LABEL_STYLE = HARVARD_LABEL_STYLE
