from bytez.tasks.style_transfer._models.cmd_style_transfer import CmdStyleTransferModel
from bytez.tasks.style_transfer._models.fast_style_transfer import FastStyleTransferModel
from bytez.tasks.style_transfer._models.tensorflow_fast_style import TensorFlowFastStyleTransferModel
