
RUMINATE_ARTICLE_PAGE_TEMPLATE = "ruminate/base_page.html"

RUMINATE_ARTICLE_BLOCK_CLASSNAME = ""
RUMINATE_NONE_INTRO_BLOCK_CLASSNAME = "intro-none"
RUMINATE_MINIMAL_INTRO_BLOCK_CLASSNAME = "intro-minimal"
RUMINATE_SPREAD_INTRO_BLOCK_CLASSNAME = "intro-spread"

RUMINATE_ARTICLE_BOILERPLATE_BLOCK_CLASSNAME = ""
RUMINATE_ARTICLE_BLOCK_TABS_CLASSNAME = ""
RUMINATE_ARTICLE_BLOCK_CONTENT_CLASSNAME = ""
RUMINATE_ARTICLE_BLOCK_PARTS_CLASSNAME = ""

RUMINATE_ARTICLE_TAGS_BLOCK_CLASSNAME = "keywords-list"
RUMINATE_ARTICLE_TAGS_BLOCK_CONTAINER_ELEMENT = "div"
RUMINATE_ARTICLE_TAGS_BLOCK_TAG_CLASSNAME = "tag"

RUMINATE_ARTICLE_BOILERPLATE_AUTHOR_VISUAL_SCALE_FACTOR = 0.33

RUMINATE_ARTICLE_BLOCK_AUTHORS_CLASSNAME = "author-list"
RUMINATE_ARTICLE_INDEX_REDIRECT_TARGET = ""
RUMINATE_ARTICLE_INDEX_NOT_ACCESSIBLE = True
