# Generated by Django 4.1.7 on 2023-05-04 10:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='humansImages/default.webp', upload_to='humansImages/', verbose_name='Your humans image')),
                ('name', models.TextField(null=True)),
                ('smallDescription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('isPublished', models.BooleanField(default=False, null=True)),
                ('customSlug', models.TextField(unique=True, verbose_name='Custom slug')),
                ('websiteUrl', models.URLField(null=True)),
                ('linkedInUrl', models.URLField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Humans',
            },
        ),
    ]
