# Generated by Django 4.1.7 on 2023-05-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='position',
            field=models.TextField(null=True),
        ),
    ]
