# Generated by Django 4.1.7 on 2023-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humans', '0002_human_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='twitterUrl',
            field=models.URLField(null=True),
        ),
    ]
