# Generated by Django 3.2.7 on 2022-02-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic_community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalnamelink",
            name="get_params",
            field=models.CharField(
                blank=True,
                help_text="Any additional query parameters that you want to append to the Link after a <i>?</i> sign.",
                max_length=400,
                null=True,
                verbose_name="Query Parameters",
            ),
        ),
    ]
