MAPPING = {
    "Titolo": "sgtt",
    "Integrazione del titolo": "sgtt_ext",
    "Luogo della ripresa (collegamento ad Authority luogo)": "place_id",
    "Visibile (pubblicato)": "published",
    "Datazione DA anno": "year_from",
    "Datazione DA giorno": "day_from",
    "Datazione DA mese": "month_from",
    "Datazione A anno": "year_to",
    "Segnatura": "signature",
    "Note": "note",
    "Note interne (CAMPO DA AGGIUNGERE)": "note_internal",
    "Copyright": "copyright",
    "Orientamento": "is_horizontal",
    "Tipologia specifica": "ogtd_id",
    "Tipologia supporto": "medium_id",
    "Quantità supporto": "num_support",
    "Cromatismo": "mtx_id",
    "Larghezza": "misl",
    "Altezza": "misa",
    "Collocazione": "placing",
    "Stato di conservazione": "stcc",
    "Abstract": "abstract",
    "Misure fotografia digitale in pixel": "file_pixels",
    "Originale": "is_original",
    "Danni": "stcc_d_id",
    "Note sulla conservazione": "note_conservation",
    "Responsabilità (collegamento ad Authority persona)": "responsability"
}