
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-16T04:27:33+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c741c34deb00ac7c7f438f6fa4ff379ec1d7f010",
 "version": "1.18.4.post0.dev45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
