
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-15T15:28:45+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eef43e965bd7a7e6c1040b03b819c6aa49e52c7d",
 "version": "v4.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
