
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-11-07T08:05:59-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "37792e03321558cfbc175741c485e45fc828154c",
 "version": "v4.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
