
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-16T15:31:36-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "d93c54611ec612f3854442eab476dffbc51af090",
 "version": "2.13.1b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
