
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-17T12:32:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "846bc8c4b86bd291739ba77ddf7e42314e0e2028",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
