# Generated by Django 3.2.15 on 2022-09-18 15:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploaded_material", "0006_communitymateriallistpluginmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                help_text="The uuid of the material",
            ),
        ),
    ]
