# Generated by Django 3.2.15 on 2023-02-01 08:18

from django.db import migrations

import academic_community.ckeditor5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("uploaded_material", "0011_alter_material_upload_material"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="content",
            field=academic_community.ckeditor5.fields.CKEditor5Field(
                blank=True, help_text="The content of the material.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="description",
            field=academic_community.ckeditor5.fields.CKEditor5Field(
                blank=True,
                help_text="Further description on the material.",
                max_length=20000,
                null=True,
            ),
        ),
    ]
