# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: value.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2

from google.protobuf.timestamp_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='value.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bvalue.proto\x12\x08protobuf\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x02\n\x05Value\x12\x14\n\nnone_value\x18\x01 \x01(\x08H\x00\x12\x15\n\x0b\x62ytes_value\x18\x02 \x01(\x0cH\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x13\n\tint_value\x18\x04 \x01(\x05H\x00\x12\x14\n\nlong_value\x18\x05 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x06 \x01(\x01H\x00\x12\x15\n\x0b\x66loat_value\x18\x07 \x01(\x02H\x00\x12\x17\n\rboolean_value\x18\x08 \x01(\x08H\x00\x12\x35\n\x0ftimestamp_value\x18\t \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x12-\n\x0cvector_value\x18\n \x01(\x0b\x32\x15.protobuf.VectorValueH\x00\x12\'\n\tmap_value\x18\x0b \x01(\x0b\x32\x12.protobuf.MapValueH\x00\x42\x0c\n\nValueOneOf\".\n\x0bVectorValue\x12\x1f\n\x06values\x18\x01 \x03(\x0b\x32\x0f.protobuf.Value\"J\n\x08MapValue\x12\x1d\n\x04keys\x18\x01 \x03(\x0b\x32\x0f.protobuf.Value\x12\x1f\n\x06values\x18\x02 \x03(\x0b\x32\x0f.protobuf.ValueP\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,],
  public_dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='protobuf.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='none_value', full_name='protobuf.Value.none_value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytes_value', full_name='protobuf.Value.bytes_value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='protobuf.Value.string_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='protobuf.Value.int_value', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='long_value', full_name='protobuf.Value.long_value', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='double_value', full_name='protobuf.Value.double_value', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='protobuf.Value.float_value', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boolean_value', full_name='protobuf.Value.boolean_value', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_value', full_name='protobuf.Value.timestamp_value', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vector_value', full_name='protobuf.Value.vector_value', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map_value', full_name='protobuf.Value.map_value', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='ValueOneOf', full_name='protobuf.Value.ValueOneOf',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=59,
  serialized_end=407,
)


_VECTORVALUE = _descriptor.Descriptor(
  name='VectorValue',
  full_name='protobuf.VectorValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='protobuf.VectorValue.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=409,
  serialized_end=455,
)


_MAPVALUE = _descriptor.Descriptor(
  name='MapValue',
  full_name='protobuf.MapValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='protobuf.MapValue.keys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='values', full_name='protobuf.MapValue.values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=457,
  serialized_end=531,
)

_VALUE.fields_by_name['timestamp_value'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_VALUE.fields_by_name['vector_value'].message_type = _VECTORVALUE
_VALUE.fields_by_name['map_value'].message_type = _MAPVALUE
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['none_value'])
_VALUE.fields_by_name['none_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['bytes_value'])
_VALUE.fields_by_name['bytes_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['string_value'])
_VALUE.fields_by_name['string_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['int_value'])
_VALUE.fields_by_name['int_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['long_value'])
_VALUE.fields_by_name['long_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['double_value'])
_VALUE.fields_by_name['double_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['float_value'])
_VALUE.fields_by_name['float_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['boolean_value'])
_VALUE.fields_by_name['boolean_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['timestamp_value'])
_VALUE.fields_by_name['timestamp_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['vector_value'])
_VALUE.fields_by_name['vector_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VALUE.oneofs_by_name['ValueOneOf'].fields.append(
  _VALUE.fields_by_name['map_value'])
_VALUE.fields_by_name['map_value'].containing_oneof = _VALUE.oneofs_by_name['ValueOneOf']
_VECTORVALUE.fields_by_name['values'].message_type = _VALUE
_MAPVALUE.fields_by_name['keys'].message_type = _VALUE
_MAPVALUE.fields_by_name['values'].message_type = _VALUE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['VectorValue'] = _VECTORVALUE
DESCRIPTOR.message_types_by_name['MapValue'] = _MAPVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'value_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.Value)
  })
_sym_db.RegisterMessage(Value)

VectorValue = _reflection.GeneratedProtocolMessageType('VectorValue', (_message.Message,), {
  'DESCRIPTOR' : _VECTORVALUE,
  '__module__' : 'value_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.VectorValue)
  })
_sym_db.RegisterMessage(VectorValue)

MapValue = _reflection.GeneratedProtocolMessageType('MapValue', (_message.Message,), {
  'DESCRIPTOR' : _MAPVALUE,
  '__module__' : 'value_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.MapValue)
  })
_sym_db.RegisterMessage(MapValue)


# @@protoc_insertion_point(module_scope)
