# Generated by Django 3.2.7 on 2022-04-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_registration_detail_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="register_presenters",
            field=models.BooleanField(
                default=False,
                help_text="Automatically register presenters when an abstract is submitted. Note that presenters can only be registered, when they already logged in once into the website. If you expect members from outside the community, you should disable this option.",
            ),
        ),
    ]
