
BE_BRIEF_POST_PAGE_TEMPLATE = "be_brief/base_page.html"

BE_BRIEF_RECORD_BLOCK_CLASSNAME = ""
BE_BRIEF_RECORD_BLOCK_AUTHORS_CLASSNAME = "author-list"

BE_BRIEF_POST_INDEX_REDIRECT_TARGET = ""
BE_BRIEF_POST_INDEX_NOT_ACCESSIBLE = True

BE_BRIEF_POST_TAGS_BLOCK_CLASSNAME = "keywords-list"
BE_BRIEF_POST_TAGS_BLOCK_CONTAINER_ELEMENT = "div"
BE_BRIEF_POST_TAGS_BLOCK_TAG_CLASSNAME = "tag"