
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-16T21:05:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c93032cc24d2c63b78bc27ee1228b3b8a60e552f",
 "version": "1.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
