# Generated by Django 3.1.3 on 2021-08-24 14:07


# Disclaimer
# ----------
#
# Copyright (C) 2021 Helmholtz-Zentrum Hereon
# Copyright (C) 2020-2021 Helmholtz-Zentrum Geesthacht
#
# This file is part of django-academic-community and is released under the
# EUPL-1.2 license.
# See LICENSE in the root of the repository for full licensing details.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the EUROPEAN UNION PUBLIC LICENCE v. 1.2 or later
# as published by the European Commission.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# EUPL-1.2 license for more details.
#
# You should have received a copy of the EUPL-1.2 license along with this
# program. If not, see https://www.eupl.eu/.


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_auto_20210528_1324"),
        ("institutions", "0003_auto_20210424_1438"),
        ("programme", "0003_auto_20210622_1937"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="organization",
            field=models.OneToOneField(
                blank=True,
                help_text="The corresponding academic organization in the CLM-Community",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institutions.academicorganization",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="member",
            field=models.OneToOneField(
                blank=True,
                help_text="The corresponding community member.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="members.communitymember",
            ),
        ),
    ]
