# Generated by Django 3.2.7 on 2022-05-23 11:17

import djangocms_text_ckeditor.fields
from django.db import migrations

import academic_community.validators


class Migration(migrations.Migration):

    dependencies = [
        ("programme", "0018_presentationtype_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="abstract",
            field=djangocms_text_ckeditor.fields.HTMLField(
                help_text="Please provide an abstract (max. 4000 characters)",
                max_length=15000,
                validators=[
                    academic_community.validators.HTMLMaxLengthValidator(4000)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="abstract",
            field=djangocms_text_ckeditor.fields.HTMLField(
                blank=True,
                help_text="Please provide an abstract (max. 4000 characters)",
                max_length=15000,
                null=True,
                validators=[
                    academic_community.validators.HTMLMaxLengthValidator(4000)
                ],
            ),
        ),
    ]
