emojies = [
    ("GRINNING FACE", "😀"),
    ("SMILING FACE WITH OPEN MOUTH", "😃"),
    ("SMILING FACE WITH OPEN MOUTH AND SMILING EYES", "😄"),
    ("GRINNING FACE WITH SMILING EYES", "😁"),
    ("SMILING FACE WITH OPEN MOUTH AND TIGHTLY-CLOSED EYES", "😆"),
    ("SMILING FACE WITH OPEN MOUTH AND COLD SWEAT", "😅"),
    ("ROLLING ON THE FLOOR LAUGHING", "🤣"),
    ("FACE WITH TEARS OF JOY", "😂"),
    ("SLIGHTLY SMILING FACE", "🙂"),
    ("UPSIDE-DOWN FACE", "🙃"),
    ("WINKING FACE", "😉"),
    ("SMILING FACE WITH SMILING EYES", "😊"),
    ("SMILING FACE WITH HALO", "😇"),
    ("SMILING FACE WITH SMILING EYES AND THREE HEARTS", "🥰"),
    ("SMILING FACE WITH HEART-SHAPED EYES", "😍"),
    ("GRINNING FACE WITH STAR EYES", "🤩"),
    ("FACE THROWING A KISS", "😘"),
    ("KISSING FACE", "😗"),
    ("KISSING FACE WITH CLOSED EYES", "😚"),
    ("KISSING FACE WITH SMILING EYES", "😙"),
    ("SMILING FACE WITH TEAR", "🥲"),
    ("FACE SAVOURING DELICIOUS FOOD", "😋"),
    ("FACE WITH STUCK-OUT TONGUE", "😛"),
    ("FACE WITH STUCK-OUT TONGUE AND WINKING EYE", "😜"),
    ("GRINNING FACE WITH ONE LARGE AND ONE SMALL EYE", "🤪"),
    ("FACE WITH STUCK-OUT TONGUE AND TIGHTLY-CLOSED EYES", "😝"),
    ("MONEY-MOUTH FACE", "🤑"),
    ("HUGGING FACE", "🤗"),
    ("SMILING FACE WITH SMILING EYES AND HAND COVERING MOUTH", "🤭"),
    ("FACE WITH FINGER COVERING CLOSED LIPS", "🤫"),
    ("THINKING FACE", "🤔"),
    ("ZIPPER-MOUTH FACE", "🤐"),
    ("FACE WITH ONE EYEBROW RAISED", "🤨"),
    ("NEUTRAL FACE", "😐"),
    ("EXPRESSIONLESS FACE", "😑"),
    ("FACE WITHOUT MOUTH", "😶"),
    ("SMIRKING FACE", "😏"),
    ("UNAMUSED FACE", "😒"),
    ("FACE WITH ROLLING EYES", "🙄"),
    ("GRIMACING FACE", "😬"),
    ("LYING FACE", "🤥"),
    ("RELIEVED FACE", "😌"),
    ("PENSIVE FACE", "😔"),
    ("SLEEPY FACE", "😪"),
    ("DROOLING FACE", "🤤"),
    ("SLEEPING FACE", "😴"),
    ("FACE WITH MEDICAL MASK", "😷"),
    ("FACE WITH THERMOMETER", "🤒"),
    ("FACE WITH HEAD-BANDAGE", "🤕"),
    ("NAUSEATED FACE", "🤢"),
    ("FACE WITH OPEN MOUTH VOMITING", "🤮"),
    ("SNEEZING FACE", "🤧"),
    ("OVERHEATED FACE", "🥵"),
    ("FREEZING FACE", "🥶"),
    ("FACE WITH UNEVEN EYES AND WAVY MOUTH", "🥴"),
    ("DIZZY FACE", "😵"),
    ("SHOCKED FACE WITH EXPLODING HEAD", "🤯"),
    ("FACE WITH COWBOY HAT", "🤠"),
    ("FACE WITH PARTY HORN AND PARTY HAT", "🥳"),
    ("DISGUISED FACE", "🥸"),
    ("SMILING FACE WITH SUNGLASSES", "😎"),
    ("NERD FACE", "🤓"),
    ("FACE WITH MONOCLE", "🧐"),
    ("CONFUSED FACE", "😕"),
    ("WORRIED FACE", "😟"),
    ("SLIGHTLY FROWNING FACE", "🙁"),
    ("FACE WITH OPEN MOUTH", "😮"),
    ("HUSHED FACE", "😯"),
    ("ASTONISHED FACE", "😲"),
    ("FLUSHED FACE", "😳"),
    ("FACE WITH PLEADING EYES", "🥺"),
    ("FROWNING FACE WITH OPEN MOUTH", "😦"),
    ("ANGUISHED FACE", "😧"),
    ("FEARFUL FACE", "😨"),
    ("FACE WITH OPEN MOUTH AND COLD SWEAT", "😰"),
    ("DISAPPOINTED BUT RELIEVED FACE", "😥"),
    ("CRYING FACE", "😢"),
    ("LOUDLY CRYING FACE", "😭"),
    ("FACE SCREAMING IN FEAR", "😱"),
    ("CONFOUNDED FACE", "😖"),
    ("PERSEVERING FACE", "😣"),
    ("DISAPPOINTED FACE", "😞"),
    ("FACE WITH COLD SWEAT", "😓"),
    ("WEARY FACE", "😩"),
    ("TIRED FACE", "😫"),
    ("YAWNING FACE", "🥱"),
    ("FACE WITH LOOK OF TRIUMPH", "😤"),
    ("POUTING FACE", "😡"),
    ("ANGRY FACE", "😠"),
    ("SERIOUS FACE WITH SYMBOLS COVERING MOUTH", "🤬"),
    ("SMILING FACE WITH HORNS", "😈"),
    ("IMP", "👿"),
    ("SKULL", "💀"),
    ("PILE OF POO", "💩"),
    ("CLOWN FACE", "🤡"),
    ("JAPANESE OGRE", "👹"),
    ("JAPANESE GOBLIN", "👺"),
    ("GHOST", "👻"),
    ("EXTRATERRESTRIAL ALIEN", "👽"),
    ("ALIEN MONSTER", "👾"),
    ("ROBOT FACE", "🤖"),
    ("SMILING CAT FACE WITH OPEN MOUTH", "😺"),
    ("GRINNING CAT FACE WITH SMILING EYES", "😸"),
    ("CAT FACE WITH TEARS OF JOY", "😹"),
    ("SMILING CAT FACE WITH HEART-SHAPED EYES", "😻"),
    ("CAT FACE WITH WRY SMILE", "😼"),
    ("KISSING CAT FACE WITH CLOSED EYES", "😽"),
    ("WEARY CAT FACE", "🙀"),
    ("CRYING CAT FACE", "😿"),
    ("POUTING CAT FACE", "😾"),
    ("SEE-NO-EVIL MONKEY", "🙈"),
    ("HEAR-NO-EVIL MONKEY", "🙉"),
    ("SPEAK-NO-EVIL MONKEY", "🙊"),
    ("KISS MARK", "💋"),
    ("LOVE LETTER", "💌"),
    ("HEART WITH ARROW", "💘"),
    ("HEART WITH RIBBON", "💝"),
    ("SPARKLING HEART", "💖"),
    ("GROWING HEART", "💗"),
    ("BEATING HEART", "💓"),
    ("REVOLVING HEARTS", "💞"),
    ("TWO HEARTS", "💕"),
    ("HEART DECORATION", "💟"),
    ("BROKEN HEART", "💔"),
    ("ORANGE HEART", "🧡"),
    ("YELLOW HEART", "💛"),
    ("GREEN HEART", "💚"),
    ("BLUE HEART", "💙"),
    ("PURPLE HEART", "💜"),
    ("BROWN HEART", "🤎"),
    ("BLACK HEART", "🖤"),
    ("WHITE HEART", "🤍"),
    ("HUNDRED POINTS SYMBOL", "💯"),
    ("ANGER SYMBOL", "💢"),
    ("COLLISION SYMBOL", "💥"),
    ("DIZZY SYMBOL", "💫"),
    ("SPLASHING SWEAT SYMBOL", "💦"),
    ("DASH SYMBOL", "💨"),
    ("BOMB", "💣"),
    ("SPEECH BALLOON", "💬"),
    ("THOUGHT BALLOON", "💭"),
    ("SLEEPING SYMBOL", "💤"),
    ("WAVING HAND SIGN", "👋"),
    ("RAISED BACK OF HAND", "🤚"),
    ("RAISED HAND", "✋"),
    ("RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS", "🖖"),
    ("OK HAND SIGN", "👌"),
    ("PINCHED FINGERS", "🤌"),
    ("PINCHING HAND", "🤏"),
    ("HAND WITH INDEX AND MIDDLE FINGERS CROSSED", "🤞"),
    ("I LOVE YOU HAND SIGN", "🤟"),
    ("SIGN OF THE HORNS", "🤘"),
    ("CALL ME HAND", "🤙"),
    ("WHITE LEFT POINTING BACKHAND INDEX", "👈"),
    ("WHITE RIGHT POINTING BACKHAND INDEX", "👉"),
    ("WHITE UP POINTING BACKHAND INDEX", "👆"),
    ("REVERSED HAND WITH MIDDLE FINGER EXTENDED", "🖕"),
    ("WHITE DOWN POINTING BACKHAND INDEX", "👇"),
    ("THUMBS UP SIGN", "👍"),
    ("THUMBS DOWN SIGN", "👎"),
    ("RAISED FIST", "✊"),
    ("FISTED HAND SIGN", "👊"),
    ("LEFT-FACING FIST", "🤛"),
    ("RIGHT-FACING FIST", "🤜"),
    ("CLAPPING HANDS SIGN", "👏"),
    ("PERSON RAISING BOTH HANDS IN CELEBRATION", "🙌"),
    ("OPEN HANDS SIGN", "👐"),
    ("PALMS UP TOGETHER", "🤲"),
    ("HANDSHAKE", "🤝"),
    ("PERSON WITH FOLDED HANDS", "🙏"),
    ("NAIL POLISH", "💅"),
    ("SELFIE", "🤳"),
    ("FLEXED BICEPS", "💪"),
    ("MECHANICAL ARM", "🦾"),
    ("MECHANICAL LEG", "🦿"),
    ("LEG", "🦵"),
    ("FOOT", "🦶"),
    ("EAR", "👂"),
    ("EAR WITH HEARING AID", "🦻"),
    ("NOSE", "👃"),
    ("BRAIN", "🧠"),
    ("ANATOMICAL HEART", "🫀"),
    ("LUNGS", "🫁"),
    ("TOOTH", "🦷"),
    ("BONE", "🦴"),
    ("EYES", "👀"),
    ("TONGUE", "👅"),
    ("MOUTH", "👄"),
    ("BABY", "👶"),
    ("CHILD", "🧒"),
    ("BOY", "👦"),
    ("GIRL", "👧"),
    ("ADULT", "🧑"),
    ("PERSON WITH BLOND HAIR", "👱"),
    ("MAN", "👨"),
    ("BEARDED PERSON", "🧔"),
    ("WOMAN", "👩"),
    ("OLDER ADULT", "🧓"),
    ("OLDER MAN", "👴"),
    ("OLDER WOMAN", "👵"),
    ("PERSON FROWNING", "🙍"),
    ("PERSON WITH POUTING FACE", "🙎"),
    ("FACE WITH NO GOOD GESTURE", "🙅"),
    ("FACE WITH OK GESTURE", "🙆"),
    ("INFORMATION DESK PERSON", "💁"),
    ("HAPPY PERSON RAISING ONE HAND", "🙋"),
    ("DEAF PERSON", "🧏"),
    ("PERSON BOWING DEEPLY", "🙇"),
    ("FACE PALM", "🤦"),
    ("SHRUG", "🤷"),
    ("POLICE OFFICER", "👮"),
    ("GUARDSMAN", "💂"),
    ("NINJA", "🥷"),
    ("CONSTRUCTION WORKER", "👷"),
    ("PRINCE", "🤴"),
    ("PRINCESS", "👸"),
    ("MAN WITH TURBAN", "👳"),
    ("MAN WITH GUA PI MAO", "👲"),
    ("PERSON WITH HEADSCARF", "🧕"),
    ("MAN IN TUXEDO", "🤵"),
    ("BRIDE WITH VEIL", "👰"),
    ("PREGNANT WOMAN", "🤰"),
    ("BREAST-FEEDING", "🤱"),
    ("BABY ANGEL", "👼"),
    ("FATHER CHRISTMAS", "🎅"),
    ("MOTHER CHRISTMAS", "🤶"),
    ("SUPERHERO", "🦸"),
    ("SUPERVILLAIN", "🦹"),
    ("MAGE", "🧙"),
    ("FAIRY", "🧚"),
    ("VAMPIRE", "🧛"),
    ("MERPERSON", "🧜"),
    ("ELF", "🧝"),
    ("GENIE", "🧞"),
    ("ZOMBIE", "🧟"),
    ("FACE MASSAGE", "💆"),
    ("HAIRCUT", "💇"),
    ("PEDESTRIAN", "🚶"),
    ("STANDING PERSON", "🧍"),
    ("KNEELING PERSON", "🧎"),
    ("RUNNER", "🏃"),
    ("DANCER", "💃"),
    ("MAN DANCING", "🕺"),
    ("WOMAN WITH BUNNY EARS", "👯"),
    ("PERSON IN STEAMY ROOM", "🧖"),
    ("PERSON CLIMBING", "🧗"),
    ("FENCER", "🤺"),
    ("HORSE RACING", "🏇"),
    ("SNOWBOARDER", "🏂"),
    ("SURFER", "🏄"),
    ("ROWBOAT", "🚣"),
    ("SWIMMER", "🏊"),
    ("BICYCLIST", "🚴"),
    ("MOUNTAIN BICYCLIST", "🚵"),
    ("PERSON DOING CARTWHEEL", "🤸"),
    ("WRESTLERS", "🤼"),
    ("WATER POLO", "🤽"),
    ("HANDBALL", "🤾"),
    ("JUGGLING", "🤹"),
    ("PERSON IN LOTUS POSITION", "🧘"),
    ("BATH", "🛀"),
    ("SLEEPING ACCOMMODATION", "🛌"),
    ("TWO WOMEN HOLDING HANDS", "👭"),
    ("MAN AND WOMAN HOLDING HANDS", "👫"),
    ("TWO MEN HOLDING HANDS", "👬"),
    ("KISS", "💏"),
    ("COUPLE WITH HEART", "💑"),
    ("FAMILY", "👪"),
    ("BUST IN SILHOUETTE", "👤"),
    ("BUSTS IN SILHOUETTE", "👥"),
    ("PEOPLE HUGGING", "🫂"),
    ("FOOTPRINTS", "👣"),
    ("EMOJI MODIFIER FITZPATRICK TYPE-1-2", "🏻"),
    ("EMOJI MODIFIER FITZPATRICK TYPE-3", "🏼"),
    ("EMOJI MODIFIER FITZPATRICK TYPE-4", "🏽"),
    ("EMOJI MODIFIER FITZPATRICK TYPE-5", "🏾"),
    ("EMOJI MODIFIER FITZPATRICK TYPE-6", "🏿"),
    ("MONKEY FACE", "🐵"),
    ("MONKEY", "🐒"),
    ("GORILLA", "🦍"),
    ("ORANGUTAN", "🦧"),
    ("DOG FACE", "🐶"),
    ("DOG", "🐕"),
    ("GUIDE DOG", "🦮"),
    ("POODLE", "🐩"),
    ("WOLF FACE", "🐺"),
    ("FOX FACE", "🦊"),
    ("RACCOON", "🦝"),
    ("CAT FACE", "🐱"),
    ("CAT", "🐈"),
    ("LION FACE", "🦁"),
    ("TIGER FACE", "🐯"),
    ("TIGER", "🐅"),
    ("LEOPARD", "🐆"),
    ("HORSE FACE", "🐴"),
    ("HORSE", "🐎"),
    ("UNICORN FACE", "🦄"),
    ("ZEBRA FACE", "🦓"),
    ("DEER", "🦌"),
    ("BISON", "🦬"),
    ("COW FACE", "🐮"),
    ("OX", "🐂"),
    ("WATER BUFFALO", "🐃"),
    ("COW", "🐄"),
    ("PIG FACE", "🐷"),
    ("PIG", "🐖"),
    ("BOAR", "🐗"),
    ("PIG NOSE", "🐽"),
    ("RAM", "🐏"),
    ("SHEEP", "🐑"),
    ("GOAT", "🐐"),
    ("DROMEDARY CAMEL", "🐪"),
    ("BACTRIAN CAMEL", "🐫"),
    ("LLAMA", "🦙"),
    ("GIRAFFE FACE", "🦒"),
    ("ELEPHANT", "🐘"),
    ("MAMMOTH", "🦣"),
    ("RHINOCEROS", "🦏"),
    ("HIPPOPOTAMUS", "🦛"),
    ("MOUSE FACE", "🐭"),
    ("MOUSE", "🐁"),
    ("RAT", "🐀"),
    ("HAMSTER FACE", "🐹"),
    ("RABBIT FACE", "🐰"),
    ("RABBIT", "🐇"),
    ("BEAVER", "🦫"),
    ("HEDGEHOG", "🦔"),
    ("BAT", "🦇"),
    ("BEAR FACE", "🐻"),
    ("KOALA", "🐨"),
    ("PANDA FACE", "🐼"),
    ("SLOTH", "🦥"),
    ("OTTER", "🦦"),
    ("SKUNK", "🦨"),
    ("KANGAROO", "🦘"),
    ("BADGER", "🦡"),
    ("PAW PRINTS", "🐾"),
    ("TURKEY", "🦃"),
    ("CHICKEN", "🐔"),
    ("ROOSTER", "🐓"),
    ("HATCHING CHICK", "🐣"),
    ("BABY CHICK", "🐤"),
    ("FRONT-FACING BABY CHICK", "🐥"),
    ("BIRD", "🐦"),
    ("PENGUIN", "🐧"),
    ("EAGLE", "🦅"),
    ("DUCK", "🦆"),
    ("SWAN", "🦢"),
    ("OWL", "🦉"),
    ("DODO", "🦤"),
    ("FEATHER", "🪶"),
    ("FLAMINGO", "🦩"),
    ("PEACOCK", "🦚"),
    ("PARROT", "🦜"),
    ("FROG FACE", "🐸"),
    ("CROCODILE", "🐊"),
    ("TURTLE", "🐢"),
    ("LIZARD", "🦎"),
    ("SNAKE", "🐍"),
    ("DRAGON FACE", "🐲"),
    ("DRAGON", "🐉"),
    ("SAUROPOD", "🦕"),
    ("T-REX", "🦖"),
    ("SPOUTING WHALE", "🐳"),
    ("WHALE", "🐋"),
    ("DOLPHIN", "🐬"),
    ("SEAL", "🦭"),
    ("FISH", "🐟"),
    ("TROPICAL FISH", "🐠"),
    ("BLOWFISH", "🐡"),
    ("SHARK", "🦈"),
    ("OCTOPUS", "🐙"),
    ("SPIRAL SHELL", "🐚"),
    ("SNAIL", "🐌"),
    ("BUTTERFLY", "🦋"),
    ("BUG", "🐛"),
    ("ANT", "🐜"),
    ("HONEYBEE", "🐝"),
    ("BEETLE", "🪲"),
    ("LADY BEETLE", "🐞"),
    ("CRICKET", "🦗"),
    ("COCKROACH", "🪳"),
    ("SCORPION", "🦂"),
    ("MOSQUITO", "🦟"),
    ("FLY", "🪰"),
    ("WORM", "🪱"),
    ("MICROBE", "🦠"),
    ("BOUQUET", "💐"),
    ("CHERRY BLOSSOM", "🌸"),
    ("WHITE FLOWER", "💮"),
    ("ROSE", "🌹"),
    ("WILTED FLOWER", "🥀"),
    ("HIBISCUS", "🌺"),
    ("SUNFLOWER", "🌻"),
    ("BLOSSOM", "🌼"),
    ("TULIP", "🌷"),
    ("SEEDLING", "🌱"),
    ("POTTED PLANT", "🪴"),
    ("EVERGREEN TREE", "🌲"),
    ("DECIDUOUS TREE", "🌳"),
    ("PALM TREE", "🌴"),
    ("CACTUS", "🌵"),
    ("EAR OF RICE", "🌾"),
    ("HERB", "🌿"),
    ("FOUR LEAF CLOVER", "🍀"),
    ("MAPLE LEAF", "🍁"),
    ("FALLEN LEAF", "🍂"),
    ("LEAF FLUTTERING IN WIND", "🍃"),
    ("GRAPES", "🍇"),
    ("MELON", "🍈"),
    ("WATERMELON", "🍉"),
    ("TANGERINE", "🍊"),
    ("LEMON", "🍋"),
    ("BANANA", "🍌"),
    ("PINEAPPLE", "🍍"),
    ("MANGO", "🥭"),
    ("RED APPLE", "🍎"),
    ("GREEN APPLE", "🍏"),
    ("PEAR", "🍐"),
    ("PEACH", "🍑"),
    ("CHERRIES", "🍒"),
    ("STRAWBERRY", "🍓"),
    ("BLUEBERRIES", "🫐"),
    ("KIWIFRUIT", "🥝"),
    ("TOMATO", "🍅"),
    ("OLIVE", "🫒"),
    ("COCONUT", "🥥"),
    ("AVOCADO", "🥑"),
    ("AUBERGINE", "🍆"),
    ("POTATO", "🥔"),
    ("CARROT", "🥕"),
    ("EAR OF MAIZE", "🌽"),
    ("BELL PEPPER", "🫑"),
    ("CUCUMBER", "🥒"),
    ("LEAFY GREEN", "🥬"),
    ("BROCCOLI", "🥦"),
    ("GARLIC", "🧄"),
    ("ONION", "🧅"),
    ("MUSHROOM", "🍄"),
    ("PEANUTS", "🥜"),
    ("CHESTNUT", "🌰"),
    ("BREAD", "🍞"),
    ("CROISSANT", "🥐"),
    ("BAGUETTE BREAD", "🥖"),
    ("FLATBREAD", "🫓"),
    ("PRETZEL", "🥨"),
    ("BAGEL", "🥯"),
    ("PANCAKES", "🥞"),
    ("WAFFLE", "🧇"),
    ("CHEESE WEDGE", "🧀"),
    ("MEAT ON BONE", "🍖"),
    ("POULTRY LEG", "🍗"),
    ("CUT OF MEAT", "🥩"),
    ("BACON", "🥓"),
    ("HAMBURGER", "🍔"),
    ("FRENCH FRIES", "🍟"),
    ("SLICE OF PIZZA", "🍕"),
    ("HOT DOG", "🌭"),
    ("SANDWICH", "🥪"),
    ("TACO", "🌮"),
    ("BURRITO", "🌯"),
    ("TAMALE", "🫔"),
    ("STUFFED FLATBREAD", "🥙"),
    ("FALAFEL", "🧆"),
    ("EGG", "🥚"),
    ("COOKING", "🍳"),
    ("SHALLOW PAN OF FOOD", "🥘"),
    ("POT OF FOOD", "🍲"),
    ("FONDUE", "🫕"),
    ("BOWL WITH SPOON", "🥣"),
    ("GREEN SALAD", "🥗"),
    ("POPCORN", "🍿"),
    ("BUTTER", "🧈"),
    ("SALT SHAKER", "🧂"),
    ("CANNED FOOD", "🥫"),
    ("BENTO BOX", "🍱"),
    ("RICE CRACKER", "🍘"),
    ("RICE BALL", "🍙"),
    ("COOKED RICE", "🍚"),
    ("CURRY AND RICE", "🍛"),
    ("STEAMING BOWL", "🍜"),
    ("SPAGHETTI", "🍝"),
    ("ROASTED SWEET POTATO", "🍠"),
    ("ODEN", "🍢"),
    ("SUSHI", "🍣"),
    ("FRIED SHRIMP", "🍤"),
    ("FISH CAKE WITH SWIRL DESIGN", "🍥"),
    ("MOON CAKE", "🥮"),
    ("DANGO", "🍡"),
    ("DUMPLING", "🥟"),
    ("FORTUNE COOKIE", "🥠"),
    ("TAKEOUT BOX", "🥡"),
    ("CRAB", "🦀"),
    ("LOBSTER", "🦞"),
    ("SHRIMP", "🦐"),
    ("SQUID", "🦑"),
    ("OYSTER", "🦪"),
    ("SOFT ICE CREAM", "🍦"),
    ("SHAVED ICE", "🍧"),
    ("ICE CREAM", "🍨"),
    ("DOUGHNUT", "🍩"),
    ("COOKIE", "🍪"),
    ("BIRTHDAY CAKE", "🎂"),
    ("SHORTCAKE", "🍰"),
    ("CUPCAKE", "🧁"),
    ("PIE", "🥧"),
    ("CHOCOLATE BAR", "🍫"),
    ("CANDY", "🍬"),
    ("LOLLIPOP", "🍭"),
    ("CUSTARD", "🍮"),
    ("HONEY POT", "🍯"),
    ("BABY BOTTLE", "🍼"),
    ("GLASS OF MILK", "🥛"),
    ("HOT BEVERAGE", "☕"),
    ("TEAPOT", "🫖"),
    ("TEACUP WITHOUT HANDLE", "🍵"),
    ("SAKE BOTTLE AND CUP", "🍶"),
    ("BOTTLE WITH POPPING CORK", "🍾"),
    ("WINE GLASS", "🍷"),
    ("COCKTAIL GLASS", "🍸"),
    ("TROPICAL DRINK", "🍹"),
    ("BEER MUG", "🍺"),
    ("CLINKING BEER MUGS", "🍻"),
    ("CLINKING GLASSES", "🥂"),
    ("TUMBLER GLASS", "🥃"),
    ("CUP WITH STRAW", "🥤"),
    ("BUBBLE TEA", "🧋"),
    ("BEVERAGE BOX", "🧃"),
    ("MATE DRINK", "🧉"),
    ("ICE CUBE", "🧊"),
    ("CHOPSTICKS", "🥢"),
    ("FORK AND KNIFE", "🍴"),
    ("SPOON", "🥄"),
    ("HOCHO", "🔪"),
    ("AMPHORA", "🏺"),
    ("EARTH GLOBE EUROPE-AFRICA", "🌍"),
    ("EARTH GLOBE AMERICAS", "🌎"),
    ("EARTH GLOBE ASIA-AUSTRALIA", "🌏"),
    ("GLOBE WITH MERIDIANS", "🌐"),
    ("SILHOUETTE OF JAPAN", "🗾"),
    ("COMPASS", "🧭"),
    ("VOLCANO", "🌋"),
    ("MOUNT FUJI", "🗻"),
    ("BRICK", "🧱"),
    ("ROCK", "🪨"),
    ("WOOD", "🪵"),
    ("HUT", "🛖"),
    ("HOUSE BUILDING", "🏠"),
    ("HOUSE WITH GARDEN", "🏡"),
    ("OFFICE BUILDING", "🏢"),
    ("JAPANESE POST OFFICE", "🏣"),
    ("EUROPEAN POST OFFICE", "🏤"),
    ("HOSPITAL", "🏥"),
    ("BANK", "🏦"),
    ("HOTEL", "🏨"),
    ("LOVE HOTEL", "🏩"),
    ("CONVENIENCE STORE", "🏪"),
    ("SCHOOL", "🏫"),
    ("DEPARTMENT STORE", "🏬"),
    ("FACTORY", "🏭"),
    ("JAPANESE CASTLE", "🏯"),
    ("EUROPEAN CASTLE", "🏰"),
    ("WEDDING", "💒"),
    ("TOKYO TOWER", "🗼"),
    ("STATUE OF LIBERTY", "🗽"),
    ("CHURCH", "⛪"),
    ("MOSQUE", "🕌"),
    ("HINDU TEMPLE", "🛕"),
    ("SYNAGOGUE", "🕍"),
    ("KAABA", "🕋"),
    ("FOUNTAIN", "⛲"),
    ("TENT", "⛺"),
    ("FOGGY", "🌁"),
    ("NIGHT WITH STARS", "🌃"),
    ("SUNRISE OVER MOUNTAINS", "🌄"),
    ("SUNRISE", "🌅"),
    ("CITYSCAPE AT DUSK", "🌆"),
    ("SUNSET OVER BUILDINGS", "🌇"),
    ("BRIDGE AT NIGHT", "🌉"),
    ("CAROUSEL HORSE", "🎠"),
    ("FERRIS WHEEL", "🎡"),
    ("ROLLER COASTER", "🎢"),
    ("BARBER POLE", "💈"),
    ("CIRCUS TENT", "🎪"),
    ("STEAM LOCOMOTIVE", "🚂"),
    ("RAILWAY CAR", "🚃"),
    ("HIGH-SPEED TRAIN", "🚄"),
    ("HIGH-SPEED TRAIN WITH BULLET NOSE", "🚅"),
    ("TRAIN", "🚆"),
    ("METRO", "🚇"),
    ("LIGHT RAIL", "🚈"),
    ("STATION", "🚉"),
    ("TRAM", "🚊"),
    ("MONORAIL", "🚝"),
    ("MOUNTAIN RAILWAY", "🚞"),
    ("TRAM CAR", "🚋"),
    ("BUS", "🚌"),
    ("ONCOMING BUS", "🚍"),
    ("TROLLEYBUS", "🚎"),
    ("MINIBUS", "🚐"),
    ("AMBULANCE", "🚑"),
    ("FIRE ENGINE", "🚒"),
    ("POLICE CAR", "🚓"),
    ("ONCOMING POLICE CAR", "🚔"),
    ("TAXI", "🚕"),
    ("ONCOMING TAXI", "🚖"),
    ("AUTOMOBILE", "🚗"),
    ("ONCOMING AUTOMOBILE", "🚘"),
    ("RECREATIONAL VEHICLE", "🚙"),
    ("PICKUP TRUCK", "🛻"),
    ("DELIVERY TRUCK", "🚚"),
    ("ARTICULATED LORRY", "🚛"),
    ("TRACTOR", "🚜"),
    ("MOTOR SCOOTER", "🛵"),
    ("MANUAL WHEELCHAIR", "🦽"),
    ("MOTORIZED WHEELCHAIR", "🦼"),
    ("AUTO RICKSHAW", "🛺"),
    ("BICYCLE", "🚲"),
    ("SCOOTER", "🛴"),
    ("SKATEBOARD", "🛹"),
    ("ROLLER SKATE", "🛼"),
    ("BUS STOP", "🚏"),
    ("FUEL PUMP", "⛽"),
    ("POLICE CARS REVOLVING LIGHT", "🚨"),
    ("HORIZONTAL TRAFFIC LIGHT", "🚥"),
    ("VERTICAL TRAFFIC LIGHT", "🚦"),
    ("OCTAGONAL SIGN", "🛑"),
    ("CONSTRUCTION SIGN", "🚧"),
    ("ANCHOR", "⚓"),
    ("SAILBOAT", "⛵"),
    ("CANOE", "🛶"),
    ("SPEEDBOAT", "🚤"),
    ("SHIP", "🚢"),
    ("AIRPLANE DEPARTURE", "🛫"),
    ("AIRPLANE ARRIVING", "🛬"),
    ("PARACHUTE", "🪂"),
    ("SEAT", "💺"),
    ("HELICOPTER", "🚁"),
    ("SUSPENSION RAILWAY", "🚟"),
    ("MOUNTAIN CABLEWAY", "🚠"),
    ("AERIAL TRAMWAY", "🚡"),
    ("ROCKET", "🚀"),
    ("FLYING SAUCER", "🛸"),
    ("LUGGAGE", "🧳"),
    ("HOURGLASS", "⌛"),
    ("HOURGLASS WITH FLOWING SAND", "⏳"),
    ("WATCH", "⌚"),
    ("ALARM CLOCK", "⏰"),
    ("CLOCK FACE TWELVE OCLOCK", "🕛"),
    ("CLOCK FACE TWELVE-THIRTY", "🕧"),
    ("CLOCK FACE ONE OCLOCK", "🕐"),
    ("CLOCK FACE ONE-THIRTY", "🕜"),
    ("CLOCK FACE TWO OCLOCK", "🕑"),
    ("CLOCK FACE TWO-THIRTY", "🕝"),
    ("CLOCK FACE THREE OCLOCK", "🕒"),
    ("CLOCK FACE THREE-THIRTY", "🕞"),
    ("CLOCK FACE FOUR OCLOCK", "🕓"),
    ("CLOCK FACE FOUR-THIRTY", "🕟"),
    ("CLOCK FACE FIVE OCLOCK", "🕔"),
    ("CLOCK FACE FIVE-THIRTY", "🕠"),
    ("CLOCK FACE SIX OCLOCK", "🕕"),
    ("CLOCK FACE SIX-THIRTY", "🕡"),
    ("CLOCK FACE SEVEN OCLOCK", "🕖"),
    ("CLOCK FACE SEVEN-THIRTY", "🕢"),
    ("CLOCK FACE EIGHT OCLOCK", "🕗"),
    ("CLOCK FACE EIGHT-THIRTY", "🕣"),
    ("CLOCK FACE NINE OCLOCK", "🕘"),
    ("CLOCK FACE NINE-THIRTY", "🕤"),
    ("CLOCK FACE TEN OCLOCK", "🕙"),
    ("CLOCK FACE TEN-THIRTY", "🕥"),
    ("CLOCK FACE ELEVEN OCLOCK", "🕚"),
    ("CLOCK FACE ELEVEN-THIRTY", "🕦"),
    ("NEW MOON SYMBOL", "🌑"),
    ("WAXING CRESCENT MOON SYMBOL", "🌒"),
    ("FIRST QUARTER MOON SYMBOL", "🌓"),
    ("WAXING GIBBOUS MOON SYMBOL", "🌔"),
    ("FULL MOON SYMBOL", "🌕"),
    ("WANING GIBBOUS MOON SYMBOL", "🌖"),
    ("LAST QUARTER MOON SYMBOL", "🌗"),
    ("WANING CRESCENT MOON SYMBOL", "🌘"),
    ("CRESCENT MOON", "🌙"),
    ("NEW MOON WITH FACE", "🌚"),
    ("FIRST QUARTER MOON WITH FACE", "🌛"),
    ("LAST QUARTER MOON WITH FACE", "🌜"),
    ("FULL MOON WITH FACE", "🌝"),
    ("SUN WITH FACE", "🌞"),
    ("RINGED PLANET", "🪐"),
    ("WHITE MEDIUM STAR", "⭐"),
    ("GLOWING STAR", "🌟"),
    ("SHOOTING STAR", "🌠"),
    ("MILKY WAY", "🌌"),
    ("SUN BEHIND CLOUD", "⛅"),
    ("CYCLONE", "🌀"),
    ("RAINBOW", "🌈"),
    ("CLOSED UMBRELLA", "🌂"),
    ("UMBRELLA WITH RAIN DROPS", "☔"),
    ("HIGH VOLTAGE SIGN", "⚡"),
    ("SNOWMAN WITHOUT SNOW", "⛄"),
    ("FIRE", "🔥"),
    ("DROPLET", "💧"),
    ("WATER WAVE", "🌊"),
    ("JACK-O-LANTERN", "🎃"),
    ("CHRISTMAS TREE", "🎄"),
    ("FIREWORKS", "🎆"),
    ("FIREWORK SPARKLER", "🎇"),
    ("FIRECRACKER", "🧨"),
    ("SPARKLES", "✨"),
    ("BALLOON", "🎈"),
    ("PARTY POPPER", "🎉"),
    ("CONFETTI BALL", "🎊"),
    ("TANABATA TREE", "🎋"),
    ("PINE DECORATION", "🎍"),
    ("JAPANESE DOLLS", "🎎"),
    ("CARP STREAMER", "🎏"),
    ("WIND CHIME", "🎐"),
    ("MOON VIEWING CEREMONY", "🎑"),
    ("RED GIFT ENVELOPE", "🧧"),
    ("RIBBON", "🎀"),
    ("WRAPPED PRESENT", "🎁"),
    ("TICKET", "🎫"),
    ("TROPHY", "🏆"),
    ("SPORTS MEDAL", "🏅"),
    ("FIRST PLACE MEDAL", "🥇"),
    ("SECOND PLACE MEDAL", "🥈"),
    ("THIRD PLACE MEDAL", "🥉"),
    ("SOCCER BALL", "⚽"),
    ("BASEBALL", "⚾"),
    ("SOFTBALL", "🥎"),
    ("BASKETBALL AND HOOP", "🏀"),
    ("VOLLEYBALL", "🏐"),
    ("AMERICAN FOOTBALL", "🏈"),
    ("RUGBY FOOTBALL", "🏉"),
    ("TENNIS RACQUET AND BALL", "🎾"),
    ("FLYING DISC", "🥏"),
    ("BOWLING", "🎳"),
    ("CRICKET BAT AND BALL", "🏏"),
    ("FIELD HOCKEY STICK AND BALL", "🏑"),
    ("ICE HOCKEY STICK AND PUCK", "🏒"),
    ("LACROSSE STICK AND BALL", "🥍"),
    ("TABLE TENNIS PADDLE AND BALL", "🏓"),
    ("BADMINTON RACQUET AND SHUTTLECOCK", "🏸"),
    ("BOXING GLOVE", "🥊"),
    ("MARTIAL ARTS UNIFORM", "🥋"),
    ("GOAL NET", "🥅"),
    ("FLAG IN HOLE", "⛳"),
    ("FISHING POLE AND FISH", "🎣"),
    ("DIVING MASK", "🤿"),
    ("RUNNING SHIRT WITH SASH", "🎽"),
    ("SKI AND SKI BOOT", "🎿"),
    ("SLED", "🛷"),
    ("CURLING STONE", "🥌"),
    ("DIRECT HIT", "🎯"),
    ("YO-YO", "🪀"),
    ("KITE", "🪁"),
    ("BILLIARDS", "🎱"),
    ("CRYSTAL BALL", "🔮"),
    ("MAGIC WAND", "🪄"),
    ("NAZAR AMULET", "🧿"),
    ("VIDEO GAME", "🎮"),
    ("SLOT MACHINE", "🎰"),
    ("GAME DIE", "🎲"),
    ("JIGSAW PUZZLE PIECE", "🧩"),
    ("TEDDY BEAR", "🧸"),
    ("PINATA", "🪅"),
    ("NESTING DOLLS", "🪆"),
    ("PLAYING CARD BLACK JOKER", "🃏"),
    ("MAHJONG TILE RED DRAGON", "🀄"),
    ("FLOWER PLAYING CARDS", "🎴"),
    ("PERFORMING ARTS", "🎭"),
    ("ARTIST PALETTE", "🎨"),
    ("SPOOL OF THREAD", "🧵"),
    ("SEWING NEEDLE", "🪡"),
    ("BALL OF YARN", "🧶"),
    ("KNOT", "🪢"),
    ("EYEGLASSES", "👓"),
    ("GOGGLES", "🥽"),
    ("LAB COAT", "🥼"),
    ("SAFETY VEST", "🦺"),
    ("NECKTIE", "👔"),
    ("T-SHIRT", "👕"),
    ("JEANS", "👖"),
    ("SCARF", "🧣"),
    ("GLOVES", "🧤"),
    ("COAT", "🧥"),
    ("SOCKS", "🧦"),
    ("DRESS", "👗"),
    ("KIMONO", "👘"),
    ("SARI", "🥻"),
    ("ONE-PIECE SWIMSUIT", "🩱"),
    ("BRIEFS", "🩲"),
    ("SHORTS", "🩳"),
    ("BIKINI", "👙"),
    ("WOMANS CLOTHES", "👚"),
    ("PURSE", "👛"),
    ("HANDBAG", "👜"),
    ("POUCH", "👝"),
    ("SCHOOL SATCHEL", "🎒"),
    ("THONG SANDAL", "🩴"),
    ("MANS SHOE", "👞"),
    ("ATHLETIC SHOE", "👟"),
    ("HIKING BOOT", "🥾"),
    ("FLAT SHOE", "🥿"),
    ("HIGH-HEELED SHOE", "👠"),
    ("WOMANS SANDAL", "👡"),
    ("BALLET SHOES", "🩰"),
    ("WOMANS BOOTS", "👢"),
    ("CROWN", "👑"),
    ("WOMANS HAT", "👒"),
    ("TOP HAT", "🎩"),
    ("GRADUATION CAP", "🎓"),
    ("BILLED CAP", "🧢"),
    ("MILITARY HELMET", "🪖"),
    ("PRAYER BEADS", "📿"),
    ("LIPSTICK", "💄"),
    ("RING", "💍"),
    ("GEM STONE", "💎"),
    ("SPEAKER WITH CANCELLATION STROKE", "🔇"),
    ("SPEAKER", "🔈"),
    ("SPEAKER WITH ONE SOUND WAVE", "🔉"),
    ("SPEAKER WITH THREE SOUND WAVES", "🔊"),
    ("PUBLIC ADDRESS LOUDSPEAKER", "📢"),
    ("CHEERING MEGAPHONE", "📣"),
    ("POSTAL HORN", "📯"),
    ("BELL", "🔔"),
    ("BELL WITH CANCELLATION STROKE", "🔕"),
    ("MUSICAL SCORE", "🎼"),
    ("MUSICAL NOTE", "🎵"),
    ("MULTIPLE MUSICAL NOTES", "🎶"),
    ("MICROPHONE", "🎤"),
    ("HEADPHONE", "🎧"),
    ("RADIO", "📻"),
    ("SAXOPHONE", "🎷"),
    ("ACCORDION", "🪗"),
    ("GUITAR", "🎸"),
    ("MUSICAL KEYBOARD", "🎹"),
    ("TRUMPET", "🎺"),
    ("VIOLIN", "🎻"),
    ("BANJO", "🪕"),
    ("DRUM WITH DRUMSTICKS", "🥁"),
    ("LONG DRUM", "🪘"),
    ("MOBILE PHONE", "📱"),
    ("MOBILE PHONE WITH RIGHTWARDS ARROW AT LEFT", "📲"),
    ("TELEPHONE RECEIVER", "📞"),
    ("PAGER", "📟"),
    ("FAX MACHINE", "📠"),
    ("BATTERY", "🔋"),
    ("ELECTRIC PLUG", "🔌"),
    ("PERSONAL COMPUTER", "💻"),
    ("MINIDISC", "💽"),
    ("FLOPPY DISK", "💾"),
    ("OPTICAL DISC", "💿"),
    ("DVD", "📀"),
    ("ABACUS", "🧮"),
    ("MOVIE CAMERA", "🎥"),
    ("CLAPPER BOARD", "🎬"),
    ("TELEVISION", "📺"),
    ("CAMERA", "📷"),
    ("CAMERA WITH FLASH", "📸"),
    ("VIDEO CAMERA", "📹"),
    ("VIDEOCASSETTE", "📼"),
    ("LEFT-POINTING MAGNIFYING GLASS", "🔍"),
    ("RIGHT-POINTING MAGNIFYING GLASS", "🔎"),
    ("ELECTRIC LIGHT BULB", "💡"),
    ("ELECTRIC TORCH", "🔦"),
    ("IZAKAYA LANTERN", "🏮"),
    ("DIYA LAMP", "🪔"),
    ("NOTEBOOK WITH DECORATIVE COVER", "📔"),
    ("CLOSED BOOK", "📕"),
    ("OPEN BOOK", "📖"),
    ("GREEN BOOK", "📗"),
    ("BLUE BOOK", "📘"),
    ("ORANGE BOOK", "📙"),
    ("BOOKS", "📚"),
    ("NOTEBOOK", "📓"),
    ("LEDGER", "📒"),
    ("PAGE WITH CURL", "📃"),
    ("SCROLL", "📜"),
    ("PAGE FACING UP", "📄"),
    ("NEWSPAPER", "📰"),
    ("BOOKMARK TABS", "📑"),
    ("BOOKMARK", "🔖"),
    ("MONEY BAG", "💰"),
    ("COIN", "🪙"),
    ("BANKNOTE WITH YEN SIGN", "💴"),
    ("BANKNOTE WITH DOLLAR SIGN", "💵"),
    ("BANKNOTE WITH EURO SIGN", "💶"),
    ("BANKNOTE WITH POUND SIGN", "💷"),
    ("MONEY WITH WINGS", "💸"),
    ("CREDIT CARD", "💳"),
    ("RECEIPT", "🧾"),
    ("CHART WITH UPWARDS TREND AND YEN SIGN", "💹"),
    ("E-MAIL SYMBOL", "📧"),
    ("INCOMING ENVELOPE", "📨"),
    ("ENVELOPE WITH DOWNWARDS ARROW ABOVE", "📩"),
    ("OUTBOX TRAY", "📤"),
    ("INBOX TRAY", "📥"),
    ("PACKAGE", "📦"),
    ("CLOSED MAILBOX WITH RAISED FLAG", "📫"),
    ("CLOSED MAILBOX WITH LOWERED FLAG", "📪"),
    ("OPEN MAILBOX WITH RAISED FLAG", "📬"),
    ("OPEN MAILBOX WITH LOWERED FLAG", "📭"),
    ("POSTBOX", "📮"),
    ("MEMO", "📝"),
    ("BRIEFCASE", "💼"),
    ("FILE FOLDER", "📁"),
    ("OPEN FILE FOLDER", "📂"),
    ("CALENDAR", "📅"),
    ("TEAR-OFF CALENDAR", "📆"),
    ("CARD INDEX", "📇"),
    ("CHART WITH UPWARDS TREND", "📈"),
    ("CHART WITH DOWNWARDS TREND", "📉"),
    ("BAR CHART", "📊"),
    ("CLIPBOARD", "📋"),
    ("PUSHPIN", "📌"),
    ("ROUND PUSHPIN", "📍"),
    ("PAPERCLIP", "📎"),
    ("STRAIGHT RULER", "📏"),
    ("TRIANGULAR RULER", "📐"),
    ("LOCK", "🔒"),
    ("OPEN LOCK", "🔓"),
    ("LOCK WITH INK PEN", "🔏"),
    ("CLOSED LOCK WITH KEY", "🔐"),
    ("KEY", "🔑"),
    ("HAMMER", "🔨"),
    ("AXE", "🪓"),
    ("PISTOL", "🔫"),
    ("BOOMERANG", "🪃"),
    ("BOW AND ARROW", "🏹"),
    ("CARPENTRY SAW", "🪚"),
    ("WRENCH", "🔧"),
    ("SCREWDRIVER", "🪛"),
    ("NUT AND BOLT", "🔩"),
    ("PROBING CANE", "🦯"),
    ("LINK SYMBOL", "🔗"),
    ("HOOK", "🪝"),
    ("TOOLBOX", "🧰"),
    ("MAGNET", "🧲"),
    ("LADDER", "🪜"),
    ("TEST TUBE", "🧪"),
    ("PETRI DISH", "🧫"),
    ("DNA DOUBLE HELIX", "🧬"),
    ("MICROSCOPE", "🔬"),
    ("TELESCOPE", "🔭"),
    ("SATELLITE ANTENNA", "📡"),
    ("SYRINGE", "💉"),
    ("DROP OF BLOOD", "🩸"),
    ("PILL", "💊"),
    ("ADHESIVE BANDAGE", "🩹"),
    ("STETHOSCOPE", "🩺"),
    ("DOOR", "🚪"),
    ("ELEVATOR", "🛗"),
    ("MIRROR", "🪞"),
    ("WINDOW", "🪟"),
    ("CHAIR", "🪑"),
    ("TOILET", "🚽"),
    ("PLUNGER", "🪠"),
    ("SHOWER", "🚿"),
    ("BATHTUB", "🛁"),
    ("MOUSE TRAP", "🪤"),
    ("RAZOR", "🪒"),
    ("LOTION BOTTLE", "🧴"),
    ("SAFETY PIN", "🧷"),
    ("BROOM", "🧹"),
    ("BASKET", "🧺"),
    ("ROLL OF PAPER", "🧻"),
    ("BUCKET", "🪣"),
    ("BAR OF SOAP", "🧼"),
    ("TOOTHBRUSH", "🪥"),
    ("SPONGE", "🧽"),
    ("FIRE EXTINGUISHER", "🧯"),
    ("SHOPPING TROLLEY", "🛒"),
    ("SMOKING SYMBOL", "🚬"),
    ("HEADSTONE", "🪦"),
    ("MOYAI", "🗿"),
    ("PLACARD", "🪧"),
    ("AUTOMATED TELLER MACHINE", "🏧"),
    ("PUT LITTER IN ITS PLACE SYMBOL", "🚮"),
    ("POTABLE WATER SYMBOL", "🚰"),
    ("WHEELCHAIR SYMBOL", "♿"),
    ("MENS SYMBOL", "🚹"),
    ("WOMENS SYMBOL", "🚺"),
    ("RESTROOM", "🚻"),
    ("BABY SYMBOL", "🚼"),
    ("WATER CLOSET", "🚾"),
    ("PASSPORT CONTROL", "🛂"),
    ("CUSTOMS", "🛃"),
    ("BAGGAGE CLAIM", "🛄"),
    ("LEFT LUGGAGE", "🛅"),
    ("CHILDREN CROSSING", "🚸"),
    ("NO ENTRY", "⛔"),
    ("NO ENTRY SIGN", "🚫"),
    ("NO BICYCLES", "🚳"),
    ("NO SMOKING SYMBOL", "🚭"),
    ("DO NOT LITTER SYMBOL", "🚯"),
    ("NON-POTABLE WATER SYMBOL", "🚱"),
    ("NO PEDESTRIANS", "🚷"),
    ("NO MOBILE PHONES", "📵"),
    ("NO ONE UNDER EIGHTEEN SYMBOL", "🔞"),
    ("CLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS", "🔃"),
    ("ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS", "🔄"),
    ("BACK WITH LEFTWARDS ARROW ABOVE", "🔙"),
    ("END WITH LEFTWARDS ARROW ABOVE", "🔚"),
    ("ON WITH EXCLAMATION MARK WITH LEFT RIGHT ARROW ABOVE", "🔛"),
    ("SOON WITH RIGHTWARDS ARROW ABOVE", "🔜"),
    ("TOP WITH UPWARDS ARROW ABOVE", "🔝"),
    ("PLACE OF WORSHIP", "🛐"),
    ("MENORAH WITH NINE BRANCHES", "🕎"),
    ("SIX POINTED STAR WITH MIDDLE DOT", "🔯"),
    ("ARIES", "♈"),
    ("TAURUS", "♉"),
    ("GEMINI", "♊"),
    ("CANCER", "♋"),
    ("LEO", "♌"),
    ("VIRGO", "♍"),
    ("LIBRA", "♎"),
    ("SCORPIUS", "♏"),
    ("SAGITTARIUS", "♐"),
    ("CAPRICORN", "♑"),
    ("AQUARIUS", "♒"),
    ("PISCES", "♓"),
    ("OPHIUCHUS", "⛎"),
    ("TWISTED RIGHTWARDS ARROWS", "🔀"),
    ("CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS", "🔁"),
    (
        "CLOCKWISE RIGHTWARDS AND LEFTWARDS OPEN CIRCLE ARROWS WITH CIRCLED ONE OVERLAY",
        "🔂",
    ),
    ("BLACK RIGHT-POINTING DOUBLE TRIANGLE", "⏩"),
    ("BLACK LEFT-POINTING DOUBLE TRIANGLE", "⏪"),
    ("UP-POINTING SMALL RED TRIANGLE", "🔼"),
    ("BLACK UP-POINTING DOUBLE TRIANGLE", "⏫"),
    ("DOWN-POINTING SMALL RED TRIANGLE", "🔽"),
    ("BLACK DOWN-POINTING DOUBLE TRIANGLE", "⏬"),
    ("CINEMA", "🎦"),
    ("LOW BRIGHTNESS SYMBOL", "🔅"),
    ("HIGH BRIGHTNESS SYMBOL", "🔆"),
    ("ANTENNA WITH BARS", "📶"),
    ("VIBRATION MODE", "📳"),
    ("MOBILE PHONE OFF", "📴"),
    ("HEAVY PLUS SIGN", "➕"),
    ("HEAVY MINUS SIGN", "➖"),
    ("HEAVY DIVISION SIGN", "➗"),
    ("BLACK QUESTION MARK ORNAMENT", "❓"),
    ("WHITE QUESTION MARK ORNAMENT", "❔"),
    ("WHITE EXCLAMATION MARK ORNAMENT", "❕"),
    ("HEAVY EXCLAMATION MARK SYMBOL", "❗"),
    ("CURRENCY EXCHANGE", "💱"),
    ("HEAVY DOLLAR SIGN", "💲"),
    ("TRIDENT EMBLEM", "🔱"),
    ("NAME BADGE", "📛"),
    ("JAPANESE SYMBOL FOR BEGINNER", "🔰"),
    ("HEAVY LARGE CIRCLE", "⭕"),
    ("WHITE HEAVY CHECK MARK", "✅"),
    ("CROSS MARK", "❌"),
    ("NEGATIVE SQUARED CROSS MARK", "❎"),
    ("CURLY LOOP", "➰"),
    ("DOUBLE CURLY LOOP", "➿"),
    ("KEYCAP TEN", "🔟"),
    ("INPUT SYMBOL FOR LATIN CAPITAL LETTERS", "🔠"),
    ("INPUT SYMBOL FOR LATIN SMALL LETTERS", "🔡"),
    ("INPUT SYMBOL FOR NUMBERS", "🔢"),
    ("INPUT SYMBOL FOR SYMBOLS", "🔣"),
    ("INPUT SYMBOL FOR LATIN LETTERS", "🔤"),
    ("NEGATIVE SQUARED AB", "🆎"),
    ("SQUARED CL", "🆑"),
    ("SQUARED COOL", "🆒"),
    ("SQUARED FREE", "🆓"),
    ("SQUARED ID", "🆔"),
    ("SQUARED NEW", "🆕"),
    ("SQUARED NG", "🆖"),
    ("SQUARED OK", "🆗"),
    ("SQUARED SOS", "🆘"),
    ("SQUARED UP WITH EXCLAMATION MARK", "🆙"),
    ("SQUARED VS", "🆚"),
    ("SQUARED KATAKANA KOKO", "🈁"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-6709", "🈶"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-6307", "🈯"),
    ("CIRCLED IDEOGRAPH ADVANTAGE", "🉐"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-5272", "🈹"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-7121", "🈚"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-7981", "🈲"),
    ("CIRCLED IDEOGRAPH ACCEPT", "🉑"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-7533", "🈸"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-5408", "🈴"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-7A7A", "🈳"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-55B6", "🈺"),
    ("SQUARED CJK UNIFIED IDEOGRAPH-6E80", "🈵"),
    ("LARGE RED CIRCLE", "🔴"),
    ("LARGE ORANGE CIRCLE", "🟠"),
    ("LARGE YELLOW CIRCLE", "🟡"),
    ("LARGE GREEN CIRCLE", "🟢"),
    ("LARGE BLUE CIRCLE", "🔵"),
    ("LARGE PURPLE CIRCLE", "🟣"),
    ("LARGE BROWN CIRCLE", "🟤"),
    ("MEDIUM BLACK CIRCLE", "⚫"),
    ("MEDIUM WHITE CIRCLE", "⚪"),
    ("LARGE RED SQUARE", "🟥"),
    ("LARGE ORANGE SQUARE", "🟧"),
    ("LARGE YELLOW SQUARE", "🟨"),
    ("LARGE GREEN SQUARE", "🟩"),
    ("LARGE BLUE SQUARE", "🟦"),
    ("LARGE PURPLE SQUARE", "🟪"),
    ("LARGE BROWN SQUARE", "🟫"),
    ("BLACK LARGE SQUARE", "⬛"),
    ("WHITE LARGE SQUARE", "⬜"),
    ("BLACK MEDIUM SMALL SQUARE", "◾"),
    ("WHITE MEDIUM SMALL SQUARE", "◽"),
    ("LARGE ORANGE DIAMOND", "🔶"),
    ("LARGE BLUE DIAMOND", "🔷"),
    ("SMALL ORANGE DIAMOND", "🔸"),
    ("SMALL BLUE DIAMOND", "🔹"),
    ("UP-POINTING RED TRIANGLE", "🔺"),
    ("DOWN-POINTING RED TRIANGLE", "🔻"),
    ("DIAMOND SHAPE WITH A DOT INSIDE", "💠"),
    ("RADIO BUTTON", "🔘"),
    ("WHITE SQUARE BUTTON", "🔳"),
    ("BLACK SQUARE BUTTON", "🔲"),
    ("CHEQUERED FLAG", "🏁"),
    ("TRIANGULAR FLAG ON POST", "🚩"),
    ("CROSSED FLAGS", "🎌"),
    ("WAVING BLACK FLAG", "🏴"),
]
