
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-15T12:42:22+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "3ae1cc6fab673fdbdbf5c065426c0e5c3e6a32e5",
 "version": "1.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
