# Generated by Django 3.1.3 on 2021-04-24 12:31


# Disclaimer
# ----------
#
# Copyright (C) 2021 Helmholtz-Zentrum Hereon
# Copyright (C) 2020-2021 Helmholtz-Zentrum Geesthacht
#
# This file is part of django-academic-community and is released under the
# EUPL-1.2 license.
# See LICENSE in the root of the repository for full licensing details.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the EUROPEAN UNION PUBLIC LICENCE v. 1.2 or later
# as published by the European Commission.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# EUPL-1.2 license for more details.
#
# You should have received a copy of the EUPL-1.2 license along with this
# program. If not, see https://www.eupl.eu/.


import djangocms_text_ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationmodel",
            name="description",
            field=djangocms_text_ckeditor.fields.HTMLField(
                blank=True,
                help_text="More details about the model.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="desired_cooperations",
            field=djangocms_text_ckeditor.fields.HTMLField(
                blank=True,
                help_text="More details about (desired) cooperations to other topics and communities.",
                max_length=4000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="publication",
            field=djangocms_text_ckeditor.fields.HTMLField(
                blank=True,
                help_text="Peer-reviewed articles published from this topic.",
                max_length=4000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="references",
            field=djangocms_text_ckeditor.fields.HTMLField(
                blank=True,
                help_text="Other references to this topic.",
                max_length=4000,
                null=True,
            ),
        ),
    ]
