
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-09T19:53:36+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b501ea0eebffe92e8c9c6daa043f0b43df85d50c",
 "version": "0.7.0rc7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
