
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-12T20:29:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "df6cfe53a0a23365b18a9c218fee3cc8615ae177",
 "version": "0.0.169"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
