
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-15T09:07:16+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "86df3b1f81e80e5bf495a920e337a9ce2499fb60",
 "version": "1.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
