
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-05-12T07:28:18-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "1a942ddfd9ffba5598d78557a07a316d1bba5a31",
 "version": "0.0.24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
