# coding: utf-8

"""
    SYSNET CRZP connector API

    SYSNET CRŽP connector REST API (IPPC & CITES extension)  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: info@sysnet.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import crzp
from crzp.models.role_holders import RoleHolders  # noqa: E501
from crzp.rest import ApiException


class TestRoleHolders(unittest.TestCase):
    """RoleHolders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleHolders(self):
        """Test RoleHolders"""
        # FIXME: construct object with mandatory attributes with example values
        # model = crzp.models.role_holders.RoleHolders()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
