from bytez.tasks.text_summarization._models.dmmiller612_bert_extractive_summarization import Dmmiller612BertExtractiveSummarizationModel
from dataclasses import dataclass
from bytez.tasks.text_summarization._models.chriskhanhtran_bert_extractive_summarization import ChriskhanhtranBertExtractiveSummarizationModel


@dataclass
class TextSummarizationModels:
    chriskhanhtran_bert_extractive_summarization = ChriskhanhtranBertExtractiveSummarizationModel().inference
    dmmiller612_bert_extractive_summarization = Dmmiller612BertExtractiveSummarizationModel().inference