# Generated by Django 4.0.2 on 2023-05-14 14:38

import apps.moarc-framework.moarcframework.orm.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moarcframework', '0003_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='mimetype',
            field=apps.moarc-framework.moarcframework.orm.fields.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Tipo de archivo'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='static/attachments/%Y/%m/%d/'),
        ),
    ]
