# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20053_users import InlineResponse20053Users  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20053Users(unittest.TestCase):
    """InlineResponse20053Users unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20053Users(self):
        """Test InlineResponse20053Users"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20053_users.InlineResponse20053Users()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
