# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.body_add_provisioned_vlan_or_range import BodyAddProvisionedVlanOrRange  # noqa: E501
from CommandCenter.rest import ApiException


class TestBodyAddProvisionedVlanOrRange(unittest.TestCase):
    """BodyAddProvisionedVlanOrRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyAddProvisionedVlanOrRange(self):
        """Test BodyAddProvisionedVlanOrRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.body_add_provisioned_vlan_or_range.BodyAddProvisionedVlanOrRange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
