# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.body_create_new_vpsa_upload_endpoint import BodyCreateNewVpsaUploadEndpoint  # noqa: E501
from CommandCenter.rest import ApiException


class TestBodyCreateNewVpsaUploadEndpoint(unittest.TestCase):
    """BodyCreateNewVpsaUploadEndpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyCreateNewVpsaUploadEndpoint(self):
        """Test BodyCreateNewVpsaUploadEndpoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.body_create_new_vpsa_upload_endpoint.BodyCreateNewVpsaUploadEndpoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
