# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.body_get_vpsa_endpoint_configs_by_upload_types import BodyGetVpsaEndpointConfigsByUploadTypes  # noqa: E501
from CommandCenter.rest import ApiException


class TestBodyGetVpsaEndpointConfigsByUploadTypes(unittest.TestCase):
    """BodyGetVpsaEndpointConfigsByUploadTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyGetVpsaEndpointConfigsByUploadTypes(self):
        """Test BodyGetVpsaEndpointConfigsByUploadTypes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.body_get_vpsa_endpoint_configs_by_upload_types.BodyGetVpsaEndpointConfigsByUploadTypes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
