# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20069_pools import InlineResponse20069Pools  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20069Pools(unittest.TestCase):
    """InlineResponse20069Pools unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20069Pools(self):
        """Test InlineResponse20069Pools"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20069_pools.InlineResponse20069Pools()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
