# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20063_vpsas import InlineResponse20063Vpsas  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20063Vpsas(unittest.TestCase):
    """InlineResponse20063Vpsas unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20063Vpsas(self):
        """Test InlineResponse20063Vpsas"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20063_vpsas.InlineResponse20063Vpsas()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
