# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.body_set_default_vlan_for_cloud_user import BodySetDefaultVlanForCloudUser  # noqa: E501
from CommandCenter.rest import ApiException


class TestBodySetDefaultVlanForCloudUser(unittest.TestCase):
    """BodySetDefaultVlanForCloudUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodySetDefaultVlanForCloudUser(self):
        """Test BodySetDefaultVlanForCloudUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.body_set_default_vlan_for_cloud_user.BodySetDefaultVlanForCloudUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
