# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response20018_drive_type import InlineResponse20018DriveType  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse20018DriveType(unittest.TestCase):
    """InlineResponse20018DriveType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20018DriveType(self):
        """Test InlineResponse20018DriveType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response20018_drive_type.InlineResponse20018DriveType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
