# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.body_delete_vrid_from_vlan import BodyDeleteVridFromVlan  # noqa: E501
from CommandCenter.rest import ApiException


class TestBodyDeleteVridFromVlan(unittest.TestCase):
    """BodyDeleteVridFromVlan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBodyDeleteVridFromVlan(self):
        """Test BodyDeleteVridFromVlan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.body_delete_vrid_from_vlan.BodyDeleteVridFromVlan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
