# coding: utf-8

"""
    Command Center operations

    Command Center operations  # noqa: E501

    OpenAPI spec version: v23.8.4
    Contact: support@zadarastorage.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import CommandCenter
from CommandCenter.models.inline_response200102_load_balancer import InlineResponse200102LoadBalancer  # noqa: E501
from CommandCenter.rest import ApiException


class TestInlineResponse200102LoadBalancer(unittest.TestCase):
    """InlineResponse200102LoadBalancer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200102LoadBalancer(self):
        """Test InlineResponse200102LoadBalancer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CommandCenter.models.inline_response200102_load_balancer.InlineResponse200102LoadBalancer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
